/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as ComposioApi from "../../../../api/index";
import * as core from "../../../../core";
import { ApiKeyResDto } from "../../../types/ApiKeyResDto";
export declare const Response: core.serialization.Schema<serializers.apiKeys.listApiKeys.Response.Raw, ComposioApi.ApiKeyResDto[]>;
export declare namespace Response {
    type Raw = ApiKeyResDto.Raw[];
}
