import {
  buildContextVersion,
  isEnabledForBuild,
  renderCommand,
  renderFrontmatter,
  renderReference,
  type BuildContext,
  type SkillReference,
  type SkillSpec,
} from '@composio/skill-spec';

const AUTOGEN_BANNER = '<!-- AUTO-GENERATED by @composio/skill-builder — edit the source spec -->';

const versionComments = (ctx: BuildContext): string[] => {
  const lines: string[] = [
    `<!-- platform: ${ctx.platform} -->`,
    `<!-- channel: ${ctx.channel} -->`,
  ];
  const version = buildContextVersion(ctx);
  if (version.cli) {
    lines.push(`<!-- cli-version: ${version.cli.version} -->`);
  }
  return lines;
};

/**
 * Render the top-level SKILL.md for a built skill artifact.
 */
export const renderSkillMarkdown = (spec: SkillSpec, ctx: BuildContext): string => {
  const lines: string[] = [
    renderFrontmatter(spec.frontmatter),
    '',
    AUTOGEN_BANNER,
    ...versionComments(ctx),
    '',
    `# ${spec.frontmatter.name}`,
  ];

  if (spec.body?.workflow) {
    lines.push('', '## Default Workflow', '', ...spec.body.workflow(ctx));
  }

  const enabledCommands = (spec.body?.commands ?? []).filter(command =>
    isEnabledForBuild(ctx, command)
  );
  for (const command of enabledCommands) {
    lines.push('', renderCommand(ctx, command));
  }

  if (spec.body?.epilogue) {
    lines.push('', ...spec.body.epilogue(ctx));
  }

  return lines.join('\n') + '\n';
};

/**
 * Render every declared reference file into `slug.md` → markdown string pairs.
 */
export const renderSkillReferences = (
  references: readonly SkillReference[],
  ctx: BuildContext
): Record<string, string> => {
  const out: Record<string, string> = {};
  for (const reference of references) {
    out[`${reference.slug}.md`] = renderReference(ctx, reference);
  }
  return out;
};
