/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as ComposioApi from "../../../../index";
/**
 * @example
 *     {
 *         email: "email",
 *         name: "name",
 *         verifyHost: "verifyHost"
 *     }
 */
export interface InviteMemberReqDto {
    /** The email of the member */
    email: string;
    /** The name of the member */
    name: string;
    /** The host to verify the member */
    verifyHost: string;
    /** The role that will be assignied to the invited user */
    role?: ComposioApi.InviteMemberReqDtoRole;
}
