/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Sort the apps by usage or alphabetically
 */
export declare type AppsGetAppsRequestSortBy = "alphabet" | "usage" | "no_sort";
export declare const AppsGetAppsRequestSortBy: {
    readonly Alphabet: "alphabet";
    readonly Usage: "usage";
    readonly NoSort: "no_sort";
};
