/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Type of the log
 */
export declare type LogsGetLogsRequestLogsType = "action" | "trigger";
export declare const LogsGetLogsRequestLogsType: {
    readonly Action: "action";
    readonly Trigger: "trigger";
};
