packages:
- "ts/packages/core"
- "ts/packages/cli"
- "ts/packages/json-schema-to-zod"
- "ts/packages/providers/*"
- "ts/packages/ts-builders"
- "ts/packages/wrappers/*"
- "ts/examples/*"
- "fern"
- "fern/llms-txt"
- "fern/pages/examples/*"
- "fern/snippets/*"
