packages:
  - "ts/packages/core"
  - "ts/packages/json-schema-to-zod"
  - "ts/packages/providers/*"
  - "ts/packages/wrappers/*"
  - "ts/examples/*"
  - "fern"
  - "fern/pages/examples/*"
  - "fern/snippets/*"
