packages:
  - ts/packages/core
  - ts/packages/cli
  - ts/packages/json-schema-to-zod
  - ts/packages/providers/*
  - ts/packages/ts-builders
  - ts/packages/wrappers/*
  - ts/examples/*
  - fern
  - fern/llms-txt-worker
  - fern/pages/examples/*
  - fern/snippets/*

catalog:
  "@composio/client": 0.1.0-alpha.37
  "@cloudflare/vitest-pool-workers": ^0.9.2
  "@cloudflare/workers-types": ^4.20250917.0
  "ai": ^5.0.44
  "openai": ^5.20.3
  "uuid": ^13.0.0
  "tsup": ^8.5.0
  "tsx": ^4.20.5
  "typescript": ^5.9.2
  "vitest": ^3.2.4
  "wrangler": ^4.37.0

minimumReleaseAge: 1440

# See: https://pnpm.io/settings#minimumreleaseage
minimumReleaseAge: 1440 # 1 day
minimumReleaseAgeExclude:
  - "@composio/client"
