packages:
  - ts/packages/core
  - ts/packages/cli
  - ts/packages/json-schema-to-zod
  - ts/packages/json-schema-to-zod/test/e2e/*
  - ts/packages/providers/*
  - ts/packages/ts-builders
  - ts/packages/wrappers/*
  - ts/examples/*
  - fern
  - fern/llms-txt-worker
  - fern/pages/examples/*
  - fern/snippets/*

catalog:
  '@cloudflare/vitest-pool-workers': ^0.9.2
  '@cloudflare/workers-types': ^4.20250917.0
  '@composio/client': 0.1.0-alpha.52
  '@modelcontextprotocol/sdk': ^1.24.0
  ai: 5.0.52
  openai: ^5.20.3
  tsup: ^8.5.0
  tsdown: ^0.16.8
  tsx: ^4.20.5
  typescript: ^5.9.2
  uuid: ^13.0.0
  vitest: ^3.2.4
  wrangler: ^4.37.0
  zod: ^4.1.0
  zod-to-json-schema: ^3.25.0

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - '@composio/client'
