/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../index";
import * as ComposioApi from "../../../../../api/index";
import * as core from "../../../../../core";
import { AuthConfigDto } from "../../../../types/AuthConfigDto";
export declare const CreateConnectorPayloadDto: core.serialization.Schema<serializers.CreateConnectorPayloadDto.Raw, ComposioApi.CreateConnectorPayloadDto>;
export declare namespace CreateConnectorPayloadDto {
    interface Raw {
        name: string;
        authScheme?: string | null;
        authConfig?: AuthConfigDto.Raw | null;
        useComposioAuth?: boolean | null;
        appId?: string | null;
        appName?: string | null;
        forceNewIntegration?: boolean | null;
    }
}
