/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {
 *         key: "key"
 *     }
 */
export interface CliGetCliCodeRequest {
    key: string;
    code?: string;
}
