/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {
 *         providerName: "providerName",
 *         actionName: "actionName",
 *         request: {
 *             "key": "value"
 *         },
 *         response: {
 *             "key": "value"
 *         },
 *         isError: true
 *     }
 */
export interface IngestDataDto {
    /** Connection ID of the log */
    connectionId?: string;
    /** Session ID of the log */
    sessionId?: string;
    /** Type of the log */
    logsType?: string;
    /** Entity ID of the log */
    entityId?: string;
    /** Provider name of the log */
    providerName: string;
    /** Action name of the log */
    actionName: string;
    request: Record<string, unknown>;
    response: Record<string, unknown>;
    isError: boolean;
}
