FROM composio/composio:latest

# Install dependencies
RUN apt install -y make build-essential libssl-dev zlib1g-dev libbz2-dev \
    libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev \
    xz-utils tk-dev libffi-dev liblzma-dev

# Switch user
USER user

# Go to user dir
WORKDIR /home/user

# Install pyenv
RUN curl https://pyenv.run | bash

# Switch to root
USER root
