"use strict";
// This file is auto-generated by @hey-api/openapi-ts
exports.__esModule = true;
exports.AuthScheme = void 0;
var AuthScheme;
(function (AuthScheme) {
    AuthScheme["OAUTH2"] = "OAUTH2";
    AuthScheme["API_KEY"] = "API_KEY";
    AuthScheme["OAUTH1"] = "OAUTH1";
})(AuthScheme = exports.AuthScheme || (exports.AuthScheme = {}));
