"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ComposioApiClient = void 0;
const Client_1 = require("./api/resources/auth/client/Client");
const Client_2 = require("./api/resources/client/client/Client");
const Client_3 = require("./api/resources/team/client/Client");
const Client_4 = require("./api/resources/apiKeys/client/Client");
const Client_5 = require("./api/resources/apps/client/Client");
const Client_6 = require("./api/resources/integrations/client/Client");
const Client_7 = require("./api/resources/actions/client/Client");
const Client_8 = require("./api/resources/connections/client/Client");
const Client_9 = require("./api/resources/triggers/client/Client");
const Client_10 = require("./api/resources/cli/client/Client");
const Client_11 = require("./api/resources/logs/client/Client");
const Client_12 = require("./api/resources/projects/client/Client");
const Client_13 = require("./api/resources/admin/client/Client");
const Client_14 = require("./api/resources/analytics/client/Client");
const Client_15 = require("./api/resources/eventLogs/client/Client");
class ComposioApiClient {
    constructor(_options) {
        this._options = _options;
    }
    get auth() {
        var _a;
        return ((_a = this._auth) !== null && _a !== void 0 ? _a : (this._auth = new Client_1.Auth(this._options)));
    }
    get client() {
        var _a;
        return ((_a = this._client) !== null && _a !== void 0 ? _a : (this._client = new Client_2.Client(this._options)));
    }
    get team() {
        var _a;
        return ((_a = this._team) !== null && _a !== void 0 ? _a : (this._team = new Client_3.Team(this._options)));
    }
    get apiKeys() {
        var _a;
        return ((_a = this._apiKeys) !== null && _a !== void 0 ? _a : (this._apiKeys = new Client_4.ApiKeys(this._options)));
    }
    get apps() {
        var _a;
        return ((_a = this._apps) !== null && _a !== void 0 ? _a : (this._apps = new Client_5.Apps(this._options)));
    }
    get integrations() {
        var _a;
        return ((_a = this._integrations) !== null && _a !== void 0 ? _a : (this._integrations = new Client_6.Integrations(this._options)));
    }
    get actions() {
        var _a;
        return ((_a = this._actions) !== null && _a !== void 0 ? _a : (this._actions = new Client_7.Actions(this._options)));
    }
    get connections() {
        var _a;
        return ((_a = this._connections) !== null && _a !== void 0 ? _a : (this._connections = new Client_8.Connections(this._options)));
    }
    get triggers() {
        var _a;
        return ((_a = this._triggers) !== null && _a !== void 0 ? _a : (this._triggers = new Client_9.Triggers(this._options)));
    }
    get cli() {
        var _a;
        return ((_a = this._cli) !== null && _a !== void 0 ? _a : (this._cli = new Client_10.Cli(this._options)));
    }
    get logs() {
        var _a;
        return ((_a = this._logs) !== null && _a !== void 0 ? _a : (this._logs = new Client_11.Logs(this._options)));
    }
    get projects() {
        var _a;
        return ((_a = this._projects) !== null && _a !== void 0 ? _a : (this._projects = new Client_12.Projects(this._options)));
    }
    get admin() {
        var _a;
        return ((_a = this._admin) !== null && _a !== void 0 ? _a : (this._admin = new Client_13.Admin(this._options)));
    }
    get analytics() {
        var _a;
        return ((_a = this._analytics) !== null && _a !== void 0 ? _a : (this._analytics = new Client_14.Analytics(this._options)));
    }
    get eventLogs() {
        var _a;
        return ((_a = this._eventLogs) !== null && _a !== void 0 ? _a : (this._eventLogs = new Client_15.EventLogs(this._options)));
    }
}
exports.ComposioApiClient = ComposioApiClient;
