/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../index";
import * as ComposioApi from "../../../../../api/index";
import * as core from "../../../../../core";
export declare const UpdateConnectionLabelsPayloadDto: core.serialization.Schema<serializers.UpdateConnectionLabelsPayloadDto.Raw, ComposioApi.UpdateConnectionLabelsPayloadDto>;
export declare namespace UpdateConnectionLabelsPayloadDto {
    interface Raw {
        labels: string[];
    }
}
