export const APPURLS: Record<string, string> = {
  digicert: "https://www.digicert.com/",
  textrazor: "https://www.textrazor.com",
  appdrag: "https://appdrag.com/",
  timekit: "https://www.timekit.io/",
  chmeetings: "https://www.chmeetings.com/",
  moxie: "https://moxiebeauty.in",
  maintainx: "https://www.getmaintainx.com",
  amcards: "https://amcards.com/user/",
  ably: "https://ably.com",
  attio: "https://attio.com",
  browserhub: "https://browserhub.io/",
  linkhut: "https://linkhut.org/",
  bugbug: "https://bugbug.io",
  lmnt: "https://drinklmnt.com",
  seismic: "https://seismic.com/",
  freshdesk: "https://www.freshworks.com/",
  linkedin_beta: "https://linkedin.com/",
  interzoid: "https://www.interzoid.com/",
  contentful: "https://www.contentful.com/",
  googleads: "https://ads.google.com",
  klipfolio: "https://www.klipfolio.com",
  guru: "https://www.guru.com/",
  zenserp: "https://zenserp.com",
  smartrecruiters: "https://www.smartrecruiters.com",
  workiom: "https://workiom.com",
  printnode: "https://www.printnode.com/en",
  datarobot: "https://www.datarobot.com/",
  placekey: "https://www.placekey.io/",
  lexoffice: "https://office.lexware.de/",
  finage: "https://finage.co.uk/",
  googletasks: "https://tasks.google.com/tasks/",
  oncehub: "https://oncehub.com",
  venly: "https://www.venly.io",
  tapform: "https://tapform.io/",
  ncscale: "https://www.ncscale.com",
  docmosis: "https://www.docmosis.com",
  humanloop: "https://humanloop.com",
  datagma: "https://datagma.com/",
  webflow: "https://webflow.com",
  twitter: "https://x.com",
  shortcut: "https://www.shortcut.com",
  timecamp: "https://www.timecamp.com",
  baserow: "https://baserow.io/",
  dailybot: "https://www.dailybot.com/",
  bench: "https://bench.com/",
  botbaba: "https://botbaba.io",
  freshbooks: "https://www.freshbooks.com/",
  typefully: "https://typefully.com/",
  ngrok: "https://ngrok.com/",
  microsoft_clarity: "https://clarity.microsoft.com",
  simplesat: "https://www.simplesat.io/",
  mboum: "https://mboum.com",
  zoho_inventory: "https://www.zoho.com/us/inventory/",
  monday: "https://monday.com/",
  process_street: "https://www.process.st",
  tinyurl: "https://www.tinyurl.com",
  tinypng: "https://tinypng.com",
  helcim: "https://www.helcim.com/",
  smugmug: "https://www.smugmug.com/",
  waboxapp: "https://www.waboxapp.com",
  chatwork: "https://go.chatwork.com",
  rafflys: "https://app-sorteos.com/en",
  braintree:
    "https://www.paypal.com/us/braintree?utm_campaign=Braintree_Migration&utm_medium=Website&utm_source=Braintree",
  hackernews: "https://news.ycombinator.com/",
  altoviz: "https://altoviz.com/en/",
  productboard: "https://www.productboard.com",
  qualaroo: "https://qualaroo.com/",
  piggy: "https://www.piggy.eu/",
  vero: "https://vero.co/",
  ahrefs: "https://ahrefs.com/",
  toneden: "https://www.toneden.io/",
  opensea: "https://opensea.io",
  borneo: "https://www.borneo.com",
  bannerbear: "https://www.bannerbear.com/",
  box: "https://www.box.com",
  discord: "https://discord.com",
  brightpearl: "https://www.brightpearl.com",
  servicem8: "https://www.servicem8.com",
  docusign: "https://www.docusign.com",
  close: "https://www.close.com",
  amazon: "https://www.amazon.in/",
  gitlab: "https://about.gitlab.com",
  bill: "https://www.bill.com",
  microsoft_tenant:
    "https://learn.microsoft.com/en-us/microsoft-365/solutions/tenant-management-overview?view=o365-worldwide",
  zoho_invoice: "https://www.zoho.com/us/invoice/",
  heroku: "https://heroku.com",
  customer_io: "https://customer.io",
  testapp: "...",
  mural: "https://www.mural.co",
  zenrows: "https://www.zenrows.com/",
  foursquare_v1: "https://foursquare.com",
  mailerlite: "https://www.mailerlite.com",
  lever_sandbox: "https://www.lever.co",
  slackbot: "https://slack.com/intl/en-in/",
  composio_search: "https://composio.dev",
  formsite: "https://www.formsite.com/",
  screenshotone: "https://screenshotone.com/",
  google_analytics: "https://analytics.google.com",
  sendgrid: "https://login.sendgrid.com",
  bamboohr: "https://www.bamboohr.com",
  affinity: "https://www.affinity.co/",
  stack_exchange: "https://www.stackexchange.com",
  blackbaud: "https://www.blackbaud.com/",
  ring_central: "https://www.ringcentral.com/",
  terminus: "https://termius.com",
  firecrawl: "https://www.firecrawl.dev/",
  hackerrank_work: "https://www.hackerrank.com/work",
  yousearch: "https://you.com/",
  onedrive:
    "https://www.microsoft.com/en-in/microsoft-365/onedrive/online-cloud-storage/",
  xero: "https://www.xero.com/",
  beeminder: "https://www.beeminder.com/",
  pagerduty: "https://www.pagerduty.com",
  brex: "https://www.brex.com/",
  highlevel: "https://www.gohighlevel.com/",
  klaviyo: "https://www.klaviyo.com/",
  coinbase: "https://www.coinbase.com/en-in",
  zoho: "https://www.zoho.com",
  wiz: "https://www.wiz.io/",
  wrike: "https://www.wrike.com",
  microsoft_teams: "https://www.microsoft.com/",
  square: "https://squareup.com",
  spotify: "https://spotify.com",
  inducedai: "https://induced.ai",
  pipedrive: "https://www.pipedrive.com/",
  workspace: "...",
  linear: "https://linear.app",
  canva: "https://www.canva.com",
  multionai: "https://www.theagi.company/",
  browseai: "https://www.browseai.com",
  exa: "https://exa.ai",
  crustdata: "https://crustdata.com/",
  ravenseotools: "https://raventools.com/",
  lever: "https://www.lever.co",
  cloudflare: "https://www.cloudflare.com/",
  intercom: "https://www.intercom.com",
  d2lbrightspace: "https://www.d2l.com/brightspace/",
  axonaut: "https://axonaut.com/",
  excel: "https://excel.cloud.microsoft/en-us/",
  factorial: "https://factorialhr.com",
  workable: "https://workable.com",
  tisane: "https://tisane.ai/",
  more_trees: "https://www.moretrees.eco/",
  miro: "https://miro.com/",
  shopify: "https://www.shopify.com",
  brandfetch: "https://brandfetch.com",
  browserbase: "https://browserbase.com",
  deel: "https://www.deel.com/",
  timely: "https://www.timelyapp.com",
  fitbit: "https://www.fitbit.com/dev",
  moz: "https://moz.com/",
  accelo: "https://www.accelo.com/",
  typeform: "https://typeform.com",
  googlesheets: "https://sheets.google.com/",
  semrush: "https://www.semrush.com/",
  clickup: "https://clickup.com",
  quickbooks: "https://quickbooks.intuit.com",
  foursquare: "https://www.foursquare.com",
  semanticscholar: "https://www.semanticscholar.org",
  mailchimp: "https://mailchimp.com/",
  strava: "https://strava.com",
  recallai: "https://www.recall.ai/",
  twitter_media: "https://x.com/",
  snowflake: "https://www.snowflake.com/en/",
  amplitude: "https://amplitude.com/",
  gumroad: "https://gumroad.com",
  peopledatalabs: "https://www.peopledatalabs.com/",
  youtube: "https://www.youtube.com",
  demio: "https://www.demio.com",
  codeinterpreter: "...",
  linkup: "https://www.linkup.com/",
  zoho_books: "https://www.zoho.com/us/books/",
  splitwise: "https://splitwise.com",
  bubble: "https://bubble.io/",
  mixpanel: "https://mixpanel.com/",
  keap: "https://keap.com",
  formcarry: "https://formcarry.com/",
  cal: "https://cal.com",
  canvas: "https://www.instructure.com/canvas",
  notion: "https://www.notion.so",
  elevenlabs: "https://www.elevenlabs.io",
  supabase: "https://supabase.com",
  hubspot: "https://www.hubspot.com/",
  agencyzoom: "https://www.agencyzoom.com/",
  harvest: "https://www.getharvest.com/",
  visme: "https://www.visme.co",
  googlemaps: "https://www.google.com/maps",
  fireflies: "https://www.fireflies.ai",
  metatextai: "https://metatext.ai",
  airtable: "https://www.airtable.com/",
  adobe: "https://get.adobe.com/reader/otherversions",
  googlesuper: "https://www.google.com/",
  todoist: "https://www.todoist.com/",
  survey_monkey: "https://www.surveymonkey.com/",
  discordbot: "https://discord.com/",
  entelligence: "https://www.entelligence.ai/",
  googlebigquery: "https://cloud.google.com/bigquery",
  retellai: "https://www.retellai.com/",
  soundcloud: "https://soundcloud.com",
  pplx: "https://perplexity.ai",
  exist: "https://exist.io/",
  texttopdf: "...",
  jira: "https://www.atlassian.com/software/jira",
  github: "https://github.com/",
  figma: "https://www.figma.com/",
  mopinion: "https://www.mopinion.com",
  facebook: "https://www.facebook.com/",
  weathermap: "https://openweathermap.org/weathermap",
  dynamics365: "https://www.microsoft.com/en-in/",
  atlassian: "https://www.atlassian.com/",
  eventbrite: "https://www.eventbrite.com/",
  googlephotos: "https://photos.google.com",
  webex: "https://www.webex.com/",
  apollo: "https://www.apollo.io/",
  gotowebinar: "https://gotowebinar.com",
  zendesk: "https://www.zendesk.com/",
  heygen: "https://www.heygen.com",
  flutterwave: "https://flutterwave.com/eu/",
  kommo: "https://www.kommo.com",
  bitwarden: "https://bitwarden.com/",
  zoho_desk: "https://www.zoho.com/desk",
  ideascale: "https://ideascale.com",
  breezyhr: "https://breezy.hr/",
  yandex: "https://yandex.com/",
  junglescout: "https://www.junglescout.com",
  reddit: "https://www.reddit.com",
  okta: "https://okta.com",
  datadog: "https://www.datadoghq.com",
  battlenet: "https://us.shop.battle.net/en-us#optLogin=true",
  confluence: "https://www.atlassian.com/software/confluence",
  sharepoint:
    "https://www.microsoft.com/en-in/microsoft-365/sharepoint/collaboration/",
  boldsign: "https://boldsign.com/",
  neon: "https://neon.tech/",
  bolna: "https://www.bolna.ai/",
  rocket_reach: "https://www.rocketreach.co",
  zoom: "https://www.zoom.com/",
  pandadoc: "https://www.pandadoc.com/",
  dropbox: "https://www.dropbox.com",
  wave_accounting: "https://www.waveapps.com",
  rippling: "https://www.rippling.com/",
  icims_talent_cloud: "https://www.icims.com/products/talent-cloud-recruiting/",
  salesforce: "https://www.salesforce.com/in/",
  foursquare_v2: "https://foursquare.com",
  ashby: "https://www.ashbyhq.com",
  mem0: "https://mem0.ai/",
  dialpad: "https://www.dialpad.com/",
  slack: "https://slack.com/intl/en-in//",
  ramp: "https://ramp.com/",
  googlemeet: "https://meet.google.com/",
  posthog: "https://posthog.com/",
  googlecalendar: "https://calendar.google.com",
  serpapi: "https://serpapi.com/",
  dropbox_sign: "https://sign.dropbox.com",
  zoho_mail: "https://www.zoho.com/mail/",
  brex_staging: "https://www.brex.com/",
  zoho_bigin: "https://www.bigin.com",
  trello: "https://trello.com",
  googledrive: "https://drive.google.com",
  tavily: "https://tavily.com",
  bitbucket: "https://bitbucket.org/",
  rocketlane: "https://www.rocketlane.com",
  composio: "https://composio.dev",
  calendly: "https://calendly.com/",
  fomo: "https://fomo.com",
  precoro: "https://precoro.com/",
  apaleo: "https://apaleo.com",
  lastpass: "https://www.lastpass.com",
  launch_darkly: "https://launchdarkly.com",
  servicenow: "https://www.servicenow.com",
  sentry: "https://sentry.io/welcome/",
  twitch: "https://www.twitch.tv/",
  auth0: "https://auth0.com",
  appsflyer: "https://www.appsflyer.com/",
  netsuite: "https://www.netsuite.com",
  onepage: "https://onepagerapp.com",
  front: "https://frontapp.com",
  acculynx: "https://acculynx.com",
  zoominfo: "https://www.zoominfo.com/",
  meta_ads: "https://business.meta.com/",
  gong: "https://www.gong.io",
  listennotes: "https://www.listennotes.com",
  brevo: "https://www.brevo.com/",
  aero_workflow: "https://www.aeroworkflow.com/",
  asana: "https://asana.com/",
  blackboard: "https://www.blackboard.com",
  gorgias: "https://www.gorgias.com",
  coda: "https://coda.io/",
  apify: "https://apify.com",
  gmail: "https://mail.google.com",
  googledocs: "https://docs.google.com",
  active_campaign: "https://www.activecampaign.com",
  taskade: "https://www.taskade.com",
  whatsapp: "https://web.whatsapp.com/",
  mocean: "https://www.mocean.energy",
  epic_games: "https://store.epicgames.com/en-US/",
  resend: "https://resend.com",
  sage: "https://www.sage.com/en-gb/",
  linkedin: "https://linkedin.com/",
  twilio: "https://twilio.com/en-us",
  stripe: "https://stripe.com",
  ynab: "https://www.ynab.com",
  alchemy: "https://www.alchemy.com/",
  binance: "https://binance.com/en",
  wakatime: "https://wakatime.com/",
  outlook:
    "https://www.microsoft.com/en-in/microsoft-365/outlook/email-and-calendar-software-microsoft-outlook",
  echtpost: "https://echtpost.de/login",
  nasa: "https://nasa.gov",
  coinmarketcal: "https://coinmarketcal.com/en/",
};

export const APP_NAMES: Record<string, string> = {
  digicert: "DigiCert",
  textrazor: "TextRazor",
  appdrag: "AppDrag",
  timekit: "Timekit",
  chmeetings: "CHMeetings",
  moxie: "Moxie",
  maintainx: "MaintainX",
  amcards: "Amcards",
  ably: "Ably",
  attio: "Attio",
  browserhub: "BrowserHub",
  linkhut: "LinkHut",
  bugbug: "bugbug",
  lmnt: "LMNT",
  seismic: "Seismic",
  freshdesk: "Freshdesk",
  linkedin_beta: "LinkedIn",
  interzoid: "Interzoid",
  contentful: "Contentful",
  googleads: "Google Ads",
  klipfolio: "Klipfolio",
  guru: "Guru",
  zenserp: "Zenserp",
  smartrecruiters: "Smart Recruiters",
  workiom: "Workiom",
  printnode: "PrintNode",
  datarobot: "DataRobot",
  placekey: "Placekey",
  lexoffice: "Lexoffice",
  finage: "Finage",
  googletasks: "Google Tasks",
  oncehub: "OnceHub",
  venly: "Venly",
  tapform: "Tapform",
  ncscale: "ncScale",
  docmosis: "Docmosis",
  humanloop: "Humanloop",
  datagma: "Datagma",
  webflow: "Webflow",
  twitter: "Twitter",
  shortcut: "Shortcut",
  timecamp: "TimeCamp",
  baserow: "Baserow",
  dailybot: "DailyBot",
  bench: "Bench",
  botbaba: "Botbaba",
  freshbooks: "Freshbooks",
  typefully: "Typefully",
  ngrok: "Ngrok",
  microsoft_clarity: "Microsoft Clarity",
  simplesat: "Simplesat",
  mboum: "Mboum",
  zoho_inventory: "Zoho Inventory",
  monday: "Monday",
  process_street: "Process Street",
  tinyurl: "TinyURL",
  tinypng: "TinyPNG",
  helcim: "Helcim",
  smugmug: "Smugmug",
  waboxapp: "Waboxapp",
  chatwork: "Chatwork",
  rafflys: "Rafflys",
  braintree: "Braintree",
  hackernews: "HackerNews",
  altoviz: "Altoviz",
  productboard: "Productboard",
  qualaroo: "Qualaroo",
  piggy: "Piggy",
  vero: "Vero",
  ahrefs: "Ahrefs",
  toneden: "ToneDen",
  opensea: "OpenSea",
  borneo: "Borneo",
  bannerbear: "Bannerbear",
  box: "box",
  discord: "Discord",
  brightpearl: "Brightpearl",
  servicem8: "ServiceM8",
  docusign: "DocuSign eSignature",
  close: "Close",
  amazon: "Amazon",
  gitlab: "GitLab",
  bill: "Bill",
  microsoft_tenant: "Microsoft Tenant",
  zoho_invoice: "Zoho Invoice",
  heroku: "Heroku",
  customer_io: "Customer.io",
  testapp: "testapp",
  mural: "Mural",
  zenrows: "Zenrows",
  foursquare_v1: "Foursquare Search",
  mailerlite: "MailerLite",
  lever_sandbox: "Lever",
  slackbot: "Slack Bot",
  composio_search: "Composio Search",
  formsite: "Formsite",
  screenshotone: "ScreenshotOne",
  google_analytics: "Google Analytics",
  sendgrid: "SendGrid",
  bamboohr: "BambooHR",
  affinity: "Affinity",
  stack_exchange: "Stack Exchange",
  blackbaud: "Blackbaud",
  ring_central: "RingCentral",
  terminus: "Terminus",
  firecrawl: "FireCrawl",
  hackerrank_work: "HackerRank",
  yousearch: "You.com",
  onedrive: "One Drive",
  xero: "Xero",
  beeminder: "Beeminder",
  pagerduty: "PagerDuty",
  brex: "Brex",
  highlevel: "HighLevel",
  klaviyo: "Klaviyo",
  coinbase: "Coinbase",
  zoho: "Zoho CRM",
  wiz: "Wiz",
  wrike: "Wrike",
  microsoft_teams: "Microsoft Teams",
  square: "Square",
  spotify: "Spotify",
  inducedai: "Induced AI",
  pipedrive: "Pipedrive",
  workspace: "Workspace",
  linear: "Linear",
  canva: "Canva",
  multionai: "MultionAI",
  browseai: "Browse.ai",
  exa: "Exa",
  crustdata: "Crustdata",
  ravenseotools: "Raven SEO Tools",
  lever: "Lever",
  cloudflare: "Cloudflare",
  intercom: "Intercom",
  d2lbrightspace: "D2L Brightspace",
  axonaut: "Axonaut",
  excel: "Excel",
  factorial: "Factorial",
  workable: "Workable",
  tisane: "Tisane Labs",
  more_trees: "More Trees",
  miro: "Miro",
  shopify: "Shopify",
  brandfetch: "Brandfetch",
  browserbase: "Browserbase",
  deel: "Deel",
  timely: "Timely",
  fitbit: "Fitbit",
  moz: "Moz API",
  accelo: "Accelo",
  typeform: "Typeform",
  googlesheets: "Google Sheets",
  semrush: "Semrush",
  clickup: "ClickUp",
  quickbooks: "QuickBooks",
  foursquare: "Foursquare Search",
  semanticscholar: "Semantic Scholar",
  mailchimp: "Mailchimp",
  strava: "Strava",
  recallai: "Recall AI",
  twitter_media: "Twitter",
  snowflake: "Snowflake",
  amplitude: "Amplitude",
  gumroad: "Gumroad",
  peopledatalabs: "People Data Labs",
  youtube: "Youtube",
  demio: "Demio",
  codeinterpreter: "CodeInterpreter",
  linkup: "Linkup",
  zoho_books: "Zoho Books",
  splitwise: "Splitwise",
  bubble: "Bubble",
  mixpanel: "Mixpanel",
  keap: "Keap",
  formcarry: "Formcarry",
  cal: "Cal.com",
  canvas: "Canvas",
  notion: "Notion",
  elevenlabs: "Eleven Labs",
  supabase: "Supabase",
  hubspot: "Hubspot",
  agencyzoom: "AgencyZoom",
  harvest: "Harvest",
  visme: "Visme",
  googlemaps: "Google Maps",
  fireflies: "Fireflies",
  metatextai: "Metatext AI",
  airtable: "Airtable",
  adobe: "Adobe API",
  googlesuper: "Google Super",
  todoist: "Todoist",
  survey_monkey: "Survey Monkey",
  discordbot: "Discord Bot",
  entelligence: "Entelligence",
  googlebigquery: "Google BigQuery",
  retellai: "Retell AI",
  soundcloud: "SoundCloud",
  pplx: "Perplexity AI",
  exist: "Exist",
  texttopdf: "Text to PDF",
  jira: "Jira",
  github: "GitHub",
  figma: "Figma",
  mopinion: "Mopinion",
  facebook: "Facebook",
  weathermap: "WeatherMap",
  dynamics365: "Microsoft Dynamics 365",
  atlassian: "Atlassian",
  eventbrite: "Eventbrite",
  googlephotos: "Google Photos",
  webex: "Webex",
  apollo: "Apollo",
  gotowebinar: "GoToWebinar",
  zendesk: "Zendesk",
  heygen: "Heygen",
  flutterwave: "Flutterwave",
  kommo: "Kommo",
  bitwarden: "Bitwarden",
  zoho_desk: "Zoho Desk",
  ideascale: "IdeaScale",
  breezyhr: "BreezyHR",
  yandex: "Yandex",
  junglescout: "Jungle Scout",
  reddit: "Reddit",
  okta: "okta",
  datadog: "Datadog",
  battlenet: "Battle.net",
  confluence: "Confluence",
  sharepoint: "Microsoft SharePoint",
  boldsign: "BoldSign",
  neon: "Neon",
  bolna: "Bolna",
  rocket_reach: "RocketReach",
  zoom: "Zoom",
  pandadoc: "PandaDoc",
  dropbox: "Dropbox",
  wave_accounting: "Wave Accounting",
  rippling: "Rippling",
  icims_talent_cloud: "iCIMS Talent Cloud",
  salesforce: "Salesforce",
  foursquare_v2: "Foursquare Search",
  ashby: "Ashby",
  mem0: "Mem0",
  dialpad: "Dialpad",
  slack: "Slack",
  ramp: "Ramp",
  googlemeet: "Google Meet",
  posthog: "PostHog",
  googlecalendar: "Google Calendar",
  serpapi: "SERP API",
  dropbox_sign: "Dropbox Sign",
  zoho_mail: "Zoho Mail",
  brex_staging: "Brex Staging",
  zoho_bigin: "Zoho Bigin",
  trello: "Trello",
  googledrive: "Google Drive",
  tavily: "Tavily",
  bitbucket: "Bitbucket",
  rocketlane: "Rocketlane",
  composio: "Composio",
  calendly: "Calendly",
  fomo: "FOMO",
  precoro: "Precoro",
  apaleo: "Apaleo",
  lastpass: "lastpass",
  launch_darkly: "LaunchDarkly",
  servicenow: "Servicenow",
  sentry: "Sentry",
  twitch: "Twitch",
  auth0: "Auth0",
  appsflyer: "AppsFlyer",
  netsuite: "NetSuite",
  onepage: "Onepage",
  front: "Front",
  acculynx: "AccuLynx",
  zoominfo: "ZoomInfo",
  meta_ads: "Meta Ads",
  gong: "Gong",
  listennotes: "Listen Notes",
  brevo: "Brevo",
  aero_workflow: "Aero Workflow",
  asana: "Asana",
  blackboard: "Blackboard",
  gorgias: "Gorgias",
  coda: "Coda",
  apify: "Apify",
  gmail: "Gmail",
  googledocs: "Google Docs",
  active_campaign: "ActiveCampaign",
  taskade: "Taskade",
  whatsapp: "WhatsApp",
  mocean: "Mocean API",
  epic_games: "Epic Games",
  resend: "Resend",
  sage: "Sage",
  linkedin: "Linkedin",
  twilio: "Twilio",
  stripe: "Stripe",
  ynab: "YNAB",
  alchemy: "Alchemy",
  binance: "Binance",
  wakatime: "Wakatime",
  outlook: "Outlook",
  echtpost: "EchtPost",
  nasa: "NASA",
  coinmarketcal: "CoinMarketCal",
};
