/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as ComposioApi from "../../../../index";
/**
 * @example
 *     {
 *         category: "crm",
 *         additionalFields: "auth_schemes"
 *     }
 */
export interface AppsGetAppsRequest {
    category?: string;
    additionalFields?: string;
    includeLocal?: ComposioApi.AppsGetAppsRequestIncludeLocal;
    sortBy?: ComposioApi.AppsGetAppsRequestSortBy;
}
