name: 'Setup Node.js with PNPM'
description: 'Sets up Node.js and PNPM with caching, using .nvmrc for version'

inputs:
  node-version:
    description: 'Node.js version to use. Defaults to .nvmrc file'
    required: false
    default: ''
  node-version-file:
    description: 'Path to .nvmrc or similar file'
    required: false
    default: '.nvmrc'
  enable-caching:
    description: 'Enable PNPM caching'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Setup PNPM
      uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0

    - name: Setup Node.js
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version: ${{ inputs.node-version }}
        node-version-file: ${{ inputs.node-version == '' && inputs.node-version-file || '' }}
        cache: ${{ inputs.enable-caching == 'true' && 'pnpm' || '' }}
