from enum import Enum

class Tag(Enum):
    IMPORTANT = ("default", "important")
    ALL = ("default", "all")
    ASANA_CUSTOM_FIELDS = ("asana", "Custom fields")
    ASANA_STORIES = ("asana", "Stories")
    ASANA_MEMBERSHIPS = ("asana", "Memberships")
    ASANA_PORTFOLIO_MEMBERSHIPS = ("asana", "Portfolio memberships")
    ASANA_TEAM_MEMBERSHIPS = ("asana", "Team memberships")
    ASANA_SECTIONS = ("asana", "Sections")
    ASANA_EVENTS = ("asana", "Events")
    ASANA_TIME_TRACKING_ENTRIES = ("asana", "Time tracking entries")
    ASANA_WEBHOOKS = ("asana", "Webhooks")
    ASANA_TASKS = ("asana", "Tasks")
    ASANA_RULES = ("asana", "Rules")
    ASANA_TYPEAHEAD = ("asana", "Typeahead")
    ASANA_PROJECT_STATUSES = ("asana", "Project statuses")
    ASANA_ALLOCATIONS = ("asana", "Allocations")
    ASANA_ORGANIZATION_EXPORTS = ("asana", "Organization exports")
    ASANA_PROJECTS = ("asana", "Projects")
    ASANA_STATUS_UPDATES = ("asana", "Status updates")
    ASANA_WORKSPACE_MEMBERSHIPS = ("asana", "Workspace memberships")
    ASANA_WORKSPACES = ("asana", "Workspaces")
    ASANA_PORTFOLIOS = ("asana", "Portfolios")
    ASANA_GOALS = ("asana", "Goals")
    ASANA_BATCH_API = ("asana", "Batch API")
    ASANA_USER_TASK_LISTS = ("asana", "User task lists")
    ASANA_ATTACHMENTS = ("asana", "Attachments")
    ASANA_JOBS = ("asana", "Jobs")
    ASANA_AUDIT_LOG_API = ("asana", "Audit log API")
    ASANA_TAGS = ("asana", "Tags")
    ASANA_TEAMS = ("asana", "Teams")
    ASANA_CUSTOM_FIELD_SETTINGS = ("asana", "Custom field settings")
    ASANA_GOAL_RELATIONSHIPS = ("asana", "Goal relationships")
    ASANA_PROJECT_BRIEFS = ("asana", "Project briefs")
    ASANA_PROJECT_MEMBERSHIPS = ("asana", "Project memberships")
    ASANA_USERS = ("asana", "Users")
    ASANA_PROJECT_TEMPLATES = ("asana", "Project templates")
    ASANA_TASK_TEMPLATES = ("asana", "Task templates")
    ASANA_TIME_PERIODS = ("asana", "Time periods")
    ELEVENLABS_SAMPLES = ("elevenlabs", "samples")
    ELEVENLABS_PRONUNCIATION_DICTIONARY = ("elevenlabs", "Pronunciation Dictionary")
    ELEVENLABS_AUDIO_NATIVE = ("elevenlabs", "audio-native")
    ELEVENLABS_USER = ("elevenlabs", "user")
    ELEVENLABS_VOICE_GENERATION = ("elevenlabs", "voice-generation")
    ELEVENLABS_WORKSPACE = ("elevenlabs", "workspace")
    ELEVENLABS_VOICES = ("elevenlabs", "voices")
    ELEVENLABS_TEXT_TO_SPEECH = ("elevenlabs", "text-to-speech")
    ELEVENLABS_SPEECH_HISTORY = ("elevenlabs", "speech-history")
    ELEVENLABS_PROJECTS = ("elevenlabs", "projects")
    ELEVENLABS_DUBBING = ("elevenlabs", "dubbing")
    ELEVENLABS_SPEECH_TO_SPEECH = ("elevenlabs", "speech-to-speech")
    ELEVENLABS_MODELS = ("elevenlabs", "models")
    LISTENNOTES_INSIGHTS_API = ("listennotes", "Insights API")
    LISTENNOTES_PLAYLIST_API = ("listennotes", "Playlist API")
    LISTENNOTES_PODCASTER_API = ("listennotes", "Podcaster API")
    LISTENNOTES_SEARCH_API = ("listennotes", "Search API")
    LISTENNOTES_DIRECTORY_API = ("listennotes", "Directory API")
    ZOOM_TRACKING_FIELD = ("zoom", "Tracking Field")
    ZOOM_CLOUD_RECORDING = ("zoom", "Cloud Recording")
    ZOOM_DEVICES = ("zoom", "Devices")
    ZOOM_H323_DEVICES = ("zoom", "H323 Devices")
    ZOOM_PAC = ("zoom", "PAC")
    ZOOM_SIP_PHONE = ("zoom", "SIP Phone")
    ZOOM_WEBINARS = ("zoom", "Webinars")
    ZOOM_MEETINGS = ("zoom", "Meetings")
    ZOOM_REPORTS = ("zoom", "Reports")
    ZOOM_TSP = ("zoom", "TSP")
    ZOOM_ARCHIVING = ("zoom", "Archiving")

class App(Enum):
    ABLY = "ably"
    ACCELO = "accelo"
    ACTIVE_COMPAIGN = "active-compaign"
    ADOBE = "adobe"
    AERO_WORKFLOW = "aero-workflow"
    ALCHEMY = "alchemy"
    ALTOVIZ = "altoviz"
    AMAZON = "amazon"
    AMCARDS = "amcards"
    AMPLITUDE = "amplitude"
    APIFY = "apify"
    APPDRAG = "appdrag"
    ASANA = "asana"
    ASHBY = "ashby"
    ATLASSIAN = "atlassian"
    ATTIO = "attio"
    AUTH0 = "auth0"
    AXONAUT = "axonaut"
    BAMBOOHR = "bamboohr"
    BANNERBEAR = "bannerbear"
    BASEROW = "baserow"
    BATTLENET = "battlenet"
    BEEMINDER = "beeminder"
    BITBUCKET = "bitbucket"
    BITWARDEN = "bitwarden"
    BLACKBAUD = "blackbaud"
    BOLDSIGN = "boldsign"
    BOTBABA = "botbaba"
    BOX = "box"
    BRAINTREE = "braintree"
    BRANDFETCH = "brandfetch"
    BREVO = "brevo"
    BREX = "brex"
    BREX_STAGING = "brex-staging"
    BROWSEAI = "browseai"
    BROWSERHUB = "browserhub"
    BUBBLE = "bubble"
    CAL = "cal"
    CALENDLY = "calendly"
    CHATWORK = "chatwork"
    CHMEETINGS = "chmeetings"
    CLICKUP = "clickup"
    CLOSE = "close"
    CLOUDFLARE = "cloudflare"
    CODEINTERPRETER = "codeinterpreter"
    COINMARKETCAL = "coinmarketcal"
    CONTENTFUL = "contentful"
    CUSTOMER_IO = "customer_io"
    DAILYBOT = "dailybot"
    DATADOG = "datadog"
    DATAGMA = "datagma"
    DATAROBOT = "datarobot"
    DEEL = "deel"
    DEMIO = "demio"
    DIGICERT = "digicert"
    DISCORD = "discord"
    DOCMOSIS = "docmosis"
    DROPBOX = "dropbox"
    DROPBOX_SIGN = "dropbox-sign"
    ECHTPOST = "echtpost"
    ELEVENLABS = "elevenlabs"
    EPIC_GAMES = "epic-games"
    EVENTBRITE = "eventbrite"
    EXA = "exa"
    EXIST = "exist"
    FACEBOOK = "facebook"
    FACTORIAL = "factorial"
    FIGMA = "figma"
    FILEMANAGER = "filemanager"
    FINAGE = "finage"
    FITBIT = "fitbit"
    FLUTTERWAVE = "flutterwave"
    FOMO = "fomo"
    FORMCARRY = "formcarry"
    FORMSITE = "formsite"
    FRESHBOOKS = "freshbooks"
    FRESHDESK = "freshdesk"
    FRONT = "front"
    GCALENDAR = "gcalendar"
    GITHUB = "github"
    GITLAB = "gitlab"
    GMAIL = "gmail"
    GOOGLE_DOCS = "google-docs"
    GOOGLE_DRIVE = "google-drive"
    GOOGLE_SHEETS = "google-sheets"
    GORGIAS = "gorgias"
    GUMROAD = "gumroad"
    GURU = "guru"
    HACKERRANK_WORK = "hackerrank-work"
    HARVEST = "harvest"
    HELCIM = "helcim"
    HEROKU = "heroku"
    HIGHLEVEL = "highlevel"
    HUBSPOT = "hubspot"
    HUMANLOOP = "humanloop"
    INTERCOM = "intercom"
    INTERZOID = "interzoid"
    JIRA = "jira"
    KEAP = "keap"
    KLAVIYO = "klaviyo"
    KLIPFOLIO = "klipfolio"
    LASTPASS = "lastpass"
    LAUNCH_DARKLY = "launch-darkly"
    LEVER = "lever"
    LEVER_SANDBOX = "lever-sandbox"
    LEXOFFICE = "lexoffice"
    LINEAR = "linear"
    LINEARSANDBOX = "linearsandbox"
    LINKHUT = "linkhut"
    LISTENNOTES = "listennotes"
    MAILCHIMP = "mailchimp"
    MAINTAINX = "maintainx"
    MBOUM = "mboum"
    METATEXTAI = "metatextai"
    MICROSOFT_TEAMS = "microsoft-teams"
    MICROSOFT_TENANT = "microsoft-tenant"
    MIRO = "miro"
    MIXPANEL = "mixpanel"
    MOCEAN_API = "mocean-api"
    MONDAY = "monday"
    MORE_TREES = "more-trees"
    MOXIE = "moxie"
    MURAL = "mural"
    NCSCALE = "ncscale"
    NETSUITE = "netsuite"
    NGROK = "ngrok"
    NOTION = "notion"
    OKTA = "okta"
    ONCEHUB = "oncehub"
    ONE_DRIVE = "one-drive"
    PAGERDUTY = "pagerduty"
    PANDADOC = "pandadoc"
    PIGGY = "piggy"
    PIPEDRIVE = "pipedrive"
    PLACEKEY = "placekey"
    PRINTNODE = "printnode"
    PROCESS_STREET = "process-street"
    PRODUCTBOARD = "productboard"
    QUALAROO = "qualaroo"
    RAFFLYS = "rafflys"
    RAVENSEOTOOLS = "ravenseotools"
    REDDIT = "reddit"
    RING_CENTRAL = "ring-central"
    ROCKET_REACH = "rocket-reach"
    SAGE = "sage"
    SALESFORCE = "salesforce"
    SCREENSHOTONE = "screenshotone"
    SERPAPI = "serpapi"
    SERVICEM8 = "servicem8"
    SHOPIFY = "shopify"
    SHORTCUT = "shortcut"
    SIMPLESAT = "simplesat"
    SLACK = "slack"
    SLACKBOT = "slackbot"
    SMARTRECRUITERS = "smartrecruiters"
    SMUGMUG = "smugmug"
    SNOWFLAKE = "snowflake"
    SPLITWISE = "splitwise"
    SPOTIFY = "spotify"
    SQUARE = "square"
    STACK_EXCHANGE = "stack-exchange"
    STRAVA = "strava"
    SURVEY_MONKEY = "survey-monkey"
    TAPFORM = "tapform"
    TASKADE = "taskade"
    TERMINUS = "terminus"
    TEXTRAZOR = "textrazor"
    TIMECAMP = "timecamp"
    TIMEKIT = "timekit"
    TIMELY = "timely"
    TINYPNG = "tinypng"
    TINYURL = "tinyurl"
    TISANE = "tisane"
    TODOIST = "todoist"
    TONEDEN = "toneden"
    TRELLO = "trello"
    TWITCH = "twitch"
    TWITTER = "twitter"
    TYPEFORM = "typeform"
    VENLY = "venly"
    VERO = "vero"
    WABOXAPP = "waboxapp"
    WAKATIME = "wakatime"
    WAVE_ACCOUNTING = "wave-accounting"
    WEBFLOW = "webflow"
    WORKABLE = "workable"
    WORKIOM = "workiom"
    WORKSPACE = "workspace"
    XERO = "xero"
    YANDEX = "yandex"
    YNAB = "ynab"
    YOUTUBE = "youtube"
    ZENDESK = "zendesk"
    ZENSERP = "zenserp"
    ZOHO = "zoho"
    ZOHO_BIGIN = "zoho-bigin"
    ZOHO_BOOKS = "zoho-books"
    ZOHO_DESK = "zoho-desk"
    ZOHO_INVENTORY = "zoho-inventory"
    ZOHO_INVOICE = "zoho-invoice"
    ZOHO_MAIL = "zoho-mail"
    ZOOM = "zoom"

class Action(Enum):
    def __init__(self, service, action, no_auth):
        self.service = service
        self.action = action
        self.no_auth = no_auth

    APIFY_LIST_APIFY_ACTORS = ("apify", "apify_list_apify_actors", False)
    APIFY_CREATE_APIFY_ACTOR = ("apify", "apify_create_apify_actor", False)
    APIFY_GET_ACTOR_ID = ("apify", "apify_get_actor_id", False)
    APIFY_SEARCH_STORE = ("apify", "apify_search_store", False)
    APIFY_GET_LAST_RUN_DATA = ("apify", "apify_get_last_run_data", False)
    APIFY_LIST_APIFY_TASKS = ("apify", "apify_list_apify_tasks", False)
    ASANA_ALLOCATIONS_GET_RECORD_BY_ID = ("asana", "asana_allocations_get_record_by_id", False)
    ASANA_ALLOCATIONS_UPDATE_RECORD_BY_ID = ("asana", "asana_allocations_update_record_by_id", False)
    ASANA_ALLOCATIONS_DELETE_ALLOCATION_BY_ID = ("asana", "asana_allocations_delete_allocation_by_id", False)
    ASANA_ALLOCATIONS_GET_MULTIPLE = ("asana", "asana_allocations_get_multiple", False)
    ASANA_ALLOCATIONS_CREATE_RECORD = ("asana", "asana_allocations_create_record", False)
    ASANA_ATTACHMENTS_GET_ATTACHMENT_RECORD = ("asana", "asana_attachments_get_attachment_record", False)
    ASANA_ATTACHMENTS_DELETE_SPECIFIC = ("asana", "asana_attachments_delete_specific", False)
    ASANA_ATTACHMENTS_GET_ALL_FOR_OBJECT = ("asana", "asana_attachments_get_all_for_object", False)
    ASANA_ATTACHMENTS_UPLOAD_ATTACHMENT = ("asana", "asana_attachments_upload_attachment", False)
    ASANA_AUDIT_LOG_API_GET_AUDIT_LOG_EVENTS = ("asana", "asana_audit_log_api_get_audit_log_events", False)
    ASANA_BATCH_API_SUBMIT_PARALLEL_REQUESTS = ("asana", "asana_batch_api_submit_parallel_requests", False)
    ASANA_CUSTOM_FIELD_SETTINGS_GET_PROJECT_CUSTOM_FIELD_SETTINGS = ("asana", "asana_custom_field_settings_get_project_custom_field_settings", False)
    ASANA_CUSTOM_FIELD_SETTINGS_GET_PORTFOLIO_CUSTOM_FIELD_SETTINGS = ("asana", "asana_custom_field_settings_get_portfolio_custom_field_settings", False)
    ASANA_CUSTOM_FIELDS_CREATE_NEW_FIELD_RECORD = ("asana", "asana_custom_fields_create_new_field_record", False)
    ASANA_CUSTOM_FIELDS_GET_METADATA = ("asana", "asana_custom_fields_get_metadata", False)
    ASANA_CUSTOM_FIELDS_UPDATE_FIELD_RECORD = ("asana", "asana_custom_fields_update_field_record", False)
    ASANA_CUSTOM_FIELDS_DELETE_FIELD_RECORD = ("asana", "asana_custom_fields_delete_field_record", False)
    ASANA_CUSTOM_FIELDS_LIST_WORK_SPACE_CUSTOM_FIELDS = ("asana", "asana_custom_fields_list_work_space_custom_fields", False)
    ASANA_CUSTOM_FIELDS_ADDE_NUM_OPTION = ("asana", "asana_custom_fields_adde_num_option", False)
    ASANA_CUSTOM_FIELDS_REORDERE_NUM_OPTION = ("asana", "asana_custom_fields_reordere_num_option", False)
    ASANA_CUSTOM_FIELDS_UPDATEE_NUM_OPTION = ("asana", "asana_custom_fields_updatee_num_option", False)
    ASANA_EVENTS_GET_RESOURCE_EVENTS = ("asana", "asana_events_get_resource_events", False)
    ASANA_GOAL_RELATIONSHIPS_GET_RECORD_BY_ID = ("asana", "asana_goal_relationships_get_record_by_id", False)
    ASANA_GOAL_RELATIONSHIPS_UPDATE_GOAL_RELATIONSHIP_RECORD = ("asana", "asana_goal_relationships_update_goal_relationship_record", False)
    ASANA_GOAL_RELATIONSHIPS_GET_COMPACT_RECORDS = ("asana", "asana_goal_relationships_get_compact_records", False)
    ASANA_GOAL_RELATIONSHIPS_CREATE_SUPPORTING_RELATIONSHIP = ("asana", "asana_goal_relationships_create_supporting_relationship", False)
    ASANA_GOAL_RELATIONSHIPS_REMOVE_SUPPORTING_RELATIONSHIP = ("asana", "asana_goal_relationships_remove_supporting_relationship", False)
    ASANA_GOALS_GET_GOAL_RECORD = ("asana", "asana_goals_get_goal_record", False)
    ASANA_GOALS_UPDATE_GOAL_RECORD = ("asana", "asana_goals_update_goal_record", False)
    ASANA_GOALS_DELETE_RECORD = ("asana", "asana_goals_delete_record", False)
    ASANA_GOALS_GET_COMPACT_RECORDS = ("asana", "asana_goals_get_compact_records", False)
    ASANA_GOALS_CREATE_NEW_GOAL_RECORD = ("asana", "asana_goals_create_new_goal_record", False)
    ASANA_GOALS_CREATE_METRIC = ("asana", "asana_goals_create_metric", False)
    ASANA_GOALS_UPDATE_METRIC_CURRENT_VALUE = ("asana", "asana_goals_update_metric_current_value", False)
    ASANA_GOALS_ADD_COLLABORATORS_TO_GOAL = ("asana", "asana_goals_add_collaborators_to_goal", False)
    ASANA_GOALS_REMOVE_FOLLOWERS_FROM_GOAL = ("asana", "asana_goals_remove_followers_from_goal", False)
    ASANA_GOALS_GET_PARENT_GOALS = ("asana", "asana_goals_get_parent_goals", False)
    ASANA_JOBS_GET_BY_ID = ("asana", "asana_jobs_get_by_id", False)
    ASANA_MEMBERSHIPS_GET_MULTIPLE = ("asana", "asana_memberships_get_multiple", False)
    ASANA_MEMBERSHIPS_CREATE_NEW_RECORD = ("asana", "asana_memberships_create_new_record", False)
    ASANA_MEMBERSHIPS_GET_MEMBERSHIP_RECORD = ("asana", "asana_memberships_get_membership_record", False)
    ASANA_MEMBERSHIPS_UPDATE_MEMBERSHIP_RECORD = ("asana", "asana_memberships_update_membership_record", False)
    ASANA_MEMBERSHIPS_DELETE_RECORD = ("asana", "asana_memberships_delete_record", False)
    ASANA_ORGANIZATION_EXPORTS_CREATE_EXPORT_REQUEST = ("asana", "asana_organization_exports_create_export_request", False)
    ASANA_ORGANIZATION_EXPORTS_GET_EXPORT_DETAILS = ("asana", "asana_organization_exports_get_export_details", False)
    ASANA_PORTFOLIO_MEMBERSHIPS_LIST_MULTIPLE_MEMBERSHIPS = ("asana", "asana_portfolio_memberships_list_multiple_memberships", False)
    ASANA_PORTFOLIO_MEMBERSHIPS_GET_COMPLETE_RECORD = ("asana", "asana_portfolio_memberships_get_complete_record", False)
    ASANA_PORTFOLIO_MEMBERSHIPS_GET_COMPACT = ("asana", "asana_portfolio_memberships_get_compact", False)
    ASANA_PORTFOLIOS_LIST_MULTIPLE_PORTFOLIOS = ("asana", "asana_portfolios_list_multiple_portfolios", False)
    ASANA_PORTFOLIOS_CREATE_NEW_PORTFOLIO_RECORD = ("asana", "asana_portfolios_create_new_portfolio_record", False)
    ASANA_PORTFOLIOS_GET_RECORD = ("asana", "asana_portfolios_get_record", False)
    ASANA_PORTFOLIOS_UPDATE_PORTFOLIO_RECORD = ("asana", "asana_portfolios_update_portfolio_record", False)
    ASANA_PORTFOLIOS_DELETE_RECORD = ("asana", "asana_portfolios_delete_record", False)
    ASANA_PORTFOLIOS_GET_ITEMS = ("asana", "asana_portfolios_get_items", False)
    ASANA_PORTFOLIOS_ADD_PORTFOLIO_ITEM = ("asana", "asana_portfolios_add_portfolio_item", False)
    ASANA_PORTFOLIOS_REMOVE_ITEM_FROM_PORTFOLIO = ("asana", "asana_portfolios_remove_item_from_portfolio", False)
    ASANA_PORTFOLIOS_ADD_CUSTOM_FIELD_SETTING = ("asana", "asana_portfolios_add_custom_field_setting", False)
    ASANA_PORTFOLIOS_REMOVE_CUSTOM_FIELD_SETTING = ("asana", "asana_portfolios_remove_custom_field_setting", False)
    ASANA_PORTFOLIOS_ADD_MEMBERS_TO_PORTFOLIO = ("asana", "asana_portfolios_add_members_to_portfolio", False)
    ASANA_PORTFOLIOS_REMOVE_MEMBERS_FROM_PORTFOLIO = ("asana", "asana_portfolios_remove_members_from_portfolio", False)
    ASANA_PROJECT_BRIEFS_GET_FULL_RECORD = ("asana", "asana_project_briefs_get_full_record", False)
    ASANA_PROJECT_BRIEFS_UPDATE_BRIEF_RECORD = ("asana", "asana_project_briefs_update_brief_record", False)
    ASANA_PROJECT_BRIEFS_REMOVE_BRIEF = ("asana", "asana_project_briefs_remove_brief", False)
    ASANA_PROJECT_BRIEFS_CREATE_NEW_RECORD = ("asana", "asana_project_briefs_create_new_record", False)
    ASANA_PROJECT_MEMBERSHIPS_GET_RECORD = ("asana", "asana_project_memberships_get_record", False)
    ASANA_PROJECT_MEMBERSHIPS_GET_COMPACT_RECORDS = ("asana", "asana_project_memberships_get_compact_records", False)
    ASANA_PROJECT_STATUSES_GET_STATUS_UPDATE_RECORD = ("asana", "asana_project_statuses_get_status_update_record", False)
    ASANA_PROJECT_STATUSES_DELETE_SPECIFIC_STATUS_UPDATE = ("asana", "asana_project_statuses_delete_specific_status_update", False)
    ASANA_PROJECT_STATUSES_GET_PROJECT_UPDATES = ("asana", "asana_project_statuses_get_project_updates", False)
    ASANA_PROJECT_STATUSES_CREATE_NEW_STATUS_UPDATE_RECORD = ("asana", "asana_project_statuses_create_new_status_update_record", False)
    ASANA_PROJECT_TEMPLATES_GET_RECORD = ("asana", "asana_project_templates_get_record", False)
    ASANA_PROJECT_TEMPLATES_DELETE_TEMPLATE_RECORD = ("asana", "asana_project_templates_delete_template_record", False)
    ASANA_PROJECT_TEMPLATES_LIST_MULTIPLE = ("asana", "asana_project_templates_list_multiple", False)
    ASANA_PROJECT_TEMPLATES_GET_ALL_TEMPLATE_RECORDS = ("asana", "asana_project_templates_get_all_template_records", False)
    ASANA_PROJECT_TEMPLATES_INSTANTIATE_PROJECT_JOB = ("asana", "asana_project_templates_instantiate_project_job", False)
    ASANA_PROJECTS_LIST_MULTIPLE = ("asana", "asana_projects_list_multiple", False)
    ASANA_PROJECTS_CREATE_NEW_PROJECT_RECORD = ("asana", "asana_projects_create_new_project_record", False)
    ASANA_PROJECTS_GET_PROJECT_RECORD = ("asana", "asana_projects_get_project_record", False)
    ASANA_PROJECTS_UPDATE_PROJECT_RECORD = ("asana", "asana_projects_update_project_record", False)
    ASANA_PROJECTS_DELETE_PROJECT_BY_ID = ("asana", "asana_projects_delete_project_by_id", False)
    ASANA_PROJECTS_DUPLICATE_PROJECT_JOB = ("asana", "asana_projects_duplicate_project_job", False)
    ASANA_PROJECTS_TASK_PROJECTS_LIST = ("asana", "asana_projects_task_projects_list", False)
    ASANA_PROJECTS_GET_TEAM_PROJECTS = ("asana", "asana_projects_get_team_projects", False)
    ASANA_PROJECTS_CREATE_PROJECT_FOR_TEAM = ("asana", "asana_projects_create_project_for_team", False)
    ASANA_PROJECTS_GET_ALL_IN_WORK_SPACE = ("asana", "asana_projects_get_all_in_work_space", False)
    ASANA_PROJECTS_CREATE_IN_WORK_SPACE = ("asana", "asana_projects_create_in_work_space", False)
    ASANA_PROJECTS_ADD_CUSTOM_FIELD_SETTING = ("asana", "asana_projects_add_custom_field_setting", False)
    ASANA_PROJECTS_REMOVE_CUSTOM_FIELD = ("asana", "asana_projects_remove_custom_field", False)
    ASANA_PROJECTS_GET_TASK_COUNTS = ("asana", "asana_projects_get_task_counts", False)
    ASANA_PROJECTS_ADD_MEMBERS_TO_PROJECT = ("asana", "asana_projects_add_members_to_project", False)
    ASANA_PROJECTS_REMOVE_MEMBERS_FROM_PROJECT = ("asana", "asana_projects_remove_members_from_project", False)
    ASANA_PROJECTS_ADD_FOLLOWERS_TO_PROJECT = ("asana", "asana_projects_add_followers_to_project", False)
    ASANA_PROJECTS_REMOVE_PROJECT_FOLLOWERS = ("asana", "asana_projects_remove_project_followers", False)
    ASANA_PROJECTS_CREATE_PROJECT_TEMPLATE_JOB = ("asana", "asana_projects_create_project_template_job", False)
    ASANA_RULES_TRIGGER_RULE_REQUEST = ("asana", "asana_rules_trigger_rule_request", False)
    ASANA_SECTIONS_GET_RECORD = ("asana", "asana_sections_get_record", False)
    ASANA_SECTIONS_UPDATE_SECTION_RECORD = ("asana", "asana_sections_update_section_record", False)
    ASANA_SECTIONS_DELETE_SECTION = ("asana", "asana_sections_delete_section", False)
    ASANA_SECTIONS_LIST_PROJECT_SECTIONS = ("asana", "asana_sections_list_project_sections", False)
    ASANA_SECTIONS_CREATE_NEW_SECTION = ("asana", "asana_sections_create_new_section", False)
    ASANA_SECTIONS_ADD_TASK_TO_SECTION = ("asana", "asana_sections_add_task_to_section", False)
    ASANA_SECTIONS_MOVE_OR_INSERT = ("asana", "asana_sections_move_or_insert", False)
    ASANA_STATUS_UPDATES_GET_RECORD_BY_ID = ("asana", "asana_status_updates_get_record_by_id", False)
    ASANA_STATUS_UPDATES_DELETE_SPECIFIC_STATUS_UPDATE = ("asana", "asana_status_updates_delete_specific_status_update", False)
    ASANA_STATUS_UPDATES_GET_COMPACT_RECORDS = ("asana", "asana_status_updates_get_compact_records", False)
    ASANA_STATUS_UPDATES_CREATE_NEW_STATUS_UPDATE_RECORD = ("asana", "asana_status_updates_create_new_status_update_record", False)
    ASANA_STORIES_GET_FULL_RECORD = ("asana", "asana_stories_get_full_record", False)
    ASANA_STORIES_UPDATE_FULL_RECORD = ("asana", "asana_stories_update_full_record", False)
    ASANA_STORIES_DELETE_STORY_RECORD = ("asana", "asana_stories_delete_story_record", False)
    ASANA_STORIES_GET_TASK_STORIES = ("asana", "asana_stories_get_task_stories", False)
    ASANA_STORIES_CREATE_COMMENT = ("asana", "asana_stories_create_comment", False)
    ASANA_TAGS_LIST_FILTERED_TAGS = ("asana", "asana_tags_list_filtered_tags", False)
    ASANA_TAGS_CREATE_NEW_TAG_RECORD = ("asana", "asana_tags_create_new_tag_record", False)
    ASANA_TAGS_GET_RECORD = ("asana", "asana_tags_get_record", False)
    ASANA_TAGS_UPDATE_TAG_RECORD = ("asana", "asana_tags_update_tag_record", False)
    ASANA_TAGS_REMOVE_TAG = ("asana", "asana_tags_remove_tag", False)
    ASANA_TAGS_GET_TASK_TAGS = ("asana", "asana_tags_get_task_tags", False)
    ASANA_TAGS_GET_FILTERED_TAGS = ("asana", "asana_tags_get_filtered_tags", False)
    ASANA_TAGS_CREATE_TAG_IN_WORK_SPACE = ("asana", "asana_tags_create_tag_in_work_space", False)
    ASANA_TASK_TEMPLATES_LIST_MULTIPLE = ("asana", "asana_task_templates_list_multiple", False)
    ASANA_TASK_TEMPLATES_GET_SINGLE_TEMPLATE = ("asana", "asana_task_templates_get_single_template", False)
    ASANA_TASK_TEMPLATES_DELETE_TASK_TEMPLATE = ("asana", "asana_task_templates_delete_task_template", False)
    ASANA_TASK_TEMPLATES_INSTANTIATE_TASK_JOB = ("asana", "asana_task_templates_instantiate_task_job", False)
    ASANA_TASKS_GET_MULTIPLE = ("asana", "asana_tasks_get_multiple", False)
    ASANA_TASKS_CREATE_NEW_TASK = ("asana", "asana_tasks_create_new_task", False)
    ASANA_TASKS_GET_TASK_RECORD = ("asana", "asana_tasks_get_task_record", False)
    ASANA_TASKS_UPDATE_TASK_RECORD = ("asana", "asana_tasks_update_task_record", False)
    ASANA_TASKS_DELETE_TASK = ("asana", "asana_tasks_delete_task", False)
    ASANA_TASKS_DUPLICATE_TASK_JOB = ("asana", "asana_tasks_duplicate_task_job", False)
    ASANA_TASKS_GET_TASKS_BY_PROJECT = ("asana", "asana_tasks_get_tasks_by_project", False)
    ASANA_TASKS_GET_SECTION_TASKS = ("asana", "asana_tasks_get_section_tasks", False)
    ASANA_TASKS_GET_MULTIPLE_WITH_TAG = ("asana", "asana_tasks_get_multiple_with_tag", False)
    ASANA_TASKS_GET_USER_TASK_LIST_TASKS = ("asana", "asana_tasks_get_user_task_list_tasks", False)
    ASANA_TASKS_GET_SUB_TASK_LIST = ("asana", "asana_tasks_get_sub_task_list", False)
    ASANA_TASKS_CREATE_SUB_TASK_RECORD = ("asana", "asana_tasks_create_sub_task_record", False)
    ASANA_TASKS_SET_PARENT_TASK = ("asana", "asana_tasks_set_parent_task", False)
    ASANA_TASKS_GET_ALL_DEPENDENCIES = ("asana", "asana_tasks_get_all_dependencies", False)
    ASANA_TASKS_SET_DEPENDENCIES_FOR_TASK = ("asana", "asana_tasks_set_dependencies_for_task", False)
    ASANA_TASK_SUN_LINK_DEPENDENCIES_FROM_TASK = ("asana", "asana_task_sun_link_dependencies_from_task", False)
    ASANA_TASKS_GET_DEPENDENTS = ("asana", "asana_tasks_get_dependents", False)
    ASANA_TASKS_SET_TASK_DEPENDENTS = ("asana", "asana_tasks_set_task_dependents", False)
    ASANA_TASK_SUN_LINK_DEPENDENTS = ("asana", "asana_task_sun_link_dependents", False)
    ASANA_TASKS_ADD_PROJECT_TO_TASK = ("asana", "asana_tasks_add_project_to_task", False)
    ASANA_TASKS_REMOVE_PROJECT_FROM_TASK = ("asana", "asana_tasks_remove_project_from_task", False)
    ASANA_TASKS_ADD_TAG_TO_TASK = ("asana", "asana_tasks_add_tag_to_task", False)
    ASANA_TASKS_REMOVE_TAG_FROM_TASK = ("asana", "asana_tasks_remove_tag_from_task", False)
    ASANA_TASKS_ADD_FOLLOWERS_TO_TASK = ("asana", "asana_tasks_add_followers_to_task", False)
    ASANA_TASKS_REMOVE_FOLLOWERS_FROM_TASK = ("asana", "asana_tasks_remove_followers_from_task", False)
    ASANA_TASKS_GET_BY_CUSTOM_ID = ("asana", "asana_tasks_get_by_custom_id", False)
    ASANA_TASKS_SEARCH_IN_WORK_SPACE = ("asana", "asana_tasks_search_in_work_space", False)
    ASANA_TEAM_MEMBERSHIPS_GET_RECORD_BY_ID = ("asana", "asana_team_memberships_get_record_by_id", False)
    ASANA_TEAM_MEMBERSHIPS_GET_COMPACT_RECORDS = ("asana", "asana_team_memberships_get_compact_records", False)
    ASANA_TEAM_MEMBERSHIPS_GET_COMPACT = ("asana", "asana_team_memberships_get_compact", False)
    ASANA_TEAM_MEMBERSHIPS_GET_USER_COMPACT = ("asana", "asana_team_memberships_get_user_compact", False)
    ASANA_TEAMS_CREATE_TEAM_RECORD = ("asana", "asana_teams_create_team_record", False)
    ASANA_TEAMS_GET_TEAM_RECORD = ("asana", "asana_teams_get_team_record", False)
    ASANA_TEAMS_UPDATE_TEAM_RECORD = ("asana", "asana_teams_update_team_record", False)
    ASANA_TEAMS_LIST_WORK_SPACE_TEAMS = ("asana", "asana_teams_list_work_space_teams", False)
    ASANA_TEAMS_GET_USER_TEAMS = ("asana", "asana_teams_get_user_teams", False)
    ASANA_TEAMS_ADD_USER_TO_TEAM = ("asana", "asana_teams_add_user_to_team", False)
    ASANA_TEAMS_REMOVE_USER_FROM_TEAM = ("asana", "asana_teams_remove_user_from_team", False)
    ASANA_TIME_PERIODS_GET_FULL_RECORD = ("asana", "asana_time_periods_get_full_record", False)
    ASANA_TIME_PERIODS_GET_COMPACT_TIME_PERIODS = ("asana", "asana_time_periods_get_compact_time_periods", False)
    ASANA_TIME_TRACKING_ENTRIES_GET_FOR_TASK = ("asana", "asana_time_tracking_entries_get_for_task", False)
    ASANA_TIME_TRACKING_ENTRIES_CREATE_NEW_TIME_ENTRY_RECORD = ("asana", "asana_time_tracking_entries_create_new_time_entry_record", False)
    ASANA_TIME_TRACKING_ENTRIES_GET_RECORD = ("asana", "asana_time_tracking_entries_get_record", False)
    ASANA_TIME_TRACKING_ENTRIES_UPDATE_TIME_TRACKING_ENTRY = ("asana", "asana_time_tracking_entries_update_time_tracking_entry", False)
    ASANA_TIME_TRACKING_ENTRIES_DELETE_TIME_ENTRY = ("asana", "asana_time_tracking_entries_delete_time_entry", False)
    ASANA_TYPE_AHEAD_GET_RESULTS = ("asana", "asana_type_ahead_get_results", False)
    ASANA_USER_TASK_LISTS_GET_RECORD = ("asana", "asana_user_task_lists_get_record", False)
    ASANA_USER_TASK_LISTS_GET_USER_TASK_LIST = ("asana", "asana_user_task_lists_get_user_task_list", False)
    ASANA_USERS_LIST_MULTIPLE_USERS = ("asana", "asana_users_list_multiple_users", False)
    ASANA_USERS_GET_USER_RECORD = ("asana", "asana_users_get_user_record", False)
    ASANA_USERS_GET_FAVORITES_FOR_USER = ("asana", "asana_users_get_favorites_for_user", False)
    ASANA_USERS_LIST_TEAM_USERS = ("asana", "asana_users_list_team_users", False)
    ASANA_USERS_LIST_WORK_SPACE_USERS = ("asana", "asana_users_list_work_space_users", False)
    ASANA_WEB_HOOKS_LIST_MULTIPLE_WEB_HOOKS = ("asana", "asana_web_hooks_list_multiple_web_hooks", False)
    ASANA_WEB_HOOKS_ESTABLISH_WEB_HOOK = ("asana", "asana_web_hooks_establish_web_hook", False)
    ASANA_WEB_HOOKS_GET_WEB_HOOK_RECORD = ("asana", "asana_web_hooks_get_web_hook_record", False)
    ASANA_WEB_HOOKS_UPDATE_WEB_HOOK_FILTERS = ("asana", "asana_web_hooks_update_web_hook_filters", False)
    ASANA_WEB_HOOKS_REMOVE_WEB_HOOK = ("asana", "asana_web_hooks_remove_web_hook", False)
    ASANA_WORK_SPACE_MEMBERSHIPS_GET_RECORD_BY_ID = ("asana", "asana_work_space_memberships_get_record_by_id", False)
    ASANA_WORK_SPACE_MEMBERSHIPS_GET_USER_MEMBERSHIPS = ("asana", "asana_work_space_memberships_get_user_memberships", False)
    ASANA_WORK_SPACE_MEMBERSHIPS_LIST_FOR_WORK_SPACE = ("asana", "asana_work_space_memberships_list_for_work_space", False)
    ASANA_WORK_SPACES_LIST_MULTIPLE = ("asana", "asana_work_spaces_list_multiple", False)
    ASANA_WORK_SPACES_GET_WORK_SPACE_RECORD = ("asana", "asana_work_spaces_get_work_space_record", False)
    ASANA_WORK_SPACES_UPDATE_WORK_SPACE_RECORD = ("asana", "asana_work_spaces_update_work_space_record", False)
    ASANA_WORK_SPACES_ADD_USER_TO_WORK_SPACE = ("asana", "asana_work_spaces_add_user_to_work_space", False)
    ASANA_WORK_SPACES_REMOVE_USER_FROM_WORK_SPACE = ("asana", "asana_work_spaces_remove_user_from_work_space", False)
    CLICKUP_CREATE_TASK = ("clickup", "clickup_create_task", False)
    CLICKUP_GET_TASKS = ("clickup", "clickup_get_tasks", False)
    CLICKUP_GET_TASK = ("clickup", "clickup_get_task", False)
    CLICKUP_CREATE_LIST = ("clickup", "clickup_create_list", False)
    CLICKUP_GET_LISTS = ("clickup", "clickup_get_lists", False)
    CLICKUP_GET_SPACES = ("clickup", "clickup_get_spaces", False)
    CLICKUP_CREATE_SPACE = ("clickup", "clickup_create_space", False)
    CLICKUP_CREATE_FOLDER = ("clickup", "clickup_create_folder", False)
    CLICKUP_GET_FOLDERS = ("clickup", "clickup_get_folders", False)
    CODEINTERPRETER_EXECUTE_CODE = ("codeinterpreter", "codeinterpreter_execute_code", True)
    DROPBOX_GET_ABOUT_ME = ("dropbox", "dropbox_get_about_me", False)
    ELEVENLABS_GET_GENERATED_ITEMSV1_HISTORY_GET = ("elevenlabs", "elevenlabs_get_generated_itemsv1_history_get", False)
    ELEVENLABS_GET_HISTORY_ITEM_BY_IDV1_HISTORY_HISTORY_ITEMID_GET = ("elevenlabs", "elevenlabs_get_history_item_by_idv1_history_history_itemid_get", False)
    ELEVENLABS_DELETE_HISTORY_ITEMV1_HISTORY_HISTORY_ITEMID_DELETE = ("elevenlabs", "elevenlabs_delete_history_itemv1_history_history_itemid_delete", False)
    ELEVENLABS_GET_AUDIO_FROM_HISTORY_ITEMV1_HISTORY_HISTORY_ITEMID_AUDIO_GET = ("elevenlabs", "elevenlabs_get_audio_from_history_itemv1_history_history_itemid_audio_get", False)
    ELEVENLABS_DOWNLOAD_HISTORY_ITEMSV1_HISTORY_DOWNLOAD_POST = ("elevenlabs", "elevenlabs_download_history_itemsv1_history_download_post", False)
    ELEVENLABS_DELETE_SAMPLEV1_VOICES_VOICE_ID_SAMPLES_SAMPLE_ID_DELETE = ("elevenlabs", "elevenlabs_delete_samplev1_voices_voice_id_samples_sample_id_delete", False)
    ELEVENLABS_GET_AUDIO_FROM_SAMPLEV1_VOICES_VOICE_ID_SAMPLES_SAMPLE_ID_AUDIO_GET = ("elevenlabs", "elevenlabs_get_audio_from_samplev1_voices_voice_id_samples_sample_id_audio_get", False)
    ELEVENLABS_TEXT_TO_SPEECHV1_TEXT_TO_SPEECH_VOICE_ID_POST = ("elevenlabs", "elevenlabs_text_to_speechv1_text_to_speech_voice_id_post", False)
    ELEVENLABS_TEXT_TO_SPEECHV1_TEXT_TO_SPEECH_VOICE_ID_STREAM_POST = ("elevenlabs", "elevenlabs_text_to_speechv1_text_to_speech_voice_id_stream_post", False)
    ELEVENLABS_SPEECH_TO_SPEECHV1_SPEECH_TO_SPEECH_VOICE_ID_POST = ("elevenlabs", "elevenlabs_speech_to_speechv1_speech_to_speech_voice_id_post", False)
    ELEVENLABS_SPEECH_TO_SPEECH_STREAMINGV1_SPEECH_TO_SPEECH_VOICE_ID_STREAM_POST = ("elevenlabs", "elevenlabs_speech_to_speech_streamingv1_speech_to_speech_voice_id_stream_post", False)
    ELEVENLABS_VOICE_GENERATION_PARAMETERSV1_VOICE_GENERATION_GENERATE_VOICE_PARAMETERS_GET = ("elevenlabs", "elevenlabs_voice_generation_parametersv1_voice_generation_generate_voice_parameters_get", False)
    ELEVENLABS_GENERATEA_RANDOM_VOICEV1_VOICE_GENERATION_GENERATE_VOICE_POST = ("elevenlabs", "elevenlabs_generatea_random_voicev1_voice_generation_generate_voice_post", False)
    ELEVENLABS_CREATEA_PREVIOUSLY_GENERATED_VOICEV1_VOICE_GENERATION_CREATE_VOICE_POST = ("elevenlabs", "elevenlabs_createa_previously_generated_voicev1_voice_generation_create_voice_post", False)
    ELEVENLABS_GET_USER_SUBSCRIPTION_INFOV1_USER_SUBSCRIPTION_GET = ("elevenlabs", "elevenlabs_get_user_subscription_infov1_user_subscription_get", False)
    ELEVENLABS_GET_USER_INFOV1_USER_GET = ("elevenlabs", "elevenlabs_get_user_infov1_user_get", False)
    ELEVENLABS_GET_VOICESV1_VOICES_GET = ("elevenlabs", "elevenlabs_get_voicesv1_voices_get", False)
    ELEVENLABS_GET_DEFAULT_VOICE_SETTINGSV1_VOICES_SETTINGS_DEFAULT_GET = ("elevenlabs", "elevenlabs_get_default_voice_settingsv1_voices_settings_default_get", False)
    ELEVENLABS_GET_VOICE_SETTINGSV1_VOICES_VOICE_ID_SETTINGS_GET = ("elevenlabs", "elevenlabs_get_voice_settingsv1_voices_voice_id_settings_get", False)
    ELEVENLABS_GET_VOICEV1_VOICES_VOICE_ID_GET = ("elevenlabs", "elevenlabs_get_voicev1_voices_voice_id_get", False)
    ELEVENLABS_DELETE_VOICEV1_VOICES_VOICE_ID_DELETE = ("elevenlabs", "elevenlabs_delete_voicev1_voices_voice_id_delete", False)
    ELEVENLABS_ADD_VOICEV1_VOICES_ADD_POST = ("elevenlabs", "elevenlabs_add_voicev1_voices_add_post", False)
    ELEVENLABS_EDIT_VOICEV1_VOICES_VOICE_ID_EDIT_POST = ("elevenlabs", "elevenlabs_edit_voicev1_voices_voice_id_edit_post", False)
    ELEVENLABS_ADD_SHARING_VOICEV1_VOICES_ADD_PUBLIC_USE_RID_VOICE_ID_POST = ("elevenlabs", "elevenlabs_add_sharing_voicev1_voices_add_public_use_rid_voice_id_post", False)
    ELEVENLABS_GET_PROJECTSV1_PROJECTS_GET = ("elevenlabs", "elevenlabs_get_projectsv1_projects_get", False)
    ELEVENLABS_ADD_PROJECTV1_PROJECTS_ADD_POST = ("elevenlabs", "elevenlabs_add_projectv1_projects_add_post", False)
    ELEVENLABS_GET_PROJECT_BY_IDV1_PROJECTS_PROJECT_ID_GET = ("elevenlabs", "elevenlabs_get_project_by_idv1_projects_project_id_get", False)
    ELEVENLABS_DELETE_PROJECTV1_PROJECTS_PROJECT_ID_DELETE = ("elevenlabs", "elevenlabs_delete_projectv1_projects_project_id_delete", False)
    ELEVENLABS_CONVERT_PROJECTV1_PROJECTS_PROJECT_ID_CONVERT_POST = ("elevenlabs", "elevenlabs_convert_projectv1_projects_project_id_convert_post", False)
    ELEVENLABS_GET_PROJECT_SNAPSHOTSV1_PROJECTS_PROJECT_ID_SNAPSHOTS_GET = ("elevenlabs", "elevenlabs_get_project_snapshotsv1_projects_project_id_snapshots_get", False)
    ELEVENLABS_STREAM_PROJECT_AUDIOV1_PROJECTS_PROJECT_ID_SNAPSHOTS_PROJECT_SNAPSHOT_ID_STREAM_POST = ("elevenlabs", "elevenlabs_stream_project_audiov1_projects_project_id_snapshots_project_snapshot_id_stream_post", False)
    ELEVENLABS_STREAMS_ARCHIVE_WITH_PROJECT_AUDIOV1_PROJECTS_PROJECT_ID_SNAPSHOTS_PROJECT_SNAPSHOT_ID_ARCHIVE_POST = ("elevenlabs", "elevenlabs_streams_archive_with_project_audiov1_projects_project_id_snapshots_project_snapshot_id_archive_post", False)
    ELEVENLABS_GET_CHAPTERSV1_PROJECTS_PROJECT_ID_CHAPTERS_GET = ("elevenlabs", "elevenlabs_get_chaptersv1_projects_project_id_chapters_get", False)
    ELEVENLABS_GET_CHAPTER_BY_IDV1_PROJECTS_PROJECT_ID_CHAPTERS_CHAPTER_ID_GET = ("elevenlabs", "elevenlabs_get_chapter_by_idv1_projects_project_id_chapters_chapter_id_get", False)
    ELEVENLABS_DELETE_CHAPTERV1_PROJECTS_PROJECT_ID_CHAPTERS_CHAPTER_ID_DELETE = ("elevenlabs", "elevenlabs_delete_chapterv1_projects_project_id_chapters_chapter_id_delete", False)
    ELEVENLABS_CONVERT_CHAPTERV1_PROJECTS_PROJECT_ID_CHAPTERS_CHAPTER_ID_CONVERT_POST = ("elevenlabs", "elevenlabs_convert_chapterv1_projects_project_id_chapters_chapter_id_convert_post", False)
    ELEVENLABS_GET_CHAPTER_SNAPSHOTSV1_PROJECTS_PROJECT_ID_CHAPTERS_CHAPTER_ID_SNAPSHOTS_GET = ("elevenlabs", "elevenlabs_get_chapter_snapshotsv1_projects_project_id_chapters_chapter_id_snapshots_get", False)
    ELEVENLABS_STREAM_CHAPTER_AUDIOV1_PROJECTS_PROJECT_ID_CHAPTERS_CHAPTER_ID_SNAPSHOTS_CHAPTER_SNAPSHOT_ID_STREAM_POST = ("elevenlabs", "elevenlabs_stream_chapter_audiov1_projects_project_id_chapters_chapter_id_snapshots_chapter_snapshot_id_stream_post", False)
    ELEVENLABS_UPDATE_PRONUNCIATION_DICTIONARIESV1_PROJECTS_PROJECT_ID_UPDATE_PRONUNCIATION_DICTIONARIES_POST = ("elevenlabs", "elevenlabs_update_pronunciation_dictionariesv1_projects_project_id_update_pronunciation_dictionaries_post", False)
    ELEVENLABS_DUBA_VIDEO_OR_AN_AUDIOFILEV1_DUBBING_POST = ("elevenlabs", "elevenlabs_duba_video_or_an_audiofilev1_dubbing_post", False)
    ELEVENLABS_GET_DUBBING_PROJECT_METADATAV1_DUBBING_DUBBING_ID_GET = ("elevenlabs", "elevenlabs_get_dubbing_project_metadatav1_dubbing_dubbing_id_get", False)
    ELEVENLABS_DELETE_DUBBING_PROJECTV1_DUBBING_DUBBING_ID_DELETE = ("elevenlabs", "elevenlabs_delete_dubbing_projectv1_dubbing_dubbing_id_delete", False)
    ELEVENLABS_GET_DUBBED_FILEV1_DUBBING_DUBBING_ID_AUDIO_LANGUAGE_CODE_GET = ("elevenlabs", "elevenlabs_get_dubbed_filev1_dubbing_dubbing_id_audio_language_code_get", False)
    ELEVENLABS_GET_TRANSCRIPT_FOR_DUBV1_DUBBING_DUBBING_ID_TRANSCRIPT_LANGUAGE_CODE_GET = ("elevenlabs", "elevenlabs_get_transcript_for_dubv1_dubbing_dubbing_id_transcript_language_code_get", False)
    ELEVENLABS_GETS_SO_PROVIDER_ADMIN_ADMIN_ADMIN_URL_PREFIXS_SO_PROVIDER_GET = ("elevenlabs", "elevenlabs_gets_so_provider_admin_admin_admin_url_prefixs_so_provider_get", False)
    ELEVENLABS_GET_MODELSV1_MODELS_GET = ("elevenlabs", "elevenlabs_get_modelsv1_models_get", False)
    ELEVENLABS_CREATES_AUDIO_NATIVE_ENABLED_PROJECTV1_AUDIO_NATIVE_POST = ("elevenlabs", "elevenlabs_creates_audio_native_enabled_projectv1_audio_native_post", False)
    ELEVENLABS_GET_VOICESV1_SHARED_VOICES_GET = ("elevenlabs", "elevenlabs_get_voicesv1_shared_voices_get", False)
    ELEVENLABS_ADDA_PRONUNCIATION_DICTIONARYV1_PRONUNCIATION_DICTIONARIES_ADD_FROM_FILE_POST = ("elevenlabs", "elevenlabs_adda_pronunciation_dictionaryv1_pronunciation_dictionaries_add_from_file_post", False)
    ELEVENLABS_ADD_RULES_TO_THE_PRONUNCIATION_DICTIONARYV1_PRONUNCIATION_DICTIONARIES_PRONUNCIATION_DICTIONARY_ID_ADD_RULES_POST = ("elevenlabs", "elevenlabs_add_rules_to_the_pronunciation_dictionaryv1_pronunciation_dictionaries_pronunciation_dictionary_id_add_rules_post", False)
    ELEVENLABS_REMOVE_RULES_FROM_THE_PRONUNCIATION_DICTIONARYV1_PRONUNCIATION_DICTIONARIES_PRONUNCIATION_DICTIONARY_ID_REMOVE_RULES_POST = ("elevenlabs", "elevenlabs_remove_rules_from_the_pronunciation_dictionaryv1_pronunciation_dictionaries_pronunciation_dictionary_id_remove_rules_post", False)
    ELEVENLABS_GET_PLS_FILE_WITHA_PRONUNCIATION_DICTIONARY_VERSION_RULESV1_PRONUNCIATION_DICTIONARIES_DICTIONARY_ID_VERSION_ID_DOWNLOAD_GET = ("elevenlabs", "elevenlabs_get_pls_file_witha_pronunciation_dictionary_version_rulesv1_pronunciation_dictionaries_dictionary_id_version_id_download_get", False)
    ELEVENLABS_GET_METADATA_FORA_PRONUNCIATION_DICTIONARYV1_PRONUNCIATION_DICTIONARIES_PRONUNCIATION_DICTIONARY_ID_GET = ("elevenlabs", "elevenlabs_get_metadata_fora_pronunciation_dictionaryv1_pronunciation_dictionaries_pronunciation_dictionary_id_get", False)
    ELEVENLABS_GET_PRONUNCIATION_DICTIONARIESV1_PRONUNCIATION_DICTIONARIES_GET = ("elevenlabs", "elevenlabs_get_pronunciation_dictionariesv1_pronunciation_dictionaries_get", False)
    ELEVENLABS_GETA_PROFILE_PAGE_PROFILE_HANDLE_GET = ("elevenlabs", "elevenlabs_geta_profile_page_profile_handle_get", False)
    ELEVENLABS_REDIRECT_TO_MINT_LI_FY_DOCS_GET = ("elevenlabs", "elevenlabs_redirect_to_mint_li_fy_docs_get", False)
    EXA_SEARCH = ("exa", "exa_search", True)
    EXA_SIMILARLINK = ("exa", "exa_similarlink", True)
    FILEMANAGER_CREATE_SHELL_ACTION = ("filemanager", "filemanager_create_shell_action", True)
    FILEMANAGER_CLOSE_SHELL_ACTION = ("filemanager", "filemanager_close_shell_action", True)
    FILEMANAGER_RUN_COMMAND_ACTION = ("filemanager", "filemanager_run_command_action", True)
    FILEMANAGER_SET_ENV_VAR_ACTION = ("filemanager", "filemanager_set_env_var_action", True)
    FILEMANAGER_OPEN_FILE_ACTION = ("filemanager", "filemanager_open_file_action", True)
    FILEMANAGER_GOTO_LINE_ACTION = ("filemanager", "filemanager_goto_line_action", True)
    FILEMANAGER_SCROLL_ACTION = ("filemanager", "filemanager_scroll_action", True)
    FILEMANAGER_CREATE_FILE_ACTION = ("filemanager", "filemanager_create_file_action", True)
    FILEMANAGER_EDIT_FILE_ACTION = ("filemanager", "filemanager_edit_file_action", True)
    GOOGLECALENDAR_CREATE_GOOGLE_EVENT = ("gcalendar", "googlecalendar_create_google_event", False)
    GOOGLECALENDAR_REMOVE_ATTENDEE = ("gcalendar", "googlecalendar_remove_attendee", False)
    GOOGLECALENDAR_FIND_EVENT = ("gcalendar", "googlecalendar_find_event", False)
    GOOGLECALENDAR_DELETE_GOOGLE_EVENT = ("gcalendar", "googlecalendar_delete_google_event", False)
    GOOGLECALENDAR_UPDATE_GOOGLE_EVENT = ("gcalendar", "googlecalendar_update_google_event", False)
    GOOGLECALENDAR_FIND_FREE_SLOTS = ("gcalendar", "googlecalendar_find_free_slots", False)
    GOOGLECALENDAR_DUPLICATE_GOOGLE_CALENDAR = ("gcalendar", "googlecalendar_duplicate_google_calendar", False)
    GOOGLECALENDAR_LIST_GOOGLE_CALENDARS = ("gcalendar", "googlecalendar_list_google_calendars", False)
    GOOGLECALENDAR_PATCH_GOOGLE_CALENDAR = ("gcalendar", "googlecalendar_patch_google_calendar", False)
    GOOGLECALENDAR_QUICK_ADD_GOOGLE_CALENDAR = ("gcalendar", "googlecalendar_quick_add_google_calendar", False)
    GOOGLECALENDAR_GET_CURRENT_DATE_TIME = ("gcalendar", "googlecalendar_get_current_date_time", False)
    GITHUB_CREATE_ISSUE = ("github", "github_create_issue", False)
    GITHUB_LIST_GITHUB_REPOS = ("github", "github_list_github_repos", False)
    GITHUB_STAR_REPO = ("github", "github_star_repo", False)
    GITHUB_GET_ABOUT_ME = ("github", "github_get_about_me", False)
    GITHUB_FETCH_README = ("github", "github_fetch_readme", False)
    GITHUB_GET_COMMITS = ("github", "github_get_commits", False)
    GITHUB_GET_COMMITS_WITH_CODE = ("github", "github_get_commits_with_code", False)
    GITHUB_GET_PATCH_FOR_COMMIT = ("github", "github_get_patch_for_commit", False)
    GMAIL_SEND_EMAIL = ("gmail", "gmail_send_email", False)
    GMAIL_CREATE_EMAIL_DRAFT = ("gmail", "gmail_create_email_draft", False)
    GMAIL_FIND_EMAIL_ID = ("gmail", "gmail_find_email_id", False)
    GMAIL_FETCH_LAST_THREE_MESSAGES = ("gmail", "gmail_fetch_last_three_messages", False)
    GMAIL_ADD_LABEL_TO_EMAIL = ("gmail", "gmail_add_label_to_email", False)
    GMAIL_LIST_LABELS = ("gmail", "gmail_list_labels", False)
    GMAIL_FETCH_MESSAGE_BY_THREAD_ID = ("gmail", "gmail_fetch_message_by_thread_id", False)
    GMAIL_REPLY_TO_THREAD = ("gmail", "gmail_reply_to_thread", False)
    GMAIL_FETCH_EMAILS_WITH_LABEL = ("gmail", "gmail_fetch_emails_with_label", False)
    LINEAR_CREATE_LINEAR_ISSUE = ("linear", "linear_create_linear_issue", False)
    LINEAR_LIST_LINEAR_PROJECTS = ("linear", "linear_list_linear_projects", False)
    LINEAR_LIST_LINEAR_TEAMS = ("linear", "linear_list_linear_teams", False)
    LISTENNOTES_SEARCH = ("listennotes", "listennotes_search", False)
    LISTENNOTES_TYPE_AHEAD = ("listennotes", "listennotes_type_ahead", False)
    LISTENNOTES_SEARCH_EPISODE_TITLES = ("listennotes", "listennotes_search_episode_titles", False)
    LISTENNOTES_GET_TRENDING_SEARCHES = ("listennotes", "listennotes_get_trending_searches", False)
    LISTENNOTES_GET_RELATED_SEARCHES = ("listennotes", "listennotes_get_related_searches", False)
    LISTENNOTES_SPELL_CHECK = ("listennotes", "listennotes_spell_check", False)
    LISTENNOTES_GET_BEST_PODCASTS = ("listennotes", "listennotes_get_best_podcasts", False)
    LISTENNOTES_GET_PODCAST_BY_ID = ("listennotes", "listennotes_get_podcast_by_id", False)
    LISTENNOTES_DELETE_PODCAST_BY_ID = ("listennotes", "listennotes_delete_podcast_by_id", False)
    LISTENNOTES_GET_EPISODE_BY_ID = ("listennotes", "listennotes_get_episode_by_id", False)
    LISTENNOTES_GET_EPISODES_IN_BATCH = ("listennotes", "listennotes_get_episodes_in_batch", False)
    LISTENNOTES_GET_PODCASTS_IN_BATCH = ("listennotes", "listennotes_get_podcasts_in_batch", False)
    LISTENNOTES_GET_CURATED_PODCAST_BY_ID = ("listennotes", "listennotes_get_curated_podcast_by_id", False)
    LISTENNOTES_GET_GENRES = ("listennotes", "listennotes_get_genres", False)
    LISTENNOTES_GET_REGIONS = ("listennotes", "listennotes_get_regions", False)
    LISTENNOTES_GET_LANGUAGES = ("listennotes", "listennotes_get_languages", False)
    LISTENNOTES_JUST_LISTEN = ("listennotes", "listennotes_just_listen", False)
    LISTENNOTES_GET_CURATED_PODCASTS = ("listennotes", "listennotes_get_curated_podcasts", False)
    LISTENNOTES_GET_PODCAST_RECOMMENDATIONS = ("listennotes", "listennotes_get_podcast_recommendations", False)
    LISTENNOTES_GET_EPISODE_RECOMMENDATIONS = ("listennotes", "listennotes_get_episode_recommendations", False)
    LISTENNOTES_SUBMIT_PODCAST = ("listennotes", "listennotes_submit_podcast", False)
    LISTENNOTES_REFRESH_RSS = ("listennotes", "listennotes_refresh_rss", False)
    LISTENNOTES_GET_PLAYLIST_BY_ID = ("listennotes", "listennotes_get_playlist_by_id", False)
    LISTENNOTES_GET_PLAYLISTS = ("listennotes", "listennotes_get_playlists", False)
    LISTENNOTES_GET_PODCAST_AUDIENCE = ("listennotes", "listennotes_get_podcast_audience", False)
    LISTENNOTES_GET_PODCASTS_BY_DOMAIN_NAME = ("listennotes", "listennotes_get_podcasts_by_domain_name", False)
    NOTION_GET_ABOUT_ME = ("notion", "notion_get_about_me", False)
    NOTION_ADD_NOTION_PAGE_CHILDREN = ("notion", "notion_add_notion_page_children", False)
    NOTION_ARCHIVE_NOTION_PAGE = ("notion", "notion_archive_notion_page", False)
    NOTION_CREATE_NOTION_DATABASE = ("notion", "notion_create_notion_database", False)
    NOTION_CREATE_PAGE_COMMENT = ("notion", "notion_create_page_comment", False)
    NOTION_CREATE_NOTION_PAGE = ("notion", "notion_create_notion_page", False)
    NOTION_DELETE_NOTION_PAGE_CHILDREN = ("notion", "notion_delete_notion_page_children", False)
    NOTION_FETCH_NOTION_COMMENT = ("notion", "notion_fetch_notion_comment", False)
    NOTION_FETCH_NOTION_DATABASE = ("notion", "notion_fetch_notion_database", False)
    NOTION_FETCH_NOTION_PAGE = ("notion", "notion_fetch_notion_page", False)
    NOTION_SEARCH_NOTION_PAGE = ("notion", "notion_search_notion_page", False)
    NOTION_UPDATE_NOTION_DATABASE = ("notion", "notion_update_notion_database", False)
    NOTION_FETCH_NOTION_BLOCK = ("notion", "notion_fetch_notion_block", False)
    NOTION_FETCH_NOTION_CHILD_BLOCK = ("notion", "notion_fetch_notion_child_block", False)
    SERPAPI_SEARCH = ("serpapi", "serpapi_search", True)
    SLACK_SEND_SLACK_MESSAGE = ("slack", "slack_send_slack_message", False)
    SLACK_LIST_SLACK_CHANNELS = ("slack", "slack_list_slack_channels", False)
    SLACK_LIST_SLACK_MEMBERS = ("slack", "slack_list_slack_members", False)
    SLACK_LIST_SLACK_MESSAGES = ("slack", "slack_list_slack_messages", False)
    SLACKBOT_SEND_SLACK_MESSAGE = ("slackbot", "slackbot_send_slack_message", False)
    SLACKBOT_LIST_SLACK_CHANNELS = ("slackbot", "slackbot_list_slack_channels", False)
    SLACKBOT_LIST_SLACK_MEMBERS = ("slackbot", "slackbot_list_slack_members", False)
    SLACKBOT_LIST_SLACK_MESSAGES = ("slackbot", "slackbot_list_slack_messages", False)
    SNOWFLAKE_RUN_QUERY = ("snowflake", "snowflake_run_query", False)
    SNOWFLAKE_SHOW_TABLES = ("snowflake", "snowflake_show_tables", False)
    SNOWFLAKE_DESCRIBE_TABLE = ("snowflake", "snowflake_describe_table", False)
    SNOWFLAKE_EXPLORE_COLUMNS = ("snowflake", "snowflake_explore_columns", False)
    TRELLO_CREATE_TRELLO_LIST = ("trello", "trello_create_trello_list", False)
    TRELLO_CREATE_TRELLO_CARD = ("trello", "trello_create_trello_card", False)
    TRELLO_GET_TRELLO_BOARD_CARDS = ("trello", "trello_get_trello_board_cards", False)
    TRELLO_DELETE_TRELLO_CARD = ("trello", "trello_delete_trello_card", False)
    TRELLO_ADD_TRELLO_CARD_COMMENT = ("trello", "trello_add_trello_card_comment", False)
    TRELLO_CREATE_TRELLO_LABEL = ("trello", "trello_create_trello_label", False)
    TRELLO_UPDATE_TRELLO_BOARD = ("trello", "trello_update_trello_board", False)
    TRELLO_GET_ABOUT_ME = ("trello", "trello_get_about_me", False)
    TRELLO_SEARCH_TRELLO = ("trello", "trello_search_trello", False)
    TRELLO_SEARCH_TRELLO_MEMBER = ("trello", "trello_search_trello_member", False)
    TRELLO_UPDATE_TRELLO_CARD = ("trello", "trello_update_trello_card", False)
    TRELLO_GET_TRELLO_MEMBER_BOARD = ("trello", "trello_get_trello_member_board", False)
    TYPEFORM_GET_ABOUT_ME = ("typeform", "typeform_get_about_me", False)
    ZENDESK_CREATE_ZENDESK_ORGANIZATION = ("zendesk", "zendesk_create_zendesk_organization", False)
    ZENDESK_DELETE_ZENDESK_ORGANIZATION = ("zendesk", "zendesk_delete_zendesk_organization", False)
    ZENDESK_COUNT_ZENDESK_ORGANIZATIONS = ("zendesk", "zendesk_count_zendesk_organizations", False)
    ZENDESK_GET_ZENDESK_ORGANIZATION = ("zendesk", "zendesk_get_zendesk_organization", False)
    ZENDESK_GET_ALL_ZENDESK_ORGANIZATIONS = ("zendesk", "zendesk_get_all_zendesk_organizations", False)
    ZENDESK_UPDATE_ZENDESK_ORGANIZATION = ("zendesk", "zendesk_update_zendesk_organization", False)
    ZENDESK_CREATE_ZENDESK_TICKET = ("zendesk", "zendesk_create_zendesk_ticket", False)
    ZENDESK_DELETE_ZENDESK_TICKET = ("zendesk", "zendesk_delete_zendesk_ticket", False)
    ZENDESK_GET_ABOUT_ME = ("zendesk", "zendesk_get_about_me", False)
    ZOOM_ARCHIVING_MEETING_FILES_LIST = ("zoom", "zoom_archiving_meeting_files_list", False)
    ZOOM_ARCHIVING_GET_STATISTICS = ("zoom", "zoom_archiving_get_statistics", False)
    ZOOM_ARCHIVING_UPDATE_AUTO_DELETE_STATUS = ("zoom", "zoom_archiving_update_auto_delete_status", False)
    ZOOM_ARCHIVING_MEETING_FILES_LIST2 = ("zoom", "zoom_archiving_meeting_files_list2", False)
    ZOOM_ARCHIVING_MEETING_FILES_DELETE = ("zoom", "zoom_archiving_meeting_files_delete", False)
    ZOOM_CLOUD_RECORDING_GET_MEETING_RECORDINGS = ("zoom", "zoom_cloud_recording_get_meeting_recordings", False)
    ZOOM_CLOUD_RECORDING_DELETE_MEETING_RECORDINGS = ("zoom", "zoom_cloud_recording_delete_meeting_recordings", False)
    ZOOM_ANALYTICS_DETAILS = ("zoom", "zoom_analytics_details", False)
    ZOOM_ANALYTICS_SUMMARY = ("zoom", "zoom_analytics_summary", False)
    ZOOM_CLOUD_RECORDING_LIST_REGISTRANTS = ("zoom", "zoom_cloud_recording_list_registrants", False)
    ZOOM_CLOUD_RECORDING_CREATE_REGISTRANT = ("zoom", "zoom_cloud_recording_create_registrant", False)
    ZOOM_CLOUD_RECORDING_LIST_REGISTRATION_QUESTIONS = ("zoom", "zoom_cloud_recording_list_registration_questions", False)
    ZOOM_CLOUD_RECORDING_UPDATE_REGISTRATION_QUESTIONS = ("zoom", "zoom_cloud_recording_update_registration_questions", False)
    ZOOM_CLOUD_RECORDING_UPDATE_REGISTRANT_STATUS = ("zoom", "zoom_cloud_recording_update_registrant_status", False)
    ZOOM_CLOUD_RECORDING_GET_SETTINGS = ("zoom", "zoom_cloud_recording_get_settings", False)
    ZOOM_CLOUD_RECORDING_UPDATE_SETTINGS = ("zoom", "zoom_cloud_recording_update_settings", False)
    ZOOM_CLOUD_RECORDING_DELETE_RECORDING = ("zoom", "zoom_cloud_recording_delete_recording", False)
    ZOOM_CLOUD_RECORDING_RECOVER_STATUS = ("zoom", "zoom_cloud_recording_recover_status", False)
    ZOOM_CLOUD_RECORDING_RECOVER_RECORDING_STATUS = ("zoom", "zoom_cloud_recording_recover_recording_status", False)
    ZOOM_CLOUD_RECORDING_LIST_RECORDINGS = ("zoom", "zoom_cloud_recording_list_recordings", False)
    ZOOM_DEVICES_LIST = ("zoom", "zoom_devices_list", False)
    ZOOM_DEVICES_CREATE_NEW_DEVICE = ("zoom", "zoom_devices_create_new_device", False)
    ZOOM_DEVICES_LIST_ZDM_GROUP_INFO = ("zoom", "zoom_devices_list_zdm_group_info", False)
    ZOOM_DEVICES_ASSIGN_DEVICE_ZPA_ASSIGNMENT = ("zoom", "zoom_devices_assign_device_zpa_assignment", False)
    ZOOM_DEVICES_UPGRADE_ZPA_OS_APP = ("zoom", "zoom_devices_upgrade_zpa_os_app", False)
    ZOOM_DEVICES_REMOVE_ZPA_DEVICE_BY_VENDOR_AND_MAC_ADDRESS = ("zoom", "zoom_devices_remove_zpa_device_by_vendor_and_mac_address", False)
    ZOOM_DEVICES_GET_ZPA_VERSION_INFO = ("zoom", "zoom_devices_get_zpa_version_info", False)
    ZOOM_DEVICES_GET_DETAIL = ("zoom", "zoom_devices_get_detail", False)
    ZOOM_DEVICES_REMOVE_DEVICE_ZMD = ("zoom", "zoom_devices_remove_device_zmd", False)
    ZOOM_DEVICES_UPDATE_DEVICE_NAME = ("zoom", "zoom_devices_update_device_name", False)
    ZOOM_DEVICES_CHANGE_DEVICE_ASSOCIATION = ("zoom", "zoom_devices_change_device_association", False)
    ZOOM_H323_DEVICES_LIST_DEVICES = ("zoom", "zoom_h323_devices_list_devices", False)
    ZOOM_H323_DEVICES_CREATE_DEVICE = ("zoom", "zoom_h323_devices_create_device", False)
    ZOOM_H323_DEVICES_DELETE_DEVICE = ("zoom", "zoom_h323_devices_delete_device", False)
    ZOOM_H323_DEVICES_UPDATE_DEVICE_INFO = ("zoom", "zoom_h323_devices_update_device_info", False)
    ZOOM_MEETINGS_DELETE_MEETING_CHAT_MESSAGE = ("zoom", "zoom_meetings_delete_meeting_chat_message", False)
    ZOOM_MEETINGS_UPDATE_MESSAGE = ("zoom", "zoom_meetings_update_message", False)
    ZOOM_MEETINGS_CONTROL_IN_MEETING_FEATURES = ("zoom", "zoom_meetings_control_in_meeting_features", False)
    ZOOM_MEETINGS_LIST_MEETING_SUMMARIES = ("zoom", "zoom_meetings_list_meeting_summaries", False)
    ZOOM_MEETINGS_GET_DETAILS = ("zoom", "zoom_meetings_get_details", False)
    ZOOM_MEETINGS_REMOVE_MEETING = ("zoom", "zoom_meetings_remove_meeting", False)
    ZOOM_MEETINGS_UPDATE_DETAILS = ("zoom", "zoom_meetings_update_details", False)
    ZOOM_MEETINGS_CREATE_BATCH_POLLS = ("zoom", "zoom_meetings_create_batch_polls", False)
    ZOOM_MEETINGS_BATCH_REGISTRANTS_CREATE = ("zoom", "zoom_meetings_batch_registrants_create", False)
    ZOOM_MEETINGS_GET_INVITATION_NOTE = ("zoom", "zoom_meetings_get_invitation_note", False)
    ZOOM_MEETINGS_CREATE_INVITE_LINKS = ("zoom", "zoom_meetings_create_invite_links", False)
    ZOOM_MEETINGS_GET_JOIN_TOKEN = ("zoom", "zoom_meetings_get_join_token", False)
    ZOOM_MEETINGS_GET_MEETING_ARCHIVE_TOKEN_FOR_LOCAL_ARCHIVING = ("zoom", "zoom_meetings_get_meeting_archive_token_for_local_archiving", False)
    ZOOM_MEETINGS_GET_JOIN_TOKEN_LOCAL_RECORDING = ("zoom", "zoom_meetings_get_join_token_local_recording", False)
    ZOOM_MEETINGS_GET_LIVE_STREAM_DETAILS = ("zoom", "zoom_meetings_get_live_stream_details", False)
    ZOOM_MEETINGS_UPDATE_LIVE_STREAM = ("zoom", "zoom_meetings_update_live_stream", False)
    ZOOM_MEETINGS_LIVE_STREAM_STATUS_UPDATE = ("zoom", "zoom_meetings_live_stream_status_update", False)
    ZOOM_MEETINGS_GET_MEETING_SUMMARY = ("zoom", "zoom_meetings_get_meeting_summary", False)
    ZOOM_MEETINGS_LIST_MEETING_POLLS = ("zoom", "zoom_meetings_list_meeting_polls", False)
    ZOOM_MEETINGS_CREATE_POLL = ("zoom", "zoom_meetings_create_poll", False)
    ZOOM_MEETINGS_GET_POLL = ("zoom", "zoom_meetings_get_poll", False)
    ZOOM_MEETINGS_UPDATE_MEETING_POLL = ("zoom", "zoom_meetings_update_meeting_poll", False)
    ZOOM_MEETINGS_POLL_DELETE = ("zoom", "zoom_meetings_poll_delete", False)
    ZOOM_MEETINGS_LIST_REGISTRANTS = ("zoom", "zoom_meetings_list_registrants", False)
    ZOOM_MEETINGS_ADD_REGISTRANT = ("zoom", "zoom_meetings_add_registrant", False)
    ZOOM_MEETINGS_LIST_REGISTRATION_QUESTIONS = ("zoom", "zoom_meetings_list_registration_questions", False)
    ZOOM_MEETINGS_UPDATE_REGISTRATION_QUESTIONS = ("zoom", "zoom_meetings_update_registration_questions", False)
    ZOOM_MEETINGS_UPDATE_REGISTRANT_STATUS = ("zoom", "zoom_meetings_update_registrant_status", False)
    ZOOM_MEETINGS_GET_REGISTRANT_DETAILS = ("zoom", "zoom_meetings_get_registrant_details", False)
    ZOOM_MEETINGS_DELETE_REGISTRANT = ("zoom", "zoom_meetings_delete_registrant", False)
    ZOOM_MEETINGS_GETS_IP_URI_WITH_PASS_CODE = ("zoom", "zoom_meetings_gets_ip_uri_with_pass_code", False)
    ZOOM_MEETINGS_UPDATE_MEETING_STATUS = ("zoom", "zoom_meetings_update_meeting_status", False)
    ZOOM_MEETINGS_GET_MEETING_SURVEY = ("zoom", "zoom_meetings_get_meeting_survey", False)
    ZOOM_MEETINGS_DELETE_MEETING_SURVEY = ("zoom", "zoom_meetings_delete_meeting_survey", False)
    ZOOM_MEETINGS_UPDATE_SURVEY = ("zoom", "zoom_meetings_update_survey", False)
    ZOOM_MEETINGS_GET_MEETING_TOKEN = ("zoom", "zoom_meetings_get_meeting_token", False)
    ZOOM_MEETINGS_GET_DETAILS2 = ("zoom", "zoom_meetings_get_details2", False)
    ZOOM_MEETINGS_LIST_PAST_MEETING_INSTANCES = ("zoom", "zoom_meetings_list_past_meeting_instances", False)
    ZOOM_MEETINGS_GET_PAST_MEETING_PARTICIPANTS = ("zoom", "zoom_meetings_get_past_meeting_participants", False)
    ZOOM_MEETINGS_LIST_PAST_MEETING_POLLS = ("zoom", "zoom_meetings_list_past_meeting_polls", False)
    ZOOM_MEETINGS_LIST_PAST_MEETING_QA = ("zoom", "zoom_meetings_list_past_meeting_qa", False)
    ZOOM_MEETINGS_LIST_MEETING_TEMPLATES = ("zoom", "zoom_meetings_list_meeting_templates", False)
    ZOOM_MEETINGS_CREATE_TEMPLATE_FROM_MEETING = ("zoom", "zoom_meetings_create_template_from_meeting", False)
    ZOOM_MEETINGS_LIST_HOST_SCHEDULED = ("zoom", "zoom_meetings_list_host_scheduled", False)
    ZOOM_MEETINGS_CREATE_MEETING = ("zoom", "zoom_meetings_create_meeting", False)
    ZOOM_MEETINGS_LIST_UPCOMING_MEETINGS = ("zoom", "zoom_meetings_list_upcoming_meetings", False)
    ZOOM_PAC_LIST_ACCOUNTS = ("zoom", "zoom_pac_list_accounts", False)
    ZOOM_REPORTS_LIST_SIGN_IN_SIGN_OUT_ACTIVITIES = ("zoom", "zoom_reports_list_sign_in_sign_out_activities", False)
    ZOOM_REPORTS_GET_BILLING_DEPARTMENT_REPORTS = ("zoom", "zoom_reports_get_billing_department_reports", False)
    ZOOM_REPORTS_GET_BILLING_INVOICES = ("zoom", "zoom_reports_get_billing_invoices", False)
    ZOOM_REPORTS_GET_CLOUD_RECORDING_USAGE_REPORT = ("zoom", "zoom_reports_get_cloud_recording_usage_report", False)
    ZOOM_REPORTS_GET_DAILY_USAGE_REPORT = ("zoom", "zoom_reports_get_daily_usage_report", False)
    ZOOM_REPORTS_GET_MEETING_DETAIL_REPORTS = ("zoom", "zoom_reports_get_meeting_detail_reports", False)
    ZOOM_REPORTS_GET_MEETING_PARTICIPANT_REPORTS = ("zoom", "zoom_reports_get_meeting_participant_reports", False)
    ZOOM_REPORTS_GET_MEETING_POLL_REPORTS = ("zoom", "zoom_reports_get_meeting_poll_reports", False)
    ZOOM_REPORTS_GET_MEETING_QA_REPORT = ("zoom", "zoom_reports_get_meeting_qa_report", False)
    ZOOM_REPORTS_GET_MEETING_SURVEY_REPORT = ("zoom", "zoom_reports_get_meeting_survey_report", False)
    ZOOM_REPORTS_GET_OPERATION_LOGS_REPORT = ("zoom", "zoom_reports_get_operation_logs_report", False)
    ZOOM_REPORTS_GET_TELEPHONE_REPORTS = ("zoom", "zoom_reports_get_telephone_reports", False)
    ZOOM_REPORTS_LIST_UPCOMING_EVENTS_REPORT = ("zoom", "zoom_reports_list_upcoming_events_report", False)
    ZOOM_REPORTS_GET_ACTIVE_INACTIVE_HOST_REPORTS = ("zoom", "zoom_reports_get_active_inactive_host_reports", False)
    ZOOM_REPORTS_GET_MEETING_REPORTS = ("zoom", "zoom_reports_get_meeting_reports", False)
    ZOOM_REPORTS_GET_WEB_IN_AR_DETAILS_REPORT = ("zoom", "zoom_reports_get_web_in_ar_details_report", False)
    ZOOM_REPORTS_WEB_IN_AR_PARTICIPANTS_LIST = ("zoom", "zoom_reports_web_in_ar_participants_list", False)
    ZOOM_REPORTS_GET_WEB_IN_AR_POLL_REPORTS = ("zoom", "zoom_reports_get_web_in_ar_poll_reports", False)
    ZOOM_REPORTS_GET_WEB_IN_AR_QA_REPORT = ("zoom", "zoom_reports_get_web_in_ar_qa_report", False)
    ZOOM_REPORTS_GET_WEB_IN_AR_SURVEY_REPORT = ("zoom", "zoom_reports_get_web_in_ar_survey_report", False)
    ZOOM_SIP_PHONE_LIST = ("zoom", "zoom_sip_phone_list", False)
    ZOOM_SIP_PHONE_ENABLE_USERS_IP_PHONE = ("zoom", "zoom_sip_phone_enable_users_ip_phone", False)
    ZOOM_SIP_PHONE_DELETE_PHONE = ("zoom", "zoom_sip_phone_delete_phone", False)
    ZOOM_SIP_PHONE_UPDATE_SPECIFIC_PHONE = ("zoom", "zoom_sip_phone_update_specific_phone", False)
    ZOOM_TSP_GET_ACCOUNT_INFO = ("zoom", "zoom_tsp_get_account_info", False)
    ZOOM_TSP_UPDATE_ACCOUNT_TSP_INFORMATION = ("zoom", "zoom_tsp_update_account_tsp_information", False)
    ZOOM_TSP_LIST_USE_RTSP_ACCOUNTS = ("zoom", "zoom_tsp_list_use_rtsp_accounts", False)
    ZOOM_TSP_ADD_USE_RTSP_ACCOUNT = ("zoom", "zoom_tsp_add_use_rtsp_account", False)
    ZOOM_TSP_SET_GLOBAL_DIAL_IN_URL = ("zoom", "zoom_tsp_set_global_dial_in_url", False)
    ZOOM_TSP_GET_USE_RTSP_ACCOUNT = ("zoom", "zoom_tsp_get_use_rtsp_account", False)
    ZOOM_TSP_DELETE_USE_RTSP_ACCOUNT = ("zoom", "zoom_tsp_delete_use_rtsp_account", False)
    ZOOM_TSP_UPDATE_USE_RTSP_ACCOUNT = ("zoom", "zoom_tsp_update_use_rtsp_account", False)
    ZOOM_TRACKING_FIELD_LIST = ("zoom", "zoom_tracking_field_list", False)
    ZOOM_TRACKING_FIELD_CREATE_FIELD = ("zoom", "zoom_tracking_field_create_field", False)
    ZOOM_TRACKING_FIELD_GET = ("zoom", "zoom_tracking_field_get", False)
    ZOOM_TRACKING_FIELD_DELETE_FIELD = ("zoom", "zoom_tracking_field_delete_field", False)
    ZOOM_TRACKING_FIELD_UPDATE = ("zoom", "zoom_tracking_field_update", False)
    ZOOM_WEB_IN_ARS_DELETE_MESSAGE_BY_ID = ("zoom", "zoom_web_in_ars_delete_message_by_id", False)
    ZOOM_WEB_IN_ARS_LIST_ABSENTEES = ("zoom", "zoom_web_in_ars_list_absentees", False)
    ZOOM_WEB_IN_ARS_LIST_PAST_INSTANCES = ("zoom", "zoom_web_in_ars_list_past_instances", False)
    ZOOM_WEB_IN_ARS_LIST_PARTICIPANTS = ("zoom", "zoom_web_in_ars_list_participants", False)
    ZOOM_WEB_IN_ARS_LIST_POLL_RESULTS = ("zoom", "zoom_web_in_ars_list_poll_results", False)
    ZOOM_WEB_IN_ARS_LIST_PAST_WEB_IN_AR_QA = ("zoom", "zoom_web_in_ars_list_past_web_in_ar_qa", False)
    ZOOM_WEB_IN_ARS_LIST_WEB_IN_AR_TEMPLATES = ("zoom", "zoom_web_in_ars_list_web_in_ar_templates", False)
    ZOOM_WEB_IN_ARS_CREATE_WEB_IN_AR_TEMPLATE = ("zoom", "zoom_web_in_ars_create_web_in_ar_template", False)
    ZOOM_WEB_IN_ARS_LIST_WEB_IN_ARS = ("zoom", "zoom_web_in_ars_list_web_in_ars", False)
    ZOOM_WEB_IN_ARS_CREATE_WEB_IN_AR = ("zoom", "zoom_web_in_ars_create_web_in_ar", False)
    ZOOM_WEB_IN_ARS_GET_DETAILS = ("zoom", "zoom_web_in_ars_get_details", False)
    ZOOM_WEB_IN_ARS_REMOVE_WEB_IN_AR = ("zoom", "zoom_web_in_ars_remove_web_in_ar", False)
    ZOOM_WEB_IN_ARS_UPDATE_SCHEDULED_WEB_IN_AR = ("zoom", "zoom_web_in_ars_update_scheduled_web_in_ar", False)
    ZOOM_WEB_IN_ARS_CREATE_BATCH_REGISTRANTS = ("zoom", "zoom_web_in_ars_create_batch_registrants", False)
    ZOOM_WEB_IN_ARS_GET_SESSION_BRANDING = ("zoom", "zoom_web_in_ars_get_session_branding", False)
    ZOOM_WEB_IN_ARS_CREATE_BRANDING_NAME_TAG = ("zoom", "zoom_web_in_ars_create_branding_name_tag", False)
    ZOOM_WEB_IN_ARS_DELETE_BRANDING_NAME_TAG = ("zoom", "zoom_web_in_ars_delete_branding_name_tag", False)
    ZOOM_WEB_IN_ARS_UPDATE_BRANDING_NAME_TAG = ("zoom", "zoom_web_in_ars_update_branding_name_tag", False)
    ZOOM_WEB_IN_ARS_UPLOAD_BRANDING_VIRTUAL_BACKGROUND = ("zoom", "zoom_web_in_ars_upload_branding_virtual_background", False)
    ZOOM_WEB_IN_ARS_DELETE_BRANDING_VIRTUAL_BACKGROUND = ("zoom", "zoom_web_in_ars_delete_branding_virtual_background", False)
    ZOOM_WEB_IN_ARS_SET_DEFAULT_BRANDING_VIRTUAL_BACKGROUND = ("zoom", "zoom_web_in_ars_set_default_branding_virtual_background", False)
    ZOOM_WEB_IN_ARS_UPLOAD_BRANDING_WALLPAPER = ("zoom", "zoom_web_in_ars_upload_branding_wallpaper", False)
    ZOOM_WEB_IN_ARS_DELETE_BRANDING_WALLPAPER = ("zoom", "zoom_web_in_ars_delete_branding_wallpaper", False)
    ZOOM_WEB_IN_ARS_CREATE_INVITE_LINKS = ("zoom", "zoom_web_in_ars_create_invite_links", False)
    ZOOM_WEB_IN_ARS_JOIN_TOKEN_LIVE_STREAMING = ("zoom", "zoom_web_in_ars_join_token_live_streaming", False)
    ZOOM_WEB_IN_ARS_GET_MEETING_ARCHIVE_TOKEN_FOR_LOCAL_ARCHIVING = ("zoom", "zoom_web_in_ars_get_meeting_archive_token_for_local_archiving", False)
    ZOOM_WEB_IN_ARS_GET_JOIN_TOKEN_LOCAL_RECORDING = ("zoom", "zoom_web_in_ars_get_join_token_local_recording", False)
    ZOOM_WEB_IN_ARS_GET_LIVE_STREAM_DETAILS = ("zoom", "zoom_web_in_ars_get_live_stream_details", False)
    ZOOM_WEB_IN_ARS_UPDATE_LIVE_STREAM = ("zoom", "zoom_web_in_ars_update_live_stream", False)
    ZOOM_WEB_IN_ARS_UPDATE_LIVE_STREAM_STATUS = ("zoom", "zoom_web_in_ars_update_live_stream_status", False)
    ZOOM_WEB_IN_ARS_LIST_PANELISTS = ("zoom", "zoom_web_in_ars_list_panelists", False)
    ZOOM_WEB_IN_ARS_ADD_PANELISTS = ("zoom", "zoom_web_in_ars_add_panelists", False)
    ZOOM_WEB_IN_ARS_REMOVE_PANELISTS = ("zoom", "zoom_web_in_ars_remove_panelists", False)
    ZOOM_WEB_IN_ARS_REMOVE_PANELIST = ("zoom", "zoom_web_in_ars_remove_panelist", False)
    ZOOM_WEB_IN_ARS_LIST_POLLS = ("zoom", "zoom_web_in_ars_list_polls", False)
    ZOOM_WEB_IN_ARS_CREATE_POLL = ("zoom", "zoom_web_in_ars_create_poll", False)
    ZOOM_WEB_IN_ARS_GET_POLL_DETAILS = ("zoom", "zoom_web_in_ars_get_poll_details", False)
    ZOOM_WEB_IN_ARS_UPDATE_POLL = ("zoom", "zoom_web_in_ars_update_poll", False)
    ZOOM_WEB_IN_ARS_DELETE_POLL = ("zoom", "zoom_web_in_ars_delete_poll", False)
    ZOOM_WEB_IN_ARS_LIST_REGISTRANTS = ("zoom", "zoom_web_in_ars_list_registrants", False)
    ZOOM_WEB_IN_ARS_ADD_REGISTRANT = ("zoom", "zoom_web_in_ars_add_registrant", False)
    ZOOM_WEB_IN_ARS_LIST_REGISTRATION_QUESTIONS = ("zoom", "zoom_web_in_ars_list_registration_questions", False)
    ZOOM_WEB_IN_ARS_UPDATE_REGISTRATION_QUESTIONS = ("zoom", "zoom_web_in_ars_update_registration_questions", False)
    ZOOM_WEB_IN_ARS_UPDATE_REGISTRANT_STATUS = ("zoom", "zoom_web_in_ars_update_registrant_status", False)
    ZOOM_WEB_IN_ARS_REGISTRANT_DETAILS = ("zoom", "zoom_web_in_ars_registrant_details", False)
    ZOOM_WEB_IN_ARS_DELETE_REGISTRANT = ("zoom", "zoom_web_in_ars_delete_registrant", False)
    ZOOM_WEB_IN_ARS_GETS_IP_URI_WITH_PASS_CODE = ("zoom", "zoom_web_in_ars_gets_ip_uri_with_pass_code", False)
    ZOOM_WEB_IN_ARS_UPDATE_STATUS = ("zoom", "zoom_web_in_ars_update_status", False)
    ZOOM_WEB_IN_ARS_GET_SURVEY = ("zoom", "zoom_web_in_ars_get_survey", False)
    ZOOM_WEB_IN_ARS_DELETE_SURVEY = ("zoom", "zoom_web_in_ars_delete_survey", False)
    ZOOM_WEB_IN_ARS_UPDATE_SURVEY = ("zoom", "zoom_web_in_ars_update_survey", False)
    ZOOM_WEB_IN_ARS_GET_WEB_IN_ART_OKEN = ("zoom", "zoom_web_in_ars_get_web_in_art_oken", False)
    ZOOM_WEB_IN_ARS_LIST_TRACKING_SOURCES = ("zoom", "zoom_web_in_ars_list_tracking_sources", False)

class Trigger(Enum):
    def __init__(self, service, trigger):
        self.service = service
        self.trigger = trigger

    GITHUB_PULL_REQUEST_EVENT = ("github", "github_pull_request_event")
    GITHUB_COMMIT_EVENT = ("github", "github_commit_event")
    SLACK_NEW_MESSAGE = ("slack", "slack_receive_message")
    SLACKBOT_NEW_MESSAGE = ("slackbot", "slackbot_receive_message")
