from enum import Enum

class Tag(Enum):
    IMPORTANT = "important"

class App(Enum):
    ALCHEMY = "alchemy"
    AMAZON = "amazon"
    AMCARDS = "amcards"
    AMPLITUDE = "amplitude"
    APIFY = "apify"
    APPDRAG = "appdrag"
    ASANA = "asana"
    ASHBY = "ashby"
    ATLASSIAN = "atlassian"
    ATTIO = "attio"
    AUTH0 = "auth0"
    AXONAUT = "axonaut"
    BAMBOOHR = "bamboohr"
    BANNERBEAR = "bannerbear"
    BASEROW = "baserow"
    BATTLENET = "battlenet"
    BEEMINDER = "beeminder"
    BITBUCKET = "bitbucket"
    BITWARDEN = "bitwarden"
    BLACKBAUD = "blackbaud"
    BOLDSIGN = "boldsign"
    BOX = "box"
    BRAINTREE = "braintree"
    BRANDFETCH = "brandfetch"
    BREVO = "brevo"
    BREX = "brex"
    BREX_STAGING = "brex-staging"
    BROWSEAI = "browseai"
    BROWSERHUB = "browserhub"
    BUBBLE = "bubble"
    CAL = "cal"
    ABLY = "ably"
    ACCELO = "accelo"
    ADOBE = "adobe"
    AERO_WORKFLOW = "aero-workflow"
    CALENDLY = "calendly"
    CHATWORK = "chatwork"
    CHMEETINGS = "chmeetings"
    CLICKUP = "clickup"
    CLOSE = "close"
    CODEINTERPRETER = "codeinterpreter"
    CONTENTFUL = "contentful"
    CUSTOMER_IO = "customer_io"
    DATADOG = "datadog"
    DATAGMA = "datagma"
    DEEL = "deel"
    DEMIO = "demio"
    DIGICERT = "digicert"
    DISCORD = "discord"
    DROPBOX = "dropbox"
    DROPBOX_SIGN = "dropbox-sign"
    ECHTPOST = "echtpost"
    EPIC_GAMES = "epic-games"
    EVENTBRITE = "eventbrite"
    EXA = "exa"
    EXIST = "exist"
    FACEBOOK = "facebook"
    FACTORIAL = "factorial"
    FIGMA = "figma"
    FILEMANAGER = "filemanager"
    FITBIT = "fitbit"
    FRESHBOOKS = "freshbooks"
    FRESHDESK = "freshdesk"
    FRONT = "front"
    GCALENDAR = "gcalendar"
    GITHUB = "github"
    GITLAB = "gitlab"
    GMAIL = "gmail"
    GOOGLE_DOCS = "google-docs"
    GOOGLE_DRIVE = "google-drive"
    GOOGLE_SHEETS = "google-sheets"
    GORGIAS = "gorgias"
    GUMROAD = "gumroad"
    GURU = "guru"
    HACKERRANK_WORK = "hackerrank-work"
    HARVEST = "harvest"
    HEROKU = "heroku"
    HIGHLEVEL = "highlevel"
    HUBSPOT = "hubspot"
    INTERCOM = "intercom"
    JIRA = "jira"
    KEAP = "keap"
    KLAVIYO = "klaviyo"
    KLIPFOLIO = "klipfolio"
    LASTPASS = "lastpass"
    LAUNCH_DARKLY = "launch-darkly"
    LEXOFFICE = "lexoffice"
    LINEAR = "linear"
    LINEARSANDBOX = "linearsandbox"
    LINKHUT = "linkhut"
    MAILCHIMP = "mailchimp"
    MAINTAINX = "maintainx"
    MICROSOFT_TEAMS = "microsoft-teams"
    MICROSOFT_TENANT = "microsoft-tenant"
    MIRO = "miro"
    MIXPANEL = "mixpanel"
    MONDAY = "monday"
    MOXIE = "moxie"
    MURAL = "mural"
    NETSUITE = "netsuite"
    NGROK = "ngrok"
    NOTION = "notion"
    OKTA = "okta"
    ONE_DRIVE = "one-drive"
    PAGERDUTY = "pagerduty"
    PANDADOC = "pandadoc"
    PIPEDRIVE = "pipedrive"
    PRINTNODE = "printnode"
    PROCESS_STREET = "process-street"
    RAVENSEOTOOLS = "ravenseotools"
    REDDIT = "reddit"
    RING_CENTRAL = "ring-central"
    SAGE = "sage"
    SALESFORCE = "salesforce"
    SERPAPI = "serpapi"
    SERVICEM8 = "servicem8"
    SHOPIFY = "shopify"
    SHORTCUT = "shortcut"
    SLACK = "slack"
    SLACKBOT = "slackbot"
    SMARTRECRUITERS = "smartrecruiters"
    SMUGMUG = "smugmug"
    SNOWFLAKE = "snowflake"
    SPLITWISE = "splitwise"
    SQUARE = "square"
    STACK_EXCHANGE = "stack-exchange"
    STRAVA = "strava"
    SURVEY_MONKEY = "survey-monkey"
    TAPFORM = "tapform"
    TASKADE = "taskade"
    TEXTRAZOR = "textrazor"
    TIMEKIT = "timekit"
    TIMELY = "timely"
    TINYPNG = "tinypng"
    TINYURL = "tinyurl"
    TODOIST = "todoist"
    TONEDEN = "toneden"
    TRELLO = "trello"
    TWITCH = "twitch"
    TWITTER = "twitter"
    TYPEFORM = "typeform"
    VENLY = "venly"
    WABOXAPP = "waboxapp"
    WAKATIME = "wakatime"
    WAVE_ACCOUNTING = "wave-accounting"
    WORKABLE = "workable"
    WORKSPACE = "workspace"
    XERO = "xero"
    YANDEX = "yandex"
    YOUTUBE = "youtube"
    ZENDESK = "zendesk"
    ZOHO = "zoho"
    ZOHO_BIGIN = "zoho-bigin"
    ZOHO_BOOKS = "zoho-books"
    ZOHO_DESK = "zoho-desk"
    ZOHO_INVENTORY = "zoho-inventory"
    ZOHO_INVOICE = "zoho-invoice"
    ZOHO_MAIL = "zoho-mail"
    ZOOM = "zoom"

class Action(Enum):
    def __init__(self, service, action, no_auth):
        self.service = service
        self.action = action
        self.no_auth = no_auth

    APIFY_LIST_APIFY_ACTORS = ("apify", "apify_list_apify_actors", False)
    APIFY_CREATE_APIFY_ACTOR = ("apify", "apify_create_apify_actor", False)
    APIFY_GET_ACTOR_ID = ("apify", "apify_get_actor_id", False)
    APIFY_SEARCH_STORE = ("apify", "apify_search_store", False)
    APIFY_GET_LAST_RUN_DATA = ("apify", "apify_get_last_run_data", False)
    APIFY_LIST_APIFY_TASKS = ("apify", "apify_list_apify_tasks", False)
    ASANA_ALLOCATIONS_GET_RECORD_BY_ID = ("asana", "asana_allocations_get_record_by_id", False)
    ASANA_ALLOCATIONS_DELETE_ALLOCATION_BY_ID = ("asana", "asana_allocations_delete_allocation_by_id", False)
    ASANA_ALLOCATIONS_GET_MULTIPLE = ("asana", "asana_allocations_get_multiple", False)
    ASANA_ATTACHMENTS_GET_ATTACHMENT_RECORD = ("asana", "asana_attachments_get_attachment_record", False)
    ASANA_ATTACHMENTS_DELETE_SPECIFIC = ("asana", "asana_attachments_delete_specific", False)
    ASANA_ATTACHMENTS_GET_ALL_FOR_OBJECT = ("asana", "asana_attachments_get_all_for_object", False)
    ASANA_ATTACHMENTS_UPLOAD_ATTACHMENT = ("asana", "asana_attachments_upload_attachment", False)
    ASANA_AUDIT_LOG_API_GET_AUDIT_LOG_EVENTS = ("asana", "asana_audit_log_api_get_audit_log_events", False)
    ASANA_BATCH_API_SUBMIT_PARALLEL_REQUESTS = ("asana", "asana_batch_api_submit_parallel_requests", False)
    ASANA_CUSTOM_FIELD_SETTINGS_GET_PROJECT_CUSTOM_FIELD_SETTINGS = ("asana", "asana_custom_field_settings_get_project_custom_field_settings", False)
    ASANA_CUSTOM_FIELD_SETTINGS_GET_PORTFOLIO_CUSTOM_FIELD_SETTINGS = ("asana", "asana_custom_field_settings_get_portfolio_custom_field_settings", False)
    ASANA_CUSTOM_FIELDS_GET_METADATA = ("asana", "asana_custom_fields_get_metadata", False)
    ASANA_CUSTOM_FIELDS_DELETE_FIELD_RECORD = ("asana", "asana_custom_fields_delete_field_record", False)
    ASANA_CUSTOM_FIELDS_LIST_WORK_SPACE_CUSTOM_FIELDS = ("asana", "asana_custom_fields_list_work_space_custom_fields", False)
    ASANA_CUSTOM_FIELDS_REORDERE_NUM_OPTION = ("asana", "asana_custom_fields_reordere_num_option", False)
    ASANA_CUSTOM_FIELDS_UPDATEE_NUM_OPTION = ("asana", "asana_custom_fields_updatee_num_option", False)
    ASANA_EVENTS_GET_RESOURCE_EVENTS = ("asana", "asana_events_get_resource_events", False)
    ASANA_GOAL_RELATIONSHIPS_GET_RECORD_BY_ID = ("asana", "asana_goal_relationships_get_record_by_id", False)
    ASANA_GOAL_RELATIONSHIPS_GET_COMPACT_RECORDS = ("asana", "asana_goal_relationships_get_compact_records", False)
    ASANA_GOAL_RELATIONSHIPS_CREATE_SUPPORTING_RELATIONSHIP = ("asana", "asana_goal_relationships_create_supporting_relationship", False)
    ASANA_GOAL_RELATIONSHIPS_REMOVE_SUPPORTING_RELATIONSHIP = ("asana", "asana_goal_relationships_remove_supporting_relationship", False)
    ASANA_GOALS_GET_GOAL_RECORD = ("asana", "asana_goals_get_goal_record", False)
    ASANA_GOALS_DELETE_RECORD = ("asana", "asana_goals_delete_record", False)
    ASANA_GOALS_GET_COMPACT_RECORDS = ("asana", "asana_goals_get_compact_records", False)
    ASANA_GOALS_CREATE_METRIC = ("asana", "asana_goals_create_metric", False)
    ASANA_GOALS_UPDATE_METRIC_CURRENT_VALUE = ("asana", "asana_goals_update_metric_current_value", False)
    ASANA_GOALS_ADD_COLLABORATORS_TO_GOAL = ("asana", "asana_goals_add_collaborators_to_goal", False)
    ASANA_GOALS_REMOVE_FOLLOWERS_FROM_GOAL = ("asana", "asana_goals_remove_followers_from_goal", False)
    ASANA_GOALS_GET_PARENT_GOALS = ("asana", "asana_goals_get_parent_goals", False)
    ASANA_JOBS_GET_BY_ID = ("asana", "asana_jobs_get_by_id", False)
    ASANA_MEMBERSHIPS_GET_MULTIPLE = ("asana", "asana_memberships_get_multiple", False)
    ASANA_MEMBERSHIPS_CREATE_NEW_RECORD = ("asana", "asana_memberships_create_new_record", False)
    ASANA_MEMBERSHIPS_GET_MEMBERSHIP_RECORD = ("asana", "asana_memberships_get_membership_record", False)
    ASANA_MEMBERSHIPS_UPDATE_MEMBERSHIP_RECORD = ("asana", "asana_memberships_update_membership_record", False)
    ASANA_MEMBERSHIPS_DELETE_RECORD = ("asana", "asana_memberships_delete_record", False)
    ASANA_ORGANIZATION_EXPORTS_CREATE_EXPORT_REQUEST = ("asana", "asana_organization_exports_create_export_request", False)
    ASANA_ORGANIZATION_EXPORTS_GET_EXPORT_DETAILS = ("asana", "asana_organization_exports_get_export_details", False)
    ASANA_PORTFOLIO_MEMBERSHIPS_LIST_MULTIPLE_MEMBERSHIPS = ("asana", "asana_portfolio_memberships_list_multiple_memberships", False)
    ASANA_PORTFOLIO_MEMBERSHIPS_GET_COMPLETE_RECORD = ("asana", "asana_portfolio_memberships_get_complete_record", False)
    ASANA_PORTFOLIO_MEMBERSHIPS_GET_COMPACT = ("asana", "asana_portfolio_memberships_get_compact", False)
    ASANA_PORTFOLIOS_LIST_MULTIPLE_PORTFOLIOS = ("asana", "asana_portfolios_list_multiple_portfolios", False)
    ASANA_PORTFOLIOS_GET_RECORD = ("asana", "asana_portfolios_get_record", False)
    ASANA_PORTFOLIOS_DELETE_RECORD = ("asana", "asana_portfolios_delete_record", False)
    ASANA_PORTFOLIOS_GET_ITEMS = ("asana", "asana_portfolios_get_items", False)
    ASANA_PORTFOLIOS_ADD_PORTFOLIO_ITEM = ("asana", "asana_portfolios_add_portfolio_item", False)
    ASANA_PORTFOLIOS_REMOVE_ITEM_FROM_PORTFOLIO = ("asana", "asana_portfolios_remove_item_from_portfolio", False)
    ASANA_PORTFOLIOS_ADD_CUSTOM_FIELD_SETTING = ("asana", "asana_portfolios_add_custom_field_setting", False)
    ASANA_PORTFOLIOS_REMOVE_CUSTOM_FIELD_SETTING = ("asana", "asana_portfolios_remove_custom_field_setting", False)
    ASANA_PORTFOLIOS_ADD_MEMBERS_TO_PORTFOLIO = ("asana", "asana_portfolios_add_members_to_portfolio", False)
    ASANA_PORTFOLIOS_REMOVE_MEMBERS_FROM_PORTFOLIO = ("asana", "asana_portfolios_remove_members_from_portfolio", False)
    ASANA_PROJECT_BRIEFS_GET_FULL_RECORD = ("asana", "asana_project_briefs_get_full_record", False)
    ASANA_PROJECT_BRIEFS_REMOVE_BRIEF = ("asana", "asana_project_briefs_remove_brief", False)
    ASANA_PROJECT_MEMBERSHIPS_GET_RECORD = ("asana", "asana_project_memberships_get_record", False)
    ASANA_PROJECT_MEMBERSHIPS_GET_COMPACT_RECORDS = ("asana", "asana_project_memberships_get_compact_records", False)
    ASANA_PROJECT_STATUSES_GET_STATUS_UPDATE_RECORD = ("asana", "asana_project_statuses_get_status_update_record", False)
    ASANA_PROJECT_STATUSES_DELETE_SPECIFIC_STATUS_UPDATE = ("asana", "asana_project_statuses_delete_specific_status_update", False)
    ASANA_PROJECT_STATUSES_GET_PROJECT_UPDATES = ("asana", "asana_project_statuses_get_project_updates", False)
    ASANA_PROJECT_TEMPLATES_GET_RECORD = ("asana", "asana_project_templates_get_record", False)
    ASANA_PROJECT_TEMPLATES_DELETE_TEMPLATE_RECORD = ("asana", "asana_project_templates_delete_template_record", False)
    ASANA_PROJECT_TEMPLATES_LIST_MULTIPLE = ("asana", "asana_project_templates_list_multiple", False)
    ASANA_PROJECT_TEMPLATES_GET_ALL_TEMPLATE_RECORDS = ("asana", "asana_project_templates_get_all_template_records", False)
    ASANA_PROJECT_TEMPLATES_INSTANTIATE_PROJECT_JOB = ("asana", "asana_project_templates_instantiate_project_job", False)
    ASANA_PROJECTS_LIST_MULTIPLE = ("asana", "asana_projects_list_multiple", False)
    ASANA_PROJECTS_GET_PROJECT_RECORD = ("asana", "asana_projects_get_project_record", False)
    ASANA_PROJECTS_DELETE_PROJECT_BY_ID = ("asana", "asana_projects_delete_project_by_id", False)
    ASANA_PROJECTS_DUPLICATE_PROJECT_JOB = ("asana", "asana_projects_duplicate_project_job", False)
    ASANA_PROJECTS_TASK_PROJECTS_LIST = ("asana", "asana_projects_task_projects_list", False)
    ASANA_PROJECTS_GET_TEAM_PROJECTS = ("asana", "asana_projects_get_team_projects", False)
    ASANA_PROJECTS_GET_ALL_IN_WORK_SPACE = ("asana", "asana_projects_get_all_in_work_space", False)
    ASANA_PROJECTS_ADD_CUSTOM_FIELD_SETTING = ("asana", "asana_projects_add_custom_field_setting", False)
    ASANA_PROJECTS_REMOVE_CUSTOM_FIELD = ("asana", "asana_projects_remove_custom_field", False)
    ASANA_PROJECTS_GET_TASK_COUNTS = ("asana", "asana_projects_get_task_counts", False)
    ASANA_PROJECTS_ADD_MEMBERS_TO_PROJECT = ("asana", "asana_projects_add_members_to_project", False)
    ASANA_PROJECTS_REMOVE_MEMBERS_FROM_PROJECT = ("asana", "asana_projects_remove_members_from_project", False)
    ASANA_PROJECTS_ADD_FOLLOWERS_TO_PROJECT = ("asana", "asana_projects_add_followers_to_project", False)
    ASANA_PROJECTS_REMOVE_PROJECT_FOLLOWERS = ("asana", "asana_projects_remove_project_followers", False)
    ASANA_PROJECTS_CREATE_PROJECT_TEMPLATE_JOB = ("asana", "asana_projects_create_project_template_job", False)
    ASANA_RULES_TRIGGER_RULE_REQUEST = ("asana", "asana_rules_trigger_rule_request", False)
    ASANA_SECTIONS_GET_RECORD = ("asana", "asana_sections_get_record", False)
    ASANA_SECTIONS_UPDATE_SECTION_RECORD = ("asana", "asana_sections_update_section_record", False)
    ASANA_SECTIONS_DELETE_SECTION = ("asana", "asana_sections_delete_section", False)
    ASANA_SECTIONS_LIST_PROJECT_SECTIONS = ("asana", "asana_sections_list_project_sections", False)
    ASANA_SECTIONS_CREATE_NEW_SECTION = ("asana", "asana_sections_create_new_section", False)
    ASANA_SECTIONS_ADD_TASK_TO_SECTION = ("asana", "asana_sections_add_task_to_section", False)
    ASANA_SECTIONS_MOVE_OR_INSERT = ("asana", "asana_sections_move_or_insert", False)
    ASANA_STATUS_UPDATES_GET_RECORD_BY_ID = ("asana", "asana_status_updates_get_record_by_id", False)
    ASANA_STATUS_UPDATES_DELETE_SPECIFIC_STATUS_UPDATE = ("asana", "asana_status_updates_delete_specific_status_update", False)
    ASANA_STATUS_UPDATES_GET_COMPACT_RECORDS = ("asana", "asana_status_updates_get_compact_records", False)
    ASANA_STORIES_GET_FULL_RECORD = ("asana", "asana_stories_get_full_record", False)
    ASANA_STORIES_UPDATE_FULL_RECORD = ("asana", "asana_stories_update_full_record", False)
    ASANA_STORIES_DELETE_STORY_RECORD = ("asana", "asana_stories_delete_story_record", False)
    ASANA_STORIES_GET_TASK_STORIES = ("asana", "asana_stories_get_task_stories", False)
    ASANA_STORIES_CREATE_COMMENT = ("asana", "asana_stories_create_comment", False)
    ASANA_TAGS_LIST_FILTERED_TAGS = ("asana", "asana_tags_list_filtered_tags", False)
    ASANA_TAGS_GET_RECORD = ("asana", "asana_tags_get_record", False)
    ASANA_TAGS_UPDATE_TAG_RECORD = ("asana", "asana_tags_update_tag_record", False)
    ASANA_TAGS_REMOVE_TAG = ("asana", "asana_tags_remove_tag", False)
    ASANA_TAGS_GET_TASK_TAGS = ("asana", "asana_tags_get_task_tags", False)
    ASANA_TAGS_GET_FILTERED_TAGS = ("asana", "asana_tags_get_filtered_tags", False)
    ASANA_TASK_TEMPLATES_LIST_MULTIPLE = ("asana", "asana_task_templates_list_multiple", False)
    ASANA_TASK_TEMPLATES_GET_SINGLE_TEMPLATE = ("asana", "asana_task_templates_get_single_template", False)
    ASANA_TASK_TEMPLATES_DELETE_TASK_TEMPLATE = ("asana", "asana_task_templates_delete_task_template", False)
    ASANA_TASK_TEMPLATES_INSTANTIATE_TASK_JOB = ("asana", "asana_task_templates_instantiate_task_job", False)
    ASANA_TASKS_GET_MULTIPLE = ("asana", "asana_tasks_get_multiple", False)
    ASANA_TASKS_GET_TASK_RECORD = ("asana", "asana_tasks_get_task_record", False)
    ASANA_TASKS_DELETE_TASK = ("asana", "asana_tasks_delete_task", False)
    ASANA_TASKS_DUPLICATE_TASK_JOB = ("asana", "asana_tasks_duplicate_task_job", False)
    ASANA_TASKS_GET_TASKS_BY_PROJECT = ("asana", "asana_tasks_get_tasks_by_project", False)
    ASANA_TASKS_GET_SECTION_TASKS = ("asana", "asana_tasks_get_section_tasks", False)
    ASANA_TASKS_GET_MULTIPLE_WITH_TAG = ("asana", "asana_tasks_get_multiple_with_tag", False)
    ASANA_TASKS_GET_USER_TASK_LIST_TASKS = ("asana", "asana_tasks_get_user_task_list_tasks", False)
    ASANA_TASKS_GET_SUB_TASK_LIST = ("asana", "asana_tasks_get_sub_task_list", False)
    ASANA_TASKS_SET_PARENT_TASK = ("asana", "asana_tasks_set_parent_task", False)
    ASANA_TASKS_GET_ALL_DEPENDENCIES = ("asana", "asana_tasks_get_all_dependencies", False)
    ASANA_TASKS_SET_DEPENDENCIES_FOR_TASK = ("asana", "asana_tasks_set_dependencies_for_task", False)
    ASANA_TASK_SUN_LINK_DEPENDENCIES_FROM_TASK = ("asana", "asana_task_sun_link_dependencies_from_task", False)
    ASANA_TASKS_GET_DEPENDENTS = ("asana", "asana_tasks_get_dependents", False)
    ASANA_TASKS_SET_TASK_DEPENDENTS = ("asana", "asana_tasks_set_task_dependents", False)
    ASANA_TASK_SUN_LINK_DEPENDENTS = ("asana", "asana_task_sun_link_dependents", False)
    ASANA_TASKS_ADD_PROJECT_TO_TASK = ("asana", "asana_tasks_add_project_to_task", False)
    ASANA_TASKS_REMOVE_PROJECT_FROM_TASK = ("asana", "asana_tasks_remove_project_from_task", False)
    ASANA_TASKS_ADD_TAG_TO_TASK = ("asana", "asana_tasks_add_tag_to_task", False)
    ASANA_TASKS_REMOVE_TAG_FROM_TASK = ("asana", "asana_tasks_remove_tag_from_task", False)
    ASANA_TASKS_ADD_FOLLOWERS_TO_TASK = ("asana", "asana_tasks_add_followers_to_task", False)
    ASANA_TASKS_REMOVE_FOLLOWERS_FROM_TASK = ("asana", "asana_tasks_remove_followers_from_task", False)
    ASANA_TASKS_GET_BY_CUSTOM_ID = ("asana", "asana_tasks_get_by_custom_id", False)
    ASANA_TASKS_SEARCH_IN_WORK_SPACE = ("asana", "asana_tasks_search_in_work_space", False)
    ASANA_TEAM_MEMBERSHIPS_GET_RECORD_BY_ID = ("asana", "asana_team_memberships_get_record_by_id", False)
    ASANA_TEAM_MEMBERSHIPS_GET_COMPACT_RECORDS = ("asana", "asana_team_memberships_get_compact_records", False)
    ASANA_TEAM_MEMBERSHIPS_GET_COMPACT = ("asana", "asana_team_memberships_get_compact", False)
    ASANA_TEAM_MEMBERSHIPS_GET_USER_COMPACT = ("asana", "asana_team_memberships_get_user_compact", False)
    ASANA_TEAMS_GET_TEAM_RECORD = ("asana", "asana_teams_get_team_record", False)
    ASANA_TEAMS_LIST_WORK_SPACE_TEAMS = ("asana", "asana_teams_list_work_space_teams", False)
    ASANA_TEAMS_GET_USER_TEAMS = ("asana", "asana_teams_get_user_teams", False)
    ASANA_TEAMS_ADD_USER_TO_TEAM = ("asana", "asana_teams_add_user_to_team", False)
    ASANA_TEAMS_REMOVE_USER_FROM_TEAM = ("asana", "asana_teams_remove_user_from_team", False)
    ASANA_TIME_PERIODS_GET_FULL_RECORD = ("asana", "asana_time_periods_get_full_record", False)
    ASANA_TIME_PERIODS_GET_COMPACT_TIME_PERIODS = ("asana", "asana_time_periods_get_compact_time_periods", False)
    ASANA_TIME_TRACKING_ENTRIES_GET_FOR_TASK = ("asana", "asana_time_tracking_entries_get_for_task", False)
    ASANA_TIME_TRACKING_ENTRIES_CREATE_NEW_TIME_ENTRY_RECORD = ("asana", "asana_time_tracking_entries_create_new_time_entry_record", False)
    ASANA_TIME_TRACKING_ENTRIES_GET_RECORD = ("asana", "asana_time_tracking_entries_get_record", False)
    ASANA_TIME_TRACKING_ENTRIES_UPDATE_TIME_TRACKING_ENTRY = ("asana", "asana_time_tracking_entries_update_time_tracking_entry", False)
    ASANA_TIME_TRACKING_ENTRIES_DELETE_TIME_ENTRY = ("asana", "asana_time_tracking_entries_delete_time_entry", False)
    ASANA_TYPE_AHEAD_GET_RESULTS = ("asana", "asana_type_ahead_get_results", False)
    ASANA_USER_TASK_LISTS_GET_RECORD = ("asana", "asana_user_task_lists_get_record", False)
    ASANA_USER_TASK_LISTS_GET_USER_TASK_LIST = ("asana", "asana_user_task_lists_get_user_task_list", False)
    ASANA_USERS_LIST_MULTIPLE_USERS = ("asana", "asana_users_list_multiple_users", False)
    ASANA_USERS_GET_USER_RECORD = ("asana", "asana_users_get_user_record", False)
    ASANA_USERS_GET_FAVORITES_FOR_USER = ("asana", "asana_users_get_favorites_for_user", False)
    ASANA_USERS_LIST_TEAM_USERS = ("asana", "asana_users_list_team_users", False)
    ASANA_USERS_LIST_WORK_SPACE_USERS = ("asana", "asana_users_list_work_space_users", False)
    ASANA_WEB_HOOKS_LIST_MULTIPLE_WEB_HOOKS = ("asana", "asana_web_hooks_list_multiple_web_hooks", False)
    ASANA_WEB_HOOKS_ESTABLISH_WEB_HOOK = ("asana", "asana_web_hooks_establish_web_hook", False)
    ASANA_WEB_HOOKS_GET_WEB_HOOK_RECORD = ("asana", "asana_web_hooks_get_web_hook_record", False)
    ASANA_WEB_HOOKS_UPDATE_WEB_HOOK_FILTERS = ("asana", "asana_web_hooks_update_web_hook_filters", False)
    ASANA_WEB_HOOKS_REMOVE_WEB_HOOK = ("asana", "asana_web_hooks_remove_web_hook", False)
    ASANA_WORK_SPACE_MEMBERSHIPS_GET_RECORD_BY_ID = ("asana", "asana_work_space_memberships_get_record_by_id", False)
    ASANA_WORK_SPACE_MEMBERSHIPS_GET_USER_MEMBERSHIPS = ("asana", "asana_work_space_memberships_get_user_memberships", False)
    ASANA_WORK_SPACE_MEMBERSHIPS_LIST_FOR_WORK_SPACE = ("asana", "asana_work_space_memberships_list_for_work_space", False)
    ASANA_WORK_SPACES_LIST_MULTIPLE = ("asana", "asana_work_spaces_list_multiple", False)
    ASANA_WORK_SPACES_GET_WORK_SPACE_RECORD = ("asana", "asana_work_spaces_get_work_space_record", False)
    ASANA_WORK_SPACES_UPDATE_WORK_SPACE_RECORD = ("asana", "asana_work_spaces_update_work_space_record", False)
    ASANA_WORK_SPACES_ADD_USER_TO_WORK_SPACE = ("asana", "asana_work_spaces_add_user_to_work_space", False)
    ASANA_WORK_SPACES_REMOVE_USER_FROM_WORK_SPACE = ("asana", "asana_work_spaces_remove_user_from_work_space", False)
    CLICKUP_CREATE_TASK = ("clickup", "clickup_create_task", False)
    CLICKUP_GET_TASKS = ("clickup", "clickup_get_tasks", False)
    CLICKUP_GET_TASK = ("clickup", "clickup_get_task", False)
    CLICKUP_CREATE_LIST = ("clickup", "clickup_create_list", False)
    CLICKUP_GET_LISTS = ("clickup", "clickup_get_lists", False)
    CLICKUP_GET_SPACES = ("clickup", "clickup_get_spaces", False)
    CLICKUP_CREATE_SPACE = ("clickup", "clickup_create_space", False)
    CLICKUP_CREATE_FOLDER = ("clickup", "clickup_create_folder", False)
    CLICKUP_GET_FOLDERS = ("clickup", "clickup_get_folders", False)
    CODEINTERPRETER_EXECUTE_CODE = ("codeinterpreter", "codeinterpreter_execute_code", True)
    DROPBOX_GET_ABOUT_ME = ("dropbox", "dropbox_get_about_me", False)
    EXA_SEARCH = ("exa", "exa_search", True)
    EXA_SIMILARLINK = ("exa", "exa_similarlink", True)
    FILEMANAGER_CREATE_SHELL_ACTION = ("filemanager", "filemanager_create_shell_action", True)
    FILEMANAGER_CLOSE_SHELL_ACTION = ("filemanager", "filemanager_close_shell_action", True)
    FILEMANAGER_RUN_COMMAND_ACTION = ("filemanager", "filemanager_run_command_action", True)
    FILEMANAGER_SET_ENV_VAR_ACTION = ("filemanager", "filemanager_set_env_var_action", True)
    FILEMANAGER_OPEN_FILE_ACTION = ("filemanager", "filemanager_open_file_action", True)
    FILEMANAGER_GOTO_LINE_ACTION = ("filemanager", "filemanager_goto_line_action", True)
    FILEMANAGER_SCROLL_ACTION = ("filemanager", "filemanager_scroll_action", True)
    FILEMANAGER_CREATE_FILE_ACTION = ("filemanager", "filemanager_create_file_action", True)
    FILEMANAGER_EDIT_FILE_ACTION = ("filemanager", "filemanager_edit_file_action", True)
    GOOGLECALENDAR_CREATE_GOOGLE_EVENT = ("gcalendar", "googlecalendar_create_google_event", False)
    GOOGLECALENDAR_REMOVE_ATTENDEE = ("gcalendar", "googlecalendar_remove_attendee", False)
    GOOGLECALENDAR_FIND_EVENT = ("gcalendar", "googlecalendar_find_event", False)
    GOOGLECALENDAR_DELETE_GOOGLE_EVENT = ("gcalendar", "googlecalendar_delete_google_event", False)
    GOOGLECALENDAR_UPDATE_GOOGLE_EVENT = ("gcalendar", "googlecalendar_update_google_event", False)
    GOOGLECALENDAR_FIND_FREE_SLOTS = ("gcalendar", "googlecalendar_find_free_slots", False)
    GOOGLECALENDAR_DUPLICATE_GOOGLE_CALENDAR = ("gcalendar", "googlecalendar_duplicate_google_calendar", False)
    GOOGLECALENDAR_LIST_GOOGLE_CALENDARS = ("gcalendar", "googlecalendar_list_google_calendars", False)
    GOOGLECALENDAR_PATCH_GOOGLE_CALENDAR = ("gcalendar", "googlecalendar_patch_google_calendar", False)
    GOOGLECALENDAR_QUICK_ADD_GOOGLE_CALENDAR = ("gcalendar", "googlecalendar_quick_add_google_calendar", False)
    GOOGLECALENDAR_GET_CURRENT_DATE_TIME = ("gcalendar", "googlecalendar_get_current_date_time", False)
    GITHUB_CREATE_ISSUE = ("github", "github_create_issue", False)
    GITHUB_LIST_GITHUB_REPOS = ("github", "github_list_github_repos", False)
    GITHUB_STAR_REPO = ("github", "github_star_repo", False)
    GITHUB_GET_ABOUT_ME = ("github", "github_get_about_me", False)
    GITHUB_FETCH_README = ("github", "github_fetch_readme", False)
    GITHUB_GET_COMMITS = ("github", "github_get_commits", False)
    GITHUB_GET_COMMITS_WITH_CODE = ("github", "github_get_commits_with_code", False)
    GITHUB_GET_PATCH_FOR_COMMIT = ("github", "github_get_patch_for_commit", False)
    GMAIL_SEND_EMAIL = ("gmail", "gmail_send_email", False)
    GMAIL_CREATE_EMAIL_DRAFT = ("gmail", "gmail_create_email_draft", False)
    GMAIL_FIND_EMAIL_ID = ("gmail", "gmail_find_email_id", False)
    GMAIL_FETCH_LAST_THREE_MESSAGES = ("gmail", "gmail_fetch_last_three_messages", False)
    GMAIL_ADD_LABEL_TO_EMAIL = ("gmail", "gmail_add_label_to_email", False)
    GMAIL_LIST_LABELS = ("gmail", "gmail_list_labels", False)
    GMAIL_FETCH_MESSAGE_BY_THREAD_ID = ("gmail", "gmail_fetch_message_by_thread_id", False)
    GMAIL_REPLY_TO_THREAD = ("gmail", "gmail_reply_to_thread", False)
    GMAIL_FETCH_EMAILS_WITH_LABEL = ("gmail", "gmail_fetch_emails_with_label", False)
    LINEAR_CREATE_LINEAR_ISSUE = ("linear", "linear_create_linear_issue", False)
    LINEAR_LIST_LINEAR_PROJECTS = ("linear", "linear_list_linear_projects", False)
    LINEAR_LIST_LINEAR_TEAMS = ("linear", "linear_list_linear_teams", False)
    NOTION_GET_ABOUT_ME = ("notion", "notion_get_about_me", False)
    NOTION_ADD_NOTION_PAGE_CHILDREN = ("notion", "notion_add_notion_page_children", False)
    NOTION_ARCHIVE_NOTION_PAGE = ("notion", "notion_archive_notion_page", False)
    NOTION_CREATE_NOTION_DATABASE = ("notion", "notion_create_notion_database", False)
    NOTION_CREATE_PAGE_COMMENT = ("notion", "notion_create_page_comment", False)
    NOTION_CREATE_NOTION_PAGE = ("notion", "notion_create_notion_page", False)
    NOTION_DELETE_NOTION_PAGE_CHILDREN = ("notion", "notion_delete_notion_page_children", False)
    NOTION_FETCH_NOTION_COMMENT = ("notion", "notion_fetch_notion_comment", False)
    NOTION_FETCH_NOTION_DATABASE = ("notion", "notion_fetch_notion_database", False)
    NOTION_FETCH_NOTION_PAGE = ("notion", "notion_fetch_notion_page", False)
    NOTION_SEARCH_NOTION_PAGE = ("notion", "notion_search_notion_page", False)
    NOTION_UPDATE_NOTION_DATABASE = ("notion", "notion_update_notion_database", False)
    NOTION_FETCH_NOTION_BLOCK = ("notion", "notion_fetch_notion_block", False)
    NOTION_FETCH_NOTION_CHILD_BLOCK = ("notion", "notion_fetch_notion_child_block", False)
    SERPAPI_SEARCH = ("serpapi", "serpapi_search", True)
    SLACK_SEND_SLACK_MESSAGE = ("slack", "slack_send_slack_message", False)
    SLACK_LIST_SLACK_CHANNELS = ("slack", "slack_list_slack_channels", False)
    SLACK_LIST_SLACK_MEMBERS = ("slack", "slack_list_slack_members", False)
    SLACK_LIST_SLACK_MESSAGES = ("slack", "slack_list_slack_messages", False)
    SLACKBOT_SEND_SLACK_MESSAGE = ("slackbot", "slackbot_send_slack_message", False)
    SLACKBOT_LIST_SLACK_CHANNELS = ("slackbot", "slackbot_list_slack_channels", False)
    SLACKBOT_LIST_SLACK_MEMBERS = ("slackbot", "slackbot_list_slack_members", False)
    SLACKBOT_LIST_SLACK_MESSAGES = ("slackbot", "slackbot_list_slack_messages", False)
    SNOWFLAKE_RUN_QUERY = ("snowflake", "snowflake_run_query", False)
    SNOWFLAKE_SHOW_TABLES = ("snowflake", "snowflake_show_tables", False)
    SNOWFLAKE_DESCRIBE_TABLE = ("snowflake", "snowflake_describe_table", False)
    SNOWFLAKE_EXPLORE_COLUMNS = ("snowflake", "snowflake_explore_columns", False)
    TRELLO_CREATE_TRELLO_LIST = ("trello", "trello_create_trello_list", False)
    TRELLO_CREATE_TRELLO_CARD = ("trello", "trello_create_trello_card", False)
    TRELLO_GET_TRELLO_BOARD_CARDS = ("trello", "trello_get_trello_board_cards", False)
    TRELLO_DELETE_TRELLO_CARD = ("trello", "trello_delete_trello_card", False)
    TRELLO_ADD_TRELLO_CARD_COMMENT = ("trello", "trello_add_trello_card_comment", False)
    TRELLO_CREATE_TRELLO_LABEL = ("trello", "trello_create_trello_label", False)
    TRELLO_UPDATE_TRELLO_BOARD = ("trello", "trello_update_trello_board", False)
    TRELLO_GET_ABOUT_ME = ("trello", "trello_get_about_me", False)
    TRELLO_SEARCH_TRELLO = ("trello", "trello_search_trello", False)
    TRELLO_SEARCH_TRELLO_MEMBER = ("trello", "trello_search_trello_member", False)
    TRELLO_UPDATE_TRELLO_CARD = ("trello", "trello_update_trello_card", False)
    TRELLO_GET_TRELLO_MEMBER_BOARD = ("trello", "trello_get_trello_member_board", False)
    TYPEFORM_GET_ABOUT_ME = ("typeform", "typeform_get_about_me", False)
    ZENDESK_CREATE_ZENDESK_ORGANIZATION = ("zendesk", "zendesk_create_zendesk_organization", False)
    ZENDESK_DELETE_ZENDESK_ORGANIZATION = ("zendesk", "zendesk_delete_zendesk_organization", False)
    ZENDESK_COUNT_ZENDESK_ORGANIZATIONS = ("zendesk", "zendesk_count_zendesk_organizations", False)
    ZENDESK_GET_ZENDESK_ORGANIZATION = ("zendesk", "zendesk_get_zendesk_organization", False)
    ZENDESK_GET_ALL_ZENDESK_ORGANIZATIONS = ("zendesk", "zendesk_get_all_zendesk_organizations", False)
    ZENDESK_UPDATE_ZENDESK_ORGANIZATION = ("zendesk", "zendesk_update_zendesk_organization", False)
    ZENDESK_CREATE_ZENDESK_TICKET = ("zendesk", "zendesk_create_zendesk_ticket", False)
    ZENDESK_DELETE_ZENDESK_TICKET = ("zendesk", "zendesk_delete_zendesk_ticket", False)
    ZENDESK_GET_ABOUT_ME = ("zendesk", "zendesk_get_about_me", False)

class Trigger(Enum):
    def __init__(self, service, trigger):
        self.service = service
        self.trigger = trigger

    GITHUB_PULL_REQUEST_EVENT = ("github", "github_pull_request_event")
    GITHUB_COMMIT_EVENT = ("github", "github_commit_event")
    SLACK_NEW_MESSAGE = ("slack", "slack_receive_message")
    SLACKBOT_NEW_MESSAGE = ("slackbot", "slackbot_receive_message")
