/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Sort the actions by usage or alphabetical
 */
export declare type ActionsListActionsMinimalV2RequestSortBy = "alphabet" | "usage" | "no_sort";
export declare const ActionsListActionsMinimalV2RequestSortBy: {
    readonly Alphabet: "alphabet";
    readonly Usage: "usage";
    readonly NoSort: "no_sort";
};
