import { join } from 'path';
import { createOpenAPI } from 'fumadocs-openapi/server';

// Versioned OpenAPI specs (generated by scripts/fetch-openapi.mjs)
// v3 spec contains /api/v3/* endpoints, v3.1 spec contains /api/v3.1/* endpoints
export const openapiV3 = createOpenAPI({
  input: [join(process.cwd(), 'public/openapi-v3.json')],
  proxyUrl: '/api/proxy',
});

export const openapiV31 = createOpenAPI({
  input: [join(process.cwd(), 'public/openapi-v3.1.json')],
  proxyUrl: '/api/proxy',
});

// Combined instance that knows about all spec files (needed by APIPage renderer and proxy)
export const openapi = createOpenAPI({
  input: [
    join(process.cwd(), 'public/openapi.json'),
    join(process.cwd(), 'public/openapi-v3.json'),
    join(process.cwd(), 'public/openapi-v3.1.json'),
  ],
  proxyUrl: '/api/proxy',
});
