/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as ComposioApi from "../../../../api/index";
import * as core from "../../../../core";
export declare const AppsGetAppsRequestSortBy: core.serialization.Schema<serializers.AppsGetAppsRequestSortBy.Raw, ComposioApi.AppsGetAppsRequestSortBy>;
export declare namespace AppsGetAppsRequestSortBy {
    type Raw = "alphabet" | "usage" | "no_sort";
}
