/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../index";
import * as ComposioApi from "../../../../../api/index";
import * as core from "../../../../../core";
export declare const WehbookNewFormatDto: core.serialization.Schema<serializers.WehbookNewFormatDto.Raw, ComposioApi.WehbookNewFormatDto>;
export declare namespace WehbookNewFormatDto {
    interface Raw {
        id: string;
        isNewWebhook: boolean;
    }
}
