/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as ComposioApi from "../../../../index";
/**
 * @example
 *     {}
 */
export interface ActionsListActionsMinimalV2Request {
    apps?: string;
    actions?: string;
    tags?: string;
    useCase?: string;
    page?: number;
    limit?: number;
    filterImportantActions?: boolean;
    sortBy?: ComposioApi.ActionsListActionsMinimalV2RequestSortBy;
}
