/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {
 *         text: "text"
 *     }
 */
export interface ActionGetNlaInputsReqDto {
    /** The use-case description for the action, this will give context to LLM to generate the correct inputs for the action. */
    text: string;
    /** The custom description for the action, use this to provide customised context about the action to the LLM to suit your use-case. */
    customDescription?: string;
    /** The system prompt to be used by LLM, use this to control and guide the behaviour of the LLM. */
    systemPrompt?: string;
}
