/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {}
 */
export interface ActionsListActionsV2Request {
    appNames?: string;
    useCase?: string;
    showEnabledOnly?: boolean;
    limit?: number;
    apps?: string;
    actions?: string;
    tags?: string;
    usecaseLimit?: number;
    filterImportantActions?: boolean;
    showAll?: boolean;
    page?: number;
}
