/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as ComposioApi from "../../../../index";
/**
 * @example
 *     {
 *         connectedAccountId: "connectedAccountId",
 *         endpoint: "endpoint",
 *         method: ComposioApi.ActionProxyRequestConfigDtoMethod.Get,
 *         parameters: [{
 *                 name: "name",
 *                 in: ComposioApi.ParameterIn.Query,
 *                 value: "value"
 *             }]
 *     }
 */
export interface ActionProxyRequestConfigDto {
    /** The connected account uuid to use for the action. */
    connectedAccountId: string;
    /** The endpoint to call for the action. If the given url is relative, it will be resolved relative to the base_url set in the connected account info. */
    endpoint: string;
    /** The HTTP method to use for the action. */
    method: ComposioApi.ActionProxyRequestConfigDtoMethod;
    parameters: ComposioApi.Parameter[];
    /** The body to be sent to the endpoint. This can either be a JSON field or a string. */
    body?: Record<string, unknown>;
}
