FROM python:slim

# Install dependencies
RUN apt update \
    && apt install  -y \
    git \
    curl \
    sudo \
    python3-dev \
    python3-pip \
    python3-venv \
    uuid-runtime \
    openssh-server

# Define entry point
COPY entrypoint.sh /root/entrypoint.sh

# Set working dir
WORKDIR /root

# Copy source
COPY ./composio /root/composio

# Install from source
RUN /bin/python3 -m pip install /root/composio/

# Remove cache
RUN rm -rf /root/composio/

# Run entrypoint.sh
ENTRYPOINT [ "/root/entrypoint.sh" ]
