FROM python:slim

# Install dependencies
RUN apt update \
    && apt install  -y \
    git \
    curl \
    sudo \
    python3-dev \
    python3-pip \
    python3-venv \
    uuid-runtime \
    openssh-server

# Create Venv
RUN /bin/python3 -m venv .composio/venv

# Setup path
RUN export PATH=$PATH:$(pwd)/.composio/venv/bin

# Install composio for dependency caching
RUN python -m pip install composio-core[all]==0.5.17 fastapi playwright uvicorn

RUN python -m pip install tree_sitter==0.21.3
RUN python -m pip install deeplake
RUN python -m pip install sentence-transformers
RUN python -m pip install tree_sitter_languages
RUN python -m pip install git+https://github.com/DataDog/jedi.git@92d0c807b0dcd115b1ffd0a4ed21e44db127c2fb#egg=jedi

# Install playwright deps
RUN playwright install-deps

# Install playwright binaries
RUN playwright install chromium

# Set working dir
WORKDIR /root

# Copy source
COPY ./composio /root/composio

# Install from source
RUN python -m pip install /root/composio[all] --no-deps --force-reinstall

# Remove cache
RUN rm -rf /root/composio/

# Setup user
RUN useradd -rm -d /home/user -s /bin/bash -g root -G sudo -u 1000 user

# Define entry point
COPY entrypoint.sh /root/entrypoint.sh

# Run entrypoint.sh
ENTRYPOINT [ "/root/entrypoint.sh" ]