/**
 * This script was previously used to generate MDX index pages for each OpenAPI tag.
 *
 * Those pages are NO LONGER needed — fumadocs' openapiSource() generates all API
 * reference pages automatically from the OpenAPI spec. MDX index pages in the same
 * directories would conflict with the generated routes, causing 301 redirects and 404s.
 *
 * The only files needed in content/reference/api-reference/ are meta.json files
 * that define folder titles and ordering for the sidebar.
 *
 * Run: bun scripts/generate-api-index.ts (no-op, kept for backwards compatibility)
 */

console.log('No-op: API index pages are generated by fumadocs openapiSource().');
console.log('Only meta.json files are needed in content/reference/api-reference/.');
