/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../index";
import * as ComposioApi from "../../../../../api/index";
import * as core from "../../../../../core";
import { SessionInfoDto } from "../../../../types/SessionInfoDto";
import { CustomAuthDto } from "../../../../types/CustomAuthDto";
export declare const ActionExecutionReqDto: core.serialization.Schema<serializers.ActionExecutionReqDto.Raw, ComposioApi.ActionExecutionReqDto>;
export declare namespace ActionExecutionReqDto {
    interface Raw {
        connectedAccountId?: string | null;
        appName?: string | null;
        entityId?: string | null;
        input?: Record<string, unknown> | null;
        sessionInfo?: SessionInfoDto.Raw | null;
        authConfig?: CustomAuthDto.Raw | null;
        text?: string | null;
        customDescription?: string | null;
        systemPrompt?: string | null;
        version?: string | null;
    }
}
