/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Sort the actions by usage or alphabetical
 */
export declare type ActionsQueryV2DtoSortBy = "alphabet" | "usage" | "no_sort";
export declare const ActionsQueryV2DtoSortBy: {
    readonly Alphabet: "alphabet";
    readonly Usage: "usage";
    readonly NoSort: "no_sort";
};
