/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as ComposioApi from "../index";
export interface ActionLogData {
    /** The unique identifier of the action log */
    id: string;
    /** The connection identifier associated with the action log */
    connectionId: string;
    /** The client identifier associated with the action log */
    clientId: string;
    /** The status of the action log */
    status: string;
    /** The name of the application associated with the action log */
    appName: string;
    /** The creation date and time of the action log */
    createdAt: Date;
    /** The type of the log */
    type: string;
    meta: ComposioApi.ActionMetadata;
}
