"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ActionsQueryV2DtoSortBy = void 0;
exports.ActionsQueryV2DtoSortBy = {
    Alphabet: "alphabet",
    Usage: "usage",
    NoSort: "no_sort",
};
