"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ActionProxyRequestMethodDtoType = void 0;
exports.ActionProxyRequestMethodDtoType = {
    FormData: "formData",
    UrlEncoded: "urlEncoded",
    Raw: "raw",
    Binary: "binary",
    Graphql: "graphql",
    None: "none",
};
