/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as ComposioApi from "../index";
export interface ActiveTriggersResDto {
    /** List of active trigger instances. */
    triggers: Record<string, unknown>[];
    /** Pagination information for the response. */
    pageInfo: ComposioApi.PageInfoDto[];
}
