/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as ComposioApi from "../index";
/**
 * Comprehensive trigger analytics data, presenting a breakdown by day, status, and provider for all triggers
 */
export interface ActionAnalyticsDto {
    /** Date of the action */
    date: string;
    byApp: ComposioApi.ActionByAppDto;
    byStatus: ComposioApi.ActionByStatusDto;
}
