/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface ActionDetailsMinimal {
    /** The description of the action, tailored to improve the LLM accuracy and reasoning. Use this a tool/function description. */
    description: string;
    /** The display name of the action, used to identify the action in the UI. */
    displayName: string;
    /** The logo of the app that the action belongs to. */
    logo: string;
    /** The name of the action, used to identify the action in the UI. */
    name: string;
    /** The tags of the action, used to categorize the action in the UI. */
    tags: string[];
    /** Whether the action is deprecated, if true, avoid using this action. */
    deprecated?: boolean;
}
