/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as ComposioApi from "../index";
export interface AnalyticsDataReqDto {
    /** Time period to get the data for */
    lastTimePeriod?: ComposioApi.AnalyticsDataReqDtoLastTimePeriod;
}
