/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as ComposioApi from "../index";
/**
 * Entity-related analytics data, providing a breakdown by connections, actions, and triggers for each entity. This is include all entity info.
 */
export interface AnalyticsEntityDataDto {
    byConnections: ComposioApi.ClientUniqueUserIdCountDto[];
    /** Action counts by entity */
    byActions: ComposioApi.ClientUniqueUserIdCountDto[];
    /** Trigger counts by entity */
    byTriggers: ComposioApi.ClientUniqueUserIdCountDto[];
}
