/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface ApiKeyResDto {
    /** The ID of the API key */
    id: string;
    /** The name of the API key */
    name: string;
    /** The creation date of the API key */
    createdAt: string;
    /** The last update date of the API key */
    updatedAt: string;
    /** The generated API key */
    key: string;
    /** Whether the API key is hidden */
    isHidden: boolean;
    /** The last used date of the API key */
    lastUsed?: string;
    /** The member of the API key */
    member: Record<string, unknown>;
}
