/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as ComposioApi from "../index";
export interface AppListResDto {
    /** List of app details */
    items: ComposioApi.AppInfoResponseDto[];
    /** Total number of pages */
    totalPages: number;
}
