/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as ComposioApi from "../index";
export interface AppQueryDto {
    /**
     * Filter apps by category. Used to retrieve apps belonging to a specific group or type.
     *             To get a list of available categories, see the [Get App Categories](#operation/getAppCategories) endpoint.
     */
    category?: string;
    /** Comma-separated list of additional fields to include in the response. Allows customizing the response payload for app details. Supported fields: auth_schemes */
    additionalFields?: string;
    /** Filter to include locally developed/testing apps in the response. Must be 'true' or 'false' */
    includeLocal?: ComposioApi.AppQueryDtoIncludeLocal;
    /** Sort the apps by usage or alphabetically */
    sortBy?: ComposioApi.AppQueryDtoSortBy;
}
