/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Deletion timestamp of the API key, if applicable
 */
export declare type ClientInfoApiKeyResDtoDeletedAt = string | Date;
