/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Headers to be included in API requests.
 */
export interface ConnectionParamsHeaders {
    /** Authorization header value used for API requests. */
    authorization?: string;
    /** Request ID header for tracing API calls. */
    xRequestId?: string;
}
