/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as ComposioApi from "../index";
export interface ConnectionWithAppData {
    id: string;
    integrationId: string;
    clientUniqueUserId?: string;
    status: string;
    data?: Record<string, unknown>;
    deleted?: boolean;
    enabled?: boolean;
    createdAt: ComposioApi.ConnectionWithAppDataCreatedAt;
    updatedAt: ComposioApi.ConnectionWithAppDataUpdatedAt;
    appUniqueId: string;
    appName: string;
    logo?: string;
    authConfig?: Record<string, unknown>;
    member: Record<string, unknown>;
    labels?: string[];
}
