/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface ConnectionParamsForAccount {
    /** OAuth scope for the connection. */
    scope?: string;
    /** Space-separated OAuth scopes for the connection. */
    scopes?: string;
    /** OAuth ID token for authentication. */
    idToken?: string;
    /** OAuth client ID for the application. */
    clientId?: string;
    /** Token expiration time in seconds. */
    expiresIn?: string;
    /** Type of OAuth token (e.g. 'Bearer'). */
    tokenType?: string;
    /** OAuth callback URL for the connection. */
    callbackUrl?: string;
    /** OAuth client secret for the application. */
    clientSecret?: string;
    /** PKCE code verifier used in OAuth flow. */
    codeVerifier?: string;
    /** OAuth refresh token for obtaining new access tokens. */
    refreshToken?: string;
    headers?: Record<string, unknown>;
    /** Query parameters to be included in API requests. */
    queryParams?: Record<string, unknown>;
    /** Base URL for API requests to the connected service. */
    baseUrl?: string;
}
