/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Timestamp when this connector was created. Returned in ISO 8601 format.
 */
export declare type ConnectorListItemDtoCreatedAt = string | Date;
