/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * The current status of the connection (e.g. 'active', 'inactive', 'pending').
 */
export declare type ConnectedAccountResponseDtoStatus = "INITIATED" | "ACTIVE" | "FAILED" | "EXPIRED";
export declare const ConnectedAccountResponseDtoStatus: {
    readonly Initiated: "INITIATED";
    readonly Active: "ACTIVE";
    readonly Failed: "FAILED";
    readonly Expired: "EXPIRED";
};
