"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.CreateCheckoutSessionReqDtoPlan = void 0;
exports.CreateCheckoutSessionReqDtoPlan = {
    Hobby: "HOBBY",
    Starter: "STARTER",
    Growth: "GROWTH",
    Enterprise: "ENTERPRISE",
    Startup: "STARTUP",
};
