/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as ComposioApi from "../index";
/**
 * Custom authentication credentials to use while executing an action.
 */
export interface CustomAuthDto {
    /** The base URL (root address) what you should use while making http requests to the connected account. For example, for gmail, it would be 'https://gmail.googleapis.com' */
    baseUrl?: string;
    parameters: ComposioApi.Parameter[];
    /** The body to be sent to the endpoint for authentication. This can either be a JSON field or a string. Note: This is very rarely neeed and is only required by very few apps. */
    body?: Record<string, unknown>;
}
