/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Status of the delete operation
 */
export declare type DeleteRowApidtoStatus = "success" | "failed";
export declare const DeleteRowApidtoStatus: {
    readonly Success: "success";
    readonly Failed: "failed";
};
