/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface GetActiveTriggersQueryDto {
    /** Comma-separated list of connected account IDs to filter triggers by. You can get these IDs from the `id` field in the response of the `GET /api/v1/connections` endpoint. */
    connectedAccountIds?: string;
    /** Comma-separated list of integration IDs to filter triggers by. You can get these IDs from the `id` field in the response of the `GET /api/v1/integrations` endpoint. */
    integrationIds?: string;
    /** Comma-separated list of trigger IDs to filter triggers by. You can get these IDs from the `id` field in the response of the `GET /api/v1/triggers` endpoint. */
    triggerIds?: string;
    /** Comma-separated list of trigger names to filter triggers by. You can get these names from the `name` field in the response of the `GET /api/v1/triggers` endpoint. */
    triggerNames?: string;
    /** Page number for pagination. Starts from 1. */
    page?: number;
    /** Number of items to return per page. */
    limit?: number;
    /** When set to true, includes disabled triggers in the response. */
    showDisabled?: boolean;
}
