/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface GetConnectionsQueryDto {
    /** The page number for pagination. Defaults to 1 if not specified. */
    page?: number;
    /** The number of items per page for pagination. Defaults to 99999999 if not specified - this is a temporary fix to support backward compatibility issues. Please specify this value to avoid fetching all connections at once. */
    pageSize?: number;
    /** Comma-separated list of app names to filter connections by. You can get the app names from the [/api/v1/apps](/api-reference/apps/list-apps) endpoint. */
    appNames?: string;
    /** Comma-separated list of labels to filter connections by. */
    labels?: string;
    /** Flag to show only active connections. Defaults to false if not specified. */
    showActiveOnly?: boolean;
    /** Comma-separated list of connection statuses to filter by. The statuses are 'ACTIVE', 'EXPIRED', 'FAILED', 'INITIATED'. */
    status?: string;
    /** The ID/UUID of the integration to filter connections by. You can get the integration ID from the [/api/v1/integrations](/api-reference/integrations/list-integrations) endpoint. */
    integrationId?: string;
    /** UUID of the connected account you want to get auth credentials for. You can get this from the `id` field in the response of the [/api/v1/connectedAccounts](/api-reference/connections/list-connections) endpoint. */
    connectionId?: string;
    /** Comma-separated list of entity IDs to filter connections by. This field is deprecated - please use entityId instead. */
    userUuid?: string;
    /** Comma-separated list of entity ids of the user to filter connections by. Learn more about entities [here](https://docs.composio.dev/patterns/Auth/connected_account#entities). */
    entityId?: string;
    /** Flag to include disabled connections in the results. Defaults to false if not specified. */
    showDisabled?: boolean;
}
