/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as ComposioApi from "../index";
export interface GetConnectionInfoResponseDto {
    /** The base URL of the connection. This is the starting part (or base part) of the URL that you need to send requests to. This is especially useful when you are working with apps that have dynamic urls (based on connection params) like Shopify. */
    baseUrl: string;
    parameters: ComposioApi.Parameter[];
    /** The body params to send with the request. Some apps require this to be sent in the body of the request for authentication. */
    body: Record<string, unknown>;
}
