/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Return logs from the last N time units
 */
export declare type GetLogsDtoTime = "5m" | "30m" | "6h" | "1d" | "1w" | "1month" | "1y";
export declare const GetLogsDtoTime: {
    readonly FiveM: "5m";
    readonly ThirtyM: "30m";
    readonly SixH: "6h";
    readonly OneD: "1d";
    readonly OneW: "1w";
    readonly OneMonth: "1month";
    readonly OneY: "1y";
};
