/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Filter logs by their status level, defaults to all
 */
export declare type GetLogsDtoStatus = "all" | "success" | "error";
export declare const GetLogsDtoStatus: {
    readonly All: "all";
    readonly Success: "success";
    readonly Error: "error";
};
