"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.GetLogsDtoStatus = void 0;
exports.GetLogsDtoStatus = {
    All: "all",
    Success: "success",
    Error: "error",
};
