/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface GetTriggerParamsDto {
    /** Unique identifier of the trigger to retrieve. You can get this from the `id` field in the response of the `GET /api/v1/triggers` endpoint. */
    triggerId: string;
}
