/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface IdentifyClientReqDto {
    /** The hash of the client */
    hash: string;
    /** The framework used by the client */
    framework?: string;
}
