/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface InitiateConnectionResponse {
    /** The current status of the initiated connection. */
    connectionStatus: string;
    /** The ID of the newly created connected account. */
    connectedAccountId: string;
    /** URL to redirect to for completing the connection process, if required. */
    redirectUrl?: string;
}
