/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Detailed integration analytics data, including a breakdown of connection count, trigger count, and request logs count for each integration
 */
export interface IntegrationsWithCountsDto {
    /** Unique identifier for the integration */
    id: string;
    /** Name of the app */
    appName: string;
    /** Name of the integration */
    integrationName: string;
    /** Count of connections for the integration */
    connectionCount: number;
    /** Count of triggers for the integration */
    triggerCount: number;
    /** Count of request logs for the integration */
    requestLogsCount: number;
}
