/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface MagicLinkReqDto {
    /** The email of the user */
    email: string;
    /** The frontend host of the user */
    verifyHost: string;
}
