/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as ComposioApi from "../index";
export interface Member {
    /** Unique identifier for the member */
    id: string;
    /** Organization ID associated with the member */
    orgId: string;
    /** Name of the member */
    name: string;
    /** Role of the member */
    role: string;
    /** Creation timestamp of the member */
    createdAt: ComposioApi.MemberCreatedAt;
    /** Last update timestamp of the member */
    updatedAt: ComposioApi.MemberUpdatedAt;
    /** Deletion timestamp of the member, if applicable */
    deletedAt?: ComposioApi.MemberDeletedAt;
}
