/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface Metadata {
    /** Indicates if the member has completed onboarding */
    hasCompletedOnboarding?: boolean;
}
