/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface NotFoundPlusSuggestionsError {
    /** Suggestions for the user to fix the error */
    suggestions: string[];
    /** HTTP status code */
    status: number;
    /** Error message */
    message: string;
    /** Request ID, used for tracing the request. This is very helpful for internal teams to debug issues. */
    requestId: string;
    /** The name of the operation that caused the error */
    type: "NotFoundError";
}
