/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Current state of the app FSM
 */
export declare type OpenApiSpecListResDtoState = "preprocess" | "validate" | "prepare" | "build" | "push" | "load" | "finish";
export declare const OpenApiSpecListResDtoState: {
    readonly Preprocess: "preprocess";
    readonly Validate: "validate";
    readonly Prepare: "prepare";
    readonly Build: "build";
    readonly Push: "push";
    readonly Load: "load";
    readonly Finish: "finish";
};
