"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.OpenApiSpecListResDtoState = void 0;
exports.OpenApiSpecListResDtoState = {
    Preprocess: "preprocess",
    Validate: "validate",
    Prepare: "prepare",
    Build: "build",
    Push: "push",
    Load: "load",
    Finish: "finish",
};
