/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface OrgApiKeyRegenerateResDto {
    /** Api key for organisation operations. Can be passed in the header as 'X-Org-Api-Key' */
    newApiKey: string;
}
