/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * The location of the parameter. Can be 'query' or 'header'.
 */
export declare type ParameterIn = "query" | "header";
export declare const ParameterIn: {
    readonly Query: "query";
    readonly Header: "header";
};
