"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ParameterIn = void 0;
exports.ParameterIn = {
    Query: "query",
    Header: "header",
};
