/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface PatchConnectorResDto {
    /** Status of the patch operation. Returns 'success' when the connector is successfully updated. For detailed information about possible status values, refer to the API documentation at `PATCH /api/v1/connectors/{connectorId}`. */
    status: string;
}
