/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface SingleTriggerResDto {
    /** Unique identifier of the trigger. Used to reference the trigger in other API calls. */
    name: string;
    /** Human-readable name of the trigger shown in the UI. */
    displayName: string;
    /** Detailed description of what the trigger does and when it fires. */
    description: string;
    /** Classification or category of the trigger. */
    type: string;
    /** Unique identifier of the app this trigger belongs to. You can get this from the `id` field in the response of the `GET /api/v1/apps` endpoint. */
    appId: string;
    /** Name of the app this trigger belongs to. */
    appName: string;
    /** Step-by-step instructions on how to set up and use this trigger. */
    instructions?: string;
    /** Sample payload that will be sent when the trigger fires. */
    payload: Record<string, unknown>;
    /** Configuration parameters required for the trigger. Structure varies based on trigger type. */
    config: Record<string, unknown>;
}
