/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface TConnectionCountDto {
    /** Name of the entity */
    clientUniqueUserId: string;
    /** Count of connections for the entity */
    count: number;
}
