"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.TimePeriodReqDtoLastTimePeriod = void 0;
exports.TimePeriodReqDtoLastTimePeriod = {
    Day: "DAY",
    Week: "WEEK",
    Month: "MONTH",
    SixMonth: "SIX_MONTH",
    Year: "YEAR",
    FiveYear: "FIVE_YEAR",
};
