/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Time period to get the data for
 */
export declare type TimePeriodReqDtoLastTimePeriod = "DAY" | "WEEK" | "MONTH" | "SIX_MONTH" | "YEAR" | "FIVE_YEAR";
export declare const TimePeriodReqDtoLastTimePeriod: {
    readonly Day: "DAY";
    readonly Week: "WEEK";
    readonly Month: "MONTH";
    readonly SixMonth: "SIX_MONTH";
    readonly Year: "YEAR";
    readonly FiveYear: "FIVE_YEAR";
};
