/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface TrackClientResDto {
    /** Message indicating the result of the tracking operation */
    message: string;
}
