/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as ComposioApi from "../index";
export interface TrackClientReqDto {
    /** The framework used by the client */
    framework: string;
    /** The MAC address of the client device */
    macAddress?: string;
    userGitUserInfo?: ComposioApi.UserGitUserInfo;
}
