/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as ComposioApi from "../index";
export interface TriggerLogsResDto {
    /** List of trigger log entries. */
    data: ComposioApi.TriggerLogItemDto[];
    /** Pagination information for the response. */
    pageInfo: ComposioApi.PageInfoDto;
}
