/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface TriggerInstanceParamsDto {
    /** Unique identifier of the trigger instance to modify. You can get this from the `id` field in the response of the `GET /api/v1/triggers/active` endpoint. */
    triggerInstanceId: string;
}
