/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface TriggerResponseDto {
    /** Status of the operation (success/error). */
    status: string;
    /** Additional information about the operation result. */
    message?: string;
    /** Unique identifier of the affected trigger. */
    triggerId?: string;
    /** Indicates whether a new trigger was created (true) or an existing one was modified (false). */
    isNew?: boolean;
}
