/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Metadata associated with the trigger log
 */
export interface TriggerMetadata {
    /** The unique id of the log */
    id: string;
    /** The type of the log */
    type: string;
    /** The date and time when the log was created */
    createdAt: Date;
    /** The date and time when the log was updated */
    updatedAt: Date;
    /** The provider of the log */
    provider: string;
    /** The client uuid of the log */
    clientId: string;
    /** The connection id of the log */
    connectionId: string;
    /** The trigger provider payload of the log */
    triggerProviderPayload?: string;
    triggerClientPayload?: string;
    /** The trigger client error of the log */
    triggerClientError?: string;
    /** The trigger name of the log */
    triggerName?: string;
    /** The trigger client response of the log */
    triggerClientResponse?: string;
}
