"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.UpdateRowApidtoStatus = void 0;
exports.UpdateRowApidtoStatus = {
    Success: "success",
    Failed: "failed",
};
