/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * The role that is assigned to the member
 */
export declare type UpdateMemberReqDtoRole = "admin" | "developer";
export declare const UpdateMemberReqDtoRole: {
    readonly Admin: "admin";
    readonly Developer: "developer";
};
