/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Status of the update operation
 */
export declare type UpdateRowApidtoStatus = "success" | "failed";
export declare const UpdateRowApidtoStatus: {
    readonly Success: "success";
    readonly Failed: "failed";
};
