/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface WebhookUrlResponseDto {
    /** Status of the operation (success/error). */
    status: string;
    /** The currently configured webhook callback URL. */
    callbackUrl?: string;
}
