/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as ComposioApi from "../../../../api/index";
import * as core from "../../../../core";
export declare const ActionProxyRequestConfigDtoMethod: core.serialization.Schema<serializers.ActionProxyRequestConfigDtoMethod.Raw, ComposioApi.ActionProxyRequestConfigDtoMethod>;
export declare namespace ActionProxyRequestConfigDtoMethod {
    type Raw = "GET" | "POST" | "PUT" | "PATCH" | "DELETE";
}
