"""
This module is a light wrapper around the auto-generated composio client types.
"""

import typing as t

from composio_client import NotGiven
from composio_client.types import (
    auth_config_create_params,
    auth_config_create_response,
    auth_config_list_params,
    auth_config_list_response,
    auth_config_retrieve_response,
    auth_config_update_params,
    connected_account_create_params,
    connected_account_complete_auth_response,
    connected_account_create_response,
    connected_account_list_params,
    connected_account_list_response,
    connected_account_patch_params,
    connected_account_patch_response,
    connected_account_refresh_params,
    connected_account_refresh_response,
    connected_account_retrieve_response,
    connected_account_revoke_response,
    connected_account_update_status_response,
    custom_delete_toolkit_response,
    custom_sync_response,
    custom_upsert_params,
    custom_upsert_response,
    keyring_list_transfer_keys_response,
    link_create_params,
    log_create_tool_execution_params,
    log_create_tool_execution_response,
    log_retrieve_tool_execution_response,
    tool_execute_params,
    tool_execute_response,
    tool_list_response,
    tool_proxy_params,
    tool_proxy_response,
    toolkit_list_params,
    toolkit_list_response,
    toolkit_recommend_scopes_params,
    toolkit_recommend_scopes_response,
    toolkit_retrieve_changelog_response,
    toolkit_retrieve_multi_params,
    toolkit_retrieve_multi_response,
    toolkit_retrieve_response,
    toolkit_retrieve_scopes_grant_context_params,
    toolkit_retrieve_scopes_grant_context_response,
    trigger_instance_upsert_response,
    webhook_endpoint_create_params,
    webhook_endpoint_create_response,
    webhook_endpoint_list_params,
    webhook_endpoint_list_response,
    webhook_endpoint_replace_params,
    webhook_endpoint_replace_response,
    webhook_endpoint_retrieve_response,
    webhook_endpoint_update_params,
    webhook_endpoint_update_response,
    webhook_subscription_create_params,
    webhook_subscription_create_response,
    webhook_subscription_delete_response,
    webhook_subscription_list_event_types_response,
    webhook_subscription_list_params,
    webhook_subscription_list_response,
    webhook_subscription_retrieve_response,
    webhook_subscription_rotate_secret_response,
    webhook_subscription_update_params,
    webhook_subscription_update_response,
)
from composio_client.types.project import (
    usage_retrieve_params,
    usage_retrieve_response,
    usage_retrieve_summary_params,
    usage_retrieve_summary_response,
)
from composio_client.types.tool_router import (
    session_config_history_params,
    session_config_history_response,
)

Tool: t.TypeAlias = tool_list_response.Item
ToolkitMinimal: t.TypeAlias = tool_list_response.ItemToolkit
AuthConfig: t.TypeAlias = connected_account_create_params.AuthConfig

Oauth1L: t.TypeAlias = t.Literal["OAUTH1"]
Oauth2L: t.TypeAlias = t.Literal["OAUTH2"]
ApiKeyL: t.TypeAlias = t.Literal["API_KEY"]
BasicL: t.TypeAlias = t.Literal["BASIC"]
NoAuthL: t.TypeAlias = t.Literal["NO_AUTH"]
SnowflakeL: t.TypeAlias = t.Literal["SNOWFLAKE"]
CalcomAuthL: t.TypeAlias = t.Literal["CALCOM_AUTH"]
BearerTokenL: t.TypeAlias = t.Literal["BEARER_TOKEN"]
BillcomAuthL: t.TypeAlias = t.Literal["BILLCOM_AUTH"]
ComposioLinkL: t.TypeAlias = t.Literal["COMPOSIO_LINK"]
BasicWithJwtL: t.TypeAlias = t.Literal["BASIC_WITH_JWT"]
GoogleServiceAccountL: t.TypeAlias = t.Literal["GOOGLE_SERVICE_ACCOUNT"]

AuthSchemeL: t.TypeAlias = t.Literal[
    Oauth1L,
    Oauth2L,
    ApiKeyL,
    BasicL,
    NoAuthL,
    SnowflakeL,
    CalcomAuthL,
    BearerTokenL,
    BillcomAuthL,
    ComposioLinkL,
    BasicWithJwtL,
    GoogleServiceAccountL,
]

__all__ = (
    "auth_config_create_params",
    "auth_config_create_response",
    "auth_config_list_params",
    "auth_config_list_response",
    "auth_config_retrieve_response",
    "auth_config_update_params",
    "connected_account_complete_auth_response",
    "connected_account_create_params",
    "connected_account_create_response",
    "connected_account_list_params",
    "connected_account_list_response",
    "connected_account_patch_params",
    "connected_account_patch_response",
    "connected_account_refresh_params",
    "connected_account_refresh_response",
    "connected_account_retrieve_response",
    "connected_account_revoke_response",
    "connected_account_update_status_response",
    "custom_delete_toolkit_response",
    "custom_sync_response",
    "custom_upsert_params",
    "custom_upsert_response",
    "keyring_list_transfer_keys_response",
    "link_create_params",
    "log_create_tool_execution_params",
    "log_create_tool_execution_response",
    "log_retrieve_tool_execution_response",
    "session_config_history_params",
    "session_config_history_response",
    "trigger_instance_upsert_response",
    "tool_execute_params",
    "tool_execute_response",
    "tool_list_response",
    "tool_proxy_params",
    "tool_proxy_response",
    "toolkit_list_params",
    "toolkit_list_response",
    "toolkit_recommend_scopes_params",
    "toolkit_recommend_scopes_response",
    "toolkit_retrieve_changelog_response",
    "toolkit_retrieve_multi_params",
    "toolkit_retrieve_multi_response",
    "toolkit_retrieve_response",
    "toolkit_retrieve_scopes_grant_context_params",
    "toolkit_retrieve_scopes_grant_context_response",
    "usage_retrieve_params",
    "usage_retrieve_response",
    "usage_retrieve_summary_params",
    "usage_retrieve_summary_response",
    "webhook_endpoint_create_params",
    "webhook_endpoint_create_response",
    "webhook_endpoint_list_params",
    "webhook_endpoint_list_response",
    "webhook_endpoint_replace_params",
    "webhook_endpoint_replace_response",
    "webhook_endpoint_retrieve_response",
    "webhook_endpoint_update_params",
    "webhook_endpoint_update_response",
    "webhook_subscription_create_params",
    "webhook_subscription_create_response",
    "webhook_subscription_delete_response",
    "webhook_subscription_list_event_types_response",
    "webhook_subscription_list_params",
    "webhook_subscription_list_response",
    "webhook_subscription_retrieve_response",
    "webhook_subscription_rotate_secret_response",
    "webhook_subscription_update_params",
    "webhook_subscription_update_response",
    "Tool",
    "ToolkitMinimal",
    "AuthConfig",
    "NotGiven",
    "AuthSchemeL",
)
