import path from 'node:path';
import { Command, Options } from '@effect/cli';
import { Console, Effect, Option } from 'effect';
import { FileSystem } from '@effect/platform';
import { ComposioToolkitsRepository } from 'src/services/composio-clients';
import { NodeProcess } from 'src/services/node-process';
import { createToolkitIndex } from 'src/generation/create-toolkit-index';
import type { GetCmdParams } from 'src/type-utils';
import { generateTypeScriptSources } from 'src/generation/typescript/generate';

export const outputOpt = Options.optional(
  Options.directory('output-dir', {
    exists: 'either',
  })
).pipe(
  Options.withAlias('o'),
  Options.withDescription(
    'Output directory for the generated Python type stubs (default: `./.generated/composio-py`)'
  )
);

export const singleFile = Options.boolean('single-file').pipe(
  Options.withDefault(false),
  Options.withDescription('Emit a single TypeScript file')
);

const _tsCmd$Generate = Command.make('generate', { outputOpt, singleFile }).pipe(
  Command.withDescription('Updates the local type stubs with the latest app data.')
);

export const tsCmd$Generate = _tsCmd$Generate.pipe(
  Command.withHandler(generateTypescriptTypeStubs)
);

export function generateTypescriptTypeStubs({
  outputOpt,
  singleFile,
}: GetCmdParams<typeof _tsCmd$Generate>) {
  return Effect.gen(function* () {
    const process = yield* NodeProcess;
    const cwd = process.cwd;

    const fs = yield* FileSystem.FileSystem;

    const outputDir = outputOpt.pipe(
      Option.getOrElse(() => path.join(cwd, '.generated', 'composio-ts'))
    );
    yield* fs.makeDirectory(outputDir, { recursive: true });

    yield* Console.log('Fetching latest data from Composio API...');
    const client = yield* ComposioToolkitsRepository;

    yield* Effect.logDebug('Fetching toolkits...');
    const toolkits = yield* client.getToolkits();

    yield* Effect.logDebug('Fetching tools...');
    const tools = yield* client.getTools();

    yield* Effect.logDebug('Fetching trigger types...');
    const triggerTypes = yield* client.getTriggerTypes();

    const index = createToolkitIndex({ toolkits, tools, triggerTypes });
    const sources = generateTypeScriptSources({
      banner: 'Auto-generated by Composio CLI. Do not modify manually.',
      emitSingleFile: singleFile,
      outputDir,
    })(index);

    yield* Console.log(`Writing type stubs to ${outputDir}...`);

    yield* Effect.all(sources.map(([filePath, content]) => fs.writeFileString(filePath, content)));

    return yield* Console.log('✅ Type stubs generated successfully.');
  });
}
