/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as ComposioApi from "../../../../api/index";
import * as core from "../../../../core";
import { MemberResDto } from "../../../types/MemberResDto";
export declare const Response: core.serialization.Schema<serializers.team.listMembers.Response.Raw, ComposioApi.MemberResDto[]>;
export declare namespace Response {
    type Raw = MemberResDto.Raw[];
}
