/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {}
 */
export interface ConnectionsGetConnectionsRequest {
    page?: number;
    pageSize?: number;
    appNames?: string;
    labels?: string;
    showActiveOnly?: boolean;
    status?: string;
    integrationId?: string;
    connectionId?: string;
    userUuid?: string;
    entityId?: string;
    showDisabled?: boolean;
}
