import { describe, expect, test } from 'bun:test';

import { HOME_INTENTS } from '../../lib/home-navigation';

const read = (path: string) => Bun.file(new URL(`../../${path}`, import.meta.url)).text();

/**
 * The 7 auth guides live in the Authentication folder; shared connections is a
 * session capability and lives under Extend sessions.
 */
const AUTH_GUIDES = [
  'manually-authenticating',
  'managing-multiple-connected-accounts',
  'importing-existing-connections',
  'custom-app-vs-managed-app',
  'programmatic-auth-configs',
  'controlling-scopes',
  'white-labeling-authentication',
];

const GUIDE_URLS = [
  ...AUTH_GUIDES.map(guide => `/docs/authentication/${guide}`),
  '/docs/extending-sessions/shared-connections',
];

describe('getting-started routing policy', () => {
  test('publishes native plugins for both supported agent hosts', async () => {
    const plugins = await read('content/docs/agent-plugins.mdx');

    expect(plugins).toContain('Agent plugins let Codex and Claude Code use Composio');
    expect(plugins).toContain('composio setup --target codex');
    expect(plugins).toContain('composio setup --target claude');
    expect(plugins).toContain('codex plugin marketplace add');
    expect(plugins).toContain('/plugin marketplace add');
    expect(plugins).toContain('composio search');
    expect(plugins).toContain('composio link');
    expect(plugins).toContain('composio execute');
    expect(plugins).toContain('composio --install-skill composio-cli claude');
    expect(plugins).toContain('composio --install-skill composio-cli codex');
    expect(plugins).toContain('composio setup --target auto --yes');
    expect(plugins).toContain('### Codex');
    expect(plugins).toContain('### Claude Code');
    expect(plugins).not.toContain('<Tabs');
  });

  test('keeps native plugins ahead of CLI and explicit MCP on Welcome', () => {
    expect(HOME_INTENTS[1].links.map(link => link.href)).toEqual([
      '/docs/agent-plugins',
      '/docs/cli',
      '/docs/composio-connect',
    ]);
  });

  test('keeps progressive authentication guides in the human hub and the sidebar', async () => {
    const [authentication, authMeta, sessionsMeta] = await Promise.all([
      read('content/docs/authentication/index.mdx'),
      read('content/docs/authentication/meta.json'),
      read('content/docs/extending-sessions/meta.json'),
    ]);
    const authPages = JSON.parse(authMeta).pages as string[];
    const sessionPages = JSON.parse(sessionsMeta).pages as string[];

    for (const guide of AUTH_GUIDES) {
      expect(authentication).toContain(`href="/docs/authentication/${guide}"`);
      expect(authPages).toContain(guide);
    }

    expect(authentication).toContain('href="/docs/extending-sessions/shared-connections"');
    expect(sessionPages).toContain('shared-connections');
  });

  /**
   * Asserts the generated bytes, not the meta.json inputs. These guides used to
   * be listed in llms.txt by a hardcoded `AUTHENTICATION_GUIDE_URLS` constant
   * because they had been dropped from the page tree; they are emitted by the
   * page-tree walk now, so a regression in that walk — not just in the meta
   * files — has to fail something.
   */
  test('emits every authentication guide into llms.txt exactly once', async () => {
    const { GET } = await import('../../app/llms.txt/route');
    const llms = await (await GET()).text();

    for (const url of GUIDE_URLS) {
      const occurrences = llms.split(`https://docs.composio.dev${url}.md`).length - 1;
      expect(occurrences, `${url} appears ${occurrences}x in llms.txt`).toBe(1);
    }
  });

  test('files the authentication guides under Core concepts, not a trailing section', async () => {
    const { GET } = await import('../../app/llms.txt/route');
    const lines = (await (await GET()).text()).split('\n');

    const sectionOf = (url: string) => {
      const index = lines.findIndex(line => line.endsWith(`${url}.md`));
      expect(index, `${url} missing from llms.txt`).toBeGreaterThan(-1);
      const preceding = lines.slice(0, index);
      const last = (prefix: string) => preceding.findLast(line => line.startsWith(prefix));
      return [last('## '), last('### ')];
    };

    for (const guide of AUTH_GUIDES) {
      expect(sectionOf(`/docs/authentication/${guide}`)).toEqual([
        '## Core concepts',
        '### Authentication',
      ]);
    }

    expect(sectionOf('/docs/extending-sessions/shared-connections')).toEqual([
      '## Guides',
      '### Extend sessions',
    ]);
    expect(lines).not.toContain('## Authentication guides');
  });
});
