/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as ComposioApi from "../../api/index";
import * as core from "../../core";
import { TriggerConfig } from "./TriggerConfig";
export declare const ActiveTriggerInstance: core.serialization.ObjectSchema<serializers.ActiveTriggerInstance.Raw, ComposioApi.ActiveTriggerInstance>;
export declare namespace ActiveTriggerInstance {
    interface Raw {
        id?: string | null;
        connectionId: string;
        triggerName: string;
        triggerData?: string | null;
        triggerConfig: TriggerConfig.Raw;
        createdAt: string;
        updatedAt: string;
        disabledAt?: string | null;
    }
}
