/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as ComposioApi from "../../api/index";
import * as core from "../../core";
export declare const ActionsControllerV1: core.serialization.ObjectSchema<serializers.ActionsControllerV1.Raw, ComposioApi.ActionsControllerV1>;
export declare namespace ActionsControllerV1 {
    interface Raw {
        getAction: Record<string, unknown>[];
    }
}
