/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as ComposioApi from "../../api/index";
import * as core from "../../core";
export declare const ActionsTagQueryReqDto: core.serialization.ObjectSchema<serializers.ActionsTagQueryReqDto.Raw, ComposioApi.ActionsTagQueryReqDto>;
export declare namespace ActionsTagQueryReqDto {
    interface Raw {
        apps?: string | null;
    }
}
