/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as ComposioApi from "../../api/index";
import * as core from "../../core";
export declare const ActionsTagsResponseDto: core.serialization.ObjectSchema<serializers.ActionsTagsResponseDto.Raw, ComposioApi.ActionsTagsResponseDto>;
export declare namespace ActionsTagsResponseDto {
    interface Raw {
        items: string[];
    }
}
