/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as ComposioApi from "../../api/index";
import * as core from "../../core";
export declare const ActionsQueryDto: core.serialization.ObjectSchema<serializers.ActionsQueryDto.Raw, ComposioApi.ActionsQueryDto>;
export declare namespace ActionsQueryDto {
    interface Raw {
        appNames?: string | null;
        useCase?: string | null;
        showEnabledOnly?: boolean | null;
        limit?: number | null;
        apps?: string | null;
        actions?: string | null;
        tags?: string | null;
        usecaseLimit?: number | null;
        filterImportantActions?: boolean | null;
        showAll?: boolean | null;
        page?: number | null;
    }
}
