/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as ComposioApi from "../../api/index";
import * as core from "../../core";
import { PageInfoDto } from "./PageInfoDto";
export declare const ActiveTriggersResDto: core.serialization.ObjectSchema<serializers.ActiveTriggersResDto.Raw, ComposioApi.ActiveTriggersResDto>;
export declare namespace ActiveTriggersResDto {
    interface Raw {
        triggers: Record<string, unknown>[];
        pageInfo: PageInfoDto.Raw[];
    }
}
