/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as ComposioApi from "../../api/index";
import * as core from "../../core";
export declare const AdditionalInfo: core.serialization.ObjectSchema<serializers.AdditionalInfo.Raw, ComposioApi.AdditionalInfo>;
export declare namespace AdditionalInfo {
    interface Raw {
        meta: string;
    }
}
