/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as ComposioApi from "../../api/index";
import * as core from "../../core";
export declare const AddToolsReqDto: core.serialization.ObjectSchema<serializers.AddToolsReqDto.Raw, ComposioApi.AddToolsReqDto>;
export declare namespace AddToolsReqDto {
    interface Raw {
        name: string;
        openApiSpecYaml: string;
        integrationYaml: string;
    }
}
