/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as ComposioApi from "../../api/index";
import * as core from "../../core";
export declare const AdvancedUseCaseSearchTask: core.serialization.ObjectSchema<serializers.AdvancedUseCaseSearchTask.Raw, ComposioApi.AdvancedUseCaseSearchTask>;
export declare namespace AdvancedUseCaseSearchTask {
    interface Raw {
        app: string;
        actions: string[];
        description: string;
        order: number;
    }
}
