/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as ComposioApi from "../../api/index";
import * as core from "../../core";
export declare const AdvancedUseCaseSearchBodyDto: core.serialization.ObjectSchema<serializers.AdvancedUseCaseSearchBodyDto.Raw, ComposioApi.AdvancedUseCaseSearchBodyDto>;
export declare namespace AdvancedUseCaseSearchBodyDto {
    interface Raw {
        useCase?: string | null;
    }
}
