"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.AnalyticsDataResDto = void 0;
const core = __importStar(require("../../core"));
const AnalyticsEntityDataDto_1 = require("./AnalyticsEntityDataDto");
const ActionAnalyticsDto_1 = require("./ActionAnalyticsDto");
const IntegrationsWithCountsDto_1 = require("./IntegrationsWithCountsDto");
const AppNameCountDto_1 = require("./AppNameCountDto");
exports.AnalyticsDataResDto = core.serialization.object({
    entity: AnalyticsEntityDataDto_1.AnalyticsEntityDataDto,
    actions: core.serialization.list(ActionAnalyticsDto_1.ActionAnalyticsDto),
    trigger: core.serialization.list(ActionAnalyticsDto_1.ActionAnalyticsDto),
    integrations: core.serialization.list(IntegrationsWithCountsDto_1.IntegrationsWithCountsDto),
    app: AppNameCountDto_1.AppNameCountDto,
});
