/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as ComposioApi from "../../api/index";
import * as core from "../../core";
import { ClientUniqueUserIdCountDto } from "./ClientUniqueUserIdCountDto";
export declare const AnalyticsEntityDataDto: core.serialization.ObjectSchema<serializers.AnalyticsEntityDataDto.Raw, ComposioApi.AnalyticsEntityDataDto>;
export declare namespace AnalyticsEntityDataDto {
    interface Raw {
        byConnections: ClientUniqueUserIdCountDto.Raw[];
        byActions: ClientUniqueUserIdCountDto.Raw[];
        byTriggers: ClientUniqueUserIdCountDto.Raw[];
    }
}
