/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as ComposioApi from "../../api/index";
import * as core from "../../core";
export declare const ApiKeyNotFoundError: core.serialization.ObjectSchema<serializers.ApiKeyNotFoundError.Raw, ComposioApi.ApiKeyNotFoundError>;
export declare namespace ApiKeyNotFoundError {
    interface Raw {
        name: "ApiKeyNotFoundError";
        status: number;
        message: string;
        requestId: string;
    }
}
