/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as ComposioApi from "../../api/index";
import * as core from "../../core";
export declare const AppNotFoundError: core.serialization.ObjectSchema<serializers.AppNotFoundError.Raw, ComposioApi.AppNotFoundError>;
export declare namespace AppNotFoundError {
    interface Raw {
        name: "AppNotFoundError";
        status: number;
        message: string;
        requestId: string;
        type: "NotFoundError";
    }
}
