/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as ComposioApi from "../../api/index";
import * as core from "../../core";
export declare const AppQueryDtoIncludeLocal: core.serialization.Schema<serializers.AppQueryDtoIncludeLocal.Raw, ComposioApi.AppQueryDtoIncludeLocal>;
export declare namespace AppQueryDtoIncludeLocal {
    type Raw = "true" | "false";
}
