/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as ComposioApi from "../../api/index";
import * as core from "../../core";
export declare const AuthConfigDto: core.serialization.ObjectSchema<serializers.AuthConfigDto.Raw, ComposioApi.AuthConfigDto>;
export declare namespace AuthConfigDto {
    interface Raw {
        scopes?: string[] | null;
        user_scopes?: string[] | null;
    }
}
