/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as ComposioApi from "../../api/index";
import * as core from "../../core";
import { ClientDto } from "./ClientDto";
import { ClientInfoApiKeyResDto } from "./ClientInfoApiKeyResDto";
export declare const ClientInfoResDto: core.serialization.ObjectSchema<serializers.ClientInfoResDto.Raw, ComposioApi.ClientInfoResDto>;
export declare namespace ClientInfoResDto {
    interface Raw {
        client: ClientDto.Raw;
        apiKey: ClientInfoApiKeyResDto.Raw;
    }
}
