/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as ComposioApi from "../../api/index";
import * as core from "../../core";
export declare const ClientDtoUpdatedAt: core.serialization.Schema<serializers.ClientDtoUpdatedAt.Raw, ComposioApi.ClientDtoUpdatedAt>;
export declare namespace ClientDtoUpdatedAt {
    type Raw = string | string;
}
