/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as ComposioApi from "../../api/index";
import * as core from "../../core";
export declare const ClientInfoApiKeyResDtoLastUsed: core.serialization.Schema<serializers.ClientInfoApiKeyResDtoLastUsed.Raw, ComposioApi.ClientInfoApiKeyResDtoLastUsed>;
export declare namespace ClientInfoApiKeyResDtoLastUsed {
    type Raw = string | string;
}
