/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as ComposioApi from "../../api/index";
import * as core from "../../core";
import { ClientInfoApiKeyResDtoCreatedAt } from "./ClientInfoApiKeyResDtoCreatedAt";
import { ClientInfoApiKeyResDtoUpdatedAt } from "./ClientInfoApiKeyResDtoUpdatedAt";
import { ClientInfoApiKeyResDtoDeletedAt } from "./ClientInfoApiKeyResDtoDeletedAt";
import { Member } from "./Member";
import { ClientInfoApiKeyResDtoLastUsed } from "./ClientInfoApiKeyResDtoLastUsed";
export declare const ClientInfoApiKeyResDto: core.serialization.ObjectSchema<serializers.ClientInfoApiKeyResDto.Raw, ComposioApi.ClientInfoApiKeyResDto>;
export declare namespace ClientInfoApiKeyResDto {
    interface Raw {
        id: string;
        name: string;
        clientId: string;
        memberId: string;
        createdAt: ClientInfoApiKeyResDtoCreatedAt.Raw;
        updatedAt: ClientInfoApiKeyResDtoUpdatedAt.Raw;
        deletedAt?: ClientInfoApiKeyResDtoDeletedAt.Raw | null;
        key: string;
        member: Member.Raw;
        lastUsed: ClientInfoApiKeyResDtoLastUsed.Raw;
        apiKey: string;
    }
}
