/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as ComposioApi from "../../api/index";
import * as core from "../../core";
export declare const ClientInfoApiKeyResDtoDeletedAt: core.serialization.Schema<serializers.ClientInfoApiKeyResDtoDeletedAt.Raw, ComposioApi.ClientInfoApiKeyResDtoDeletedAt>;
export declare namespace ClientInfoApiKeyResDtoDeletedAt {
    type Raw = string | string;
}
