"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.ConnectedAccountResponseDto = void 0;
const core = __importStar(require("../../core"));
const MemberInfoResDto_1 = require("./MemberInfoResDto");
const Meta_1 = require("./Meta");
const ConnectedAccountResponseDtoStatus_1 = require("./ConnectedAccountResponseDtoStatus");
exports.ConnectedAccountResponseDto = core.serialization.object({
    integrationId: core.serialization.string(),
    appUniqueId: core.serialization.string(),
    memberInfo: MemberInfoResDto_1.MemberInfoResDto.optional(),
    meta: Meta_1.Meta.optional(),
    isDisabled: core.serialization.boolean().optional(),
    id: core.serialization.string(),
    clientUniqueUserId: core.serialization.string(),
    appName: core.serialization.string(),
    entityId: core.serialization.string(),
    status: ConnectedAccountResponseDtoStatus_1.ConnectedAccountResponseDtoStatus,
    enabled: core.serialization.boolean().optional(),
    createdAt: core.serialization.string(),
    updatedAt: core.serialization.string(),
});
