/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as ComposioApi from "../../api/index";
import * as core from "../../core";
export declare const ConnectionParamsHeaders: core.serialization.ObjectSchema<serializers.ConnectionParamsHeaders.Raw, ComposioApi.ConnectionParamsHeaders>;
export declare namespace ConnectionParamsHeaders {
    interface Raw {
        Authorization?: string | null;
        "x-request-id"?: string | null;
    }
}
