/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as ComposioApi from "../../api/index";
import * as core from "../../core";
import { ConnectionWithAppDataCreatedAt } from "./ConnectionWithAppDataCreatedAt";
import { ConnectionWithAppDataUpdatedAt } from "./ConnectionWithAppDataUpdatedAt";
export declare const ConnectionWithAppData: core.serialization.ObjectSchema<serializers.ConnectionWithAppData.Raw, ComposioApi.ConnectionWithAppData>;
export declare namespace ConnectionWithAppData {
    interface Raw {
        id: string;
        integrationId: string;
        clientUniqueUserId?: string | null;
        status: string;
        data?: Record<string, unknown> | null;
        deleted?: boolean | null;
        enabled?: boolean | null;
        createdAt: ConnectionWithAppDataCreatedAt.Raw;
        updatedAt: ConnectionWithAppDataUpdatedAt.Raw;
        appUniqueId: string;
        appName: string;
        logo?: string | null;
        authConfig?: Record<string, unknown> | null;
        member: Record<string, unknown>;
        labels?: string[] | null;
    }
}
