/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as ComposioApi from "../../api/index";
import * as core from "../../core";
export declare const ConnectionParamsUpdatedAt: core.serialization.Schema<serializers.ConnectionParamsUpdatedAt.Raw, ComposioApi.ConnectionParamsUpdatedAt>;
export declare namespace ConnectionParamsUpdatedAt {
    type Raw = string | string;
}
