/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as ComposioApi from "../../api/index";
import * as core from "../../core";
export declare const ConnectorListItemDtoCreatedAt: core.serialization.Schema<serializers.ConnectorListItemDtoCreatedAt.Raw, ComposioApi.ConnectorListItemDtoCreatedAt>;
export declare namespace ConnectorListItemDtoCreatedAt {
    type Raw = string | string;
}
