/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as ComposioApi from "../../api/index";
import * as core from "../../core";
export declare const Data: core.serialization.ObjectSchema<serializers.Data.Raw, ComposioApi.Data>;
export declare namespace Data {
    interface Raw {
        field1: string;
        field2: string;
    }
}
