/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as ComposioApi from "../../api/index";
import * as core from "../../core";
import { DeleteRowApidtoStatus } from "./DeleteRowApidtoStatus";
export declare const DeleteRowApidto: core.serialization.ObjectSchema<serializers.DeleteRowApidto.Raw, ComposioApi.DeleteRowApidto>;
export declare namespace DeleteRowApidto {
    interface Raw {
        status: DeleteRowApidtoStatus.Raw;
        count: number;
    }
}
