/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as ComposioApi from "../../api/index";
import * as core from "../../core";
export declare const DirectExecuteReqDto: core.serialization.ObjectSchema<serializers.DirectExecuteReqDto.Raw, ComposioApi.DirectExecuteReqDto>;
export declare namespace DirectExecuteReqDto {
    interface Raw {
        endpoint: string;
        base_url: string;
        headers: Record<string, unknown>;
        queryParams: Record<string, unknown>;
        body?: Record<string, unknown> | null;
    }
}
