/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as ComposioApi from "../../api/index";
import * as core from "../../core";
export declare const ExecuteActionResDto: core.serialization.ObjectSchema<serializers.ExecuteActionResDto.Raw, ComposioApi.ExecuteActionResDto>;
export declare namespace ExecuteActionResDto {
    interface Raw {
        response_data: boolean;
        execution_details: Record<string, unknown>;
    }
}
