/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as ComposioApi from "../../api/index";
import * as core from "../../core";
export declare const FetchTokenError: core.serialization.ObjectSchema<serializers.FetchTokenError.Raw, ComposioApi.FetchTokenError>;
export declare namespace FetchTokenError {
    interface Raw {
        name: "FetchTokenError";
        status: number;
        message: string;
        requestId: string;
    }
}
