/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as ComposioApi from "../../api/index";
import * as core from "../../core";
export declare const FetchQueryDto: core.serialization.ObjectSchema<serializers.FetchQueryDto.Raw, ComposioApi.FetchQueryDto>;
export declare namespace FetchQueryDto {
    interface Raw {
        startTime: string;
        endTime: string;
    }
}
