/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as ComposioApi from "../../api/index";
import * as core from "../../core";
export declare const GetConnectionsHeaderParamsDto: core.serialization.ObjectSchema<serializers.GetConnectionsHeaderParamsDto.Raw, ComposioApi.GetConnectionsHeaderParamsDto>;
export declare namespace GetConnectionsHeaderParamsDto {
    interface Raw {
        "x-project-id"?: string | null;
    }
}
