/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as ComposioApi from "../../api/index";
import * as core from "../../core";
import { ConnectionParams } from "./ConnectionParams";
export declare const GetConnectionsResponseDto: core.serialization.ObjectSchema<serializers.GetConnectionsResponseDto.Raw, ComposioApi.GetConnectionsResponseDto>;
export declare namespace GetConnectionsResponseDto {
    interface Raw {
        items: ConnectionParams.Raw[];
        totalPages: number;
        page: number;
    }
}
