/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as ComposioApi from "../../api/index";
import * as core from "../../core";
import { Parameter } from "./Parameter";
export declare const GetConnectionInfoResponseDto: core.serialization.ObjectSchema<serializers.GetConnectionInfoResponseDto.Raw, ComposioApi.GetConnectionInfoResponseDto>;
export declare namespace GetConnectionInfoResponseDto {
    interface Raw {
        base_url: string;
        parameters: Parameter.Raw[];
        body: Record<string, unknown>;
    }
}
