/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as ComposioApi from "../../api/index";
import * as core from "../../core";
export declare const GetLogsQueryDto: core.serialization.ObjectSchema<serializers.GetLogsQueryDto.Raw, ComposioApi.GetLogsQueryDto>;
export declare namespace GetLogsQueryDto {
    interface Raw {
        connectionId?: string | null;
        integrationId?: string | null;
        page?: number | null;
        limit?: number | null;
    }
}
