/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as ComposioApi from "../../api/index";
import * as core from "../../core";
export declare const GetSingleActionQueryDto: core.serialization.ObjectSchema<serializers.GetSingleActionQueryDto.Raw, ComposioApi.GetSingleActionQueryDto>;
export declare namespace GetSingleActionQueryDto {
    interface Raw {
        version?: string | null;
    }
}
