/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as ComposioApi from "../../api/index";
import * as core from "../../core";
export declare const HttpError: core.serialization.ObjectSchema<serializers.HttpError.Raw, ComposioApi.HttpError>;
export declare namespace HttpError {
    interface Raw {
        status: number;
        message: string;
        requestId: string;
    }
}
