/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as ComposioApi from "../../api/index";
import * as core from "../../core";
export declare const InvalidTriggerConfigError: core.serialization.ObjectSchema<serializers.InvalidTriggerConfigError.Raw, ComposioApi.InvalidTriggerConfigError>;
export declare namespace InvalidTriggerConfigError {
    interface Raw {
        name: "InvalidTriggerConfigError";
        status: number;
        message: string;
        requestId: string;
        details: Record<string, unknown>;
        type: "BadRequestError";
    }
}
