/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as ComposioApi from "../../api/index";
import * as core from "../../core";
export declare const ListTriggersQueryDto: core.serialization.ObjectSchema<serializers.ListTriggersQueryDto.Raw, ComposioApi.ListTriggersQueryDto>;
export declare namespace ListTriggersQueryDto {
    interface Raw {
        appNames?: string | null;
        connectedAccountIds?: string | null;
        triggerIds?: string | null;
        triggerNames?: string | null;
        integrationIds?: string | null;
        showEnabledOnly?: boolean | null;
    }
}
