/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as ComposioApi from "../../api/index";
import * as core from "../../core";
export declare const MagicLinkReqDto: core.serialization.ObjectSchema<serializers.MagicLinkReqDto.Raw, ComposioApi.MagicLinkReqDto>;
export declare namespace MagicLinkReqDto {
    interface Raw {
        email: string;
        verifyHost: string;
    }
}
