/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as ComposioApi from "../../api/index";
import * as core from "../../core";
export declare const MemberInfoResDtoUpdatedAt: core.serialization.Schema<serializers.MemberInfoResDtoUpdatedAt.Raw, ComposioApi.MemberInfoResDtoUpdatedAt>;
export declare namespace MemberInfoResDtoUpdatedAt {
    type Raw = string | string;
}
