"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.MemberInfoResDto = void 0;
const core = __importStar(require("../../core"));
const MemberInfoResDtoRole_1 = require("./MemberInfoResDtoRole");
const MemberInfoResDtoCreatedAt_1 = require("./MemberInfoResDtoCreatedAt");
const MemberInfoResDtoUpdatedAt_1 = require("./MemberInfoResDtoUpdatedAt");
const MemberInfoResDtoDeletedAt_1 = require("./MemberInfoResDtoDeletedAt");
exports.MemberInfoResDto = core.serialization.object({
    id: core.serialization.string(),
    orgId: core.serialization.string(),
    email: core.serialization.string(),
    name: core.serialization.string(),
    role: MemberInfoResDtoRole_1.MemberInfoResDtoRole,
    metadata: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
    createdAt: MemberInfoResDtoCreatedAt_1.MemberInfoResDtoCreatedAt,
    updatedAt: MemberInfoResDtoUpdatedAt_1.MemberInfoResDtoUpdatedAt,
    deletedAt: MemberInfoResDtoDeletedAt_1.MemberInfoResDtoDeletedAt.optional(),
});
