/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as ComposioApi from "../../api/index";
import * as core from "../../core";
export declare const MemberUpdatedAt: core.serialization.Schema<serializers.MemberUpdatedAt.Raw, ComposioApi.MemberUpdatedAt>;
export declare namespace MemberUpdatedAt {
    type Raw = string | string;
}
