/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as ComposioApi from "../../api/index";
import * as core from "../../core";
export declare const MemberInfoResDtoRole: core.serialization.Schema<serializers.MemberInfoResDtoRole.Raw, ComposioApi.MemberInfoResDtoRole>;
export declare namespace MemberInfoResDtoRole {
    type Raw = "admin" | "developer";
}
