/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as ComposioApi from "../../api/index";
import * as core from "../../core";
export declare const Meta: core.serialization.ObjectSchema<serializers.Meta.Raw, ComposioApi.Meta>;
export declare namespace Meta {
    interface Raw {
        app: Record<string, unknown>;
    }
}
