/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as ComposioApi from "../../api/index";
import * as core from "../../core";
export declare const PageInfo: core.serialization.ObjectSchema<serializers.PageInfo.Raw, ComposioApi.PageInfo>;
export declare namespace PageInfo {
    interface Raw {
        total: number;
        page: number;
        pageSize: number;
        totalPages: number;
    }
}
