/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as ComposioApi from "../../api/index";
import * as core from "../../core";
export declare const PageInfoDto: core.serialization.ObjectSchema<serializers.PageInfoDto.Raw, ComposioApi.PageInfoDto>;
export declare namespace PageInfoDto {
    interface Raw {
        currentPage: number;
        perPage: number;
        totalPages: number;
    }
}
