/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as ComposioApi from "../../api/index";
import * as core from "../../core";
import { ParameterIn } from "./ParameterIn";
export declare const Parameter: core.serialization.ObjectSchema<serializers.Parameter.Raw, ComposioApi.Parameter>;
export declare namespace Parameter {
    interface Raw {
        name: string;
        in: ParameterIn.Raw;
        value: string;
    }
}
