/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as ComposioApi from "../../api/index";
import * as core from "../../core";
export declare const ParameterIn: core.serialization.Schema<serializers.ParameterIn.Raw, ComposioApi.ParameterIn>;
export declare namespace ParameterIn {
    type Raw = "query" | "header";
}
