/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as ComposioApi from "../../api/index";
import * as core from "../../core";
import { ProjectResDto } from "./ProjectResDto";
export declare const ProjectListResDto: core.serialization.ObjectSchema<serializers.ProjectListResDto.Raw, ComposioApi.ProjectListResDto>;
export declare namespace ProjectListResDto {
    interface Raw {
        items: ProjectResDto.Raw[];
    }
}
