/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as ComposioApi from "../../api/index";
import * as core from "../../core";
export declare const ProjectDeleteReqDto: core.serialization.ObjectSchema<serializers.ProjectDeleteReqDto.Raw, ComposioApi.ProjectDeleteReqDto>;
export declare namespace ProjectDeleteReqDto {
    interface Raw {
        projectId: string;
    }
}
