/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as ComposioApi from "../../api/index";
import * as core from "../../core";
export declare const ProjectResDto: core.serialization.ObjectSchema<serializers.ProjectResDto.Raw, ComposioApi.ProjectResDto>;
export declare namespace ProjectResDto {
    interface Raw {
        id: string;
        name: string;
        createdAt: string;
        primaryApiKey: string;
    }
}
