/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as ComposioApi from "../../api/index";
import * as core from "../../core";
export declare const ReadOnlyQueryReqDto: core.serialization.ObjectSchema<serializers.ReadOnlyQueryReqDto.Raw, ComposioApi.ReadOnlyQueryReqDto>;
export declare namespace ReadOnlyQueryReqDto {
    interface Raw {
        query: string;
    }
}
