/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as ComposioApi from "../../api/index";
import * as core from "../../core";
export declare const SwitchTriggerStatusParamsDto: core.serialization.ObjectSchema<serializers.SwitchTriggerStatusParamsDto.Raw, ComposioApi.SwitchTriggerStatusParamsDto>;
export declare namespace SwitchTriggerStatusParamsDto {
    interface Raw {
        triggerId: string;
    }
}
