/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as ComposioApi from "../../api/index";
import * as core from "../../core";
export declare const TConnectionCountDto: core.serialization.ObjectSchema<serializers.TConnectionCountDto.Raw, ComposioApi.TConnectionCountDto>;
export declare namespace TConnectionCountDto {
    interface Raw {
        clientUniqueUserId: string;
        count: number;
    }
}
