/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as ComposioApi from "../../api/index";
import * as core from "../../core";
export declare const ToolsExecuteReqDto: core.serialization.ObjectSchema<serializers.ToolsExecuteReqDto.Raw, ComposioApi.ToolsExecuteReqDto>;
export declare namespace ToolsExecuteReqDto {
    interface Raw {
        actionName: string;
        runInSandbox: boolean;
        input: Record<string, unknown>;
        nlaInput?: string | null;
        authorizationData?: Record<string, unknown> | null;
        appSchema?: Record<string, unknown> | null;
        customDescription?: string | null;
        systemPrompt?: string | null;
        version?: string | null;
    }
}
