/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as ComposioApi from "../../api/index";
import * as core from "../../core";
export declare const TrackClientResDto: core.serialization.ObjectSchema<serializers.TrackClientResDto.Raw, ComposioApi.TrackClientResDto>;
export declare namespace TrackClientResDto {
    interface Raw {
        message: string;
    }
}
