/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as ComposioApi from "../../api/index";
import * as core from "../../core";
export declare const TriggerResponseDto: core.serialization.ObjectSchema<serializers.TriggerResponseDto.Raw, ComposioApi.TriggerResponseDto>;
export declare namespace TriggerResponseDto {
    interface Raw {
        status: string;
        message?: string | null;
        triggerId?: string | null;
        isNew?: boolean | null;
    }
}
