/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as ComposioApi from "../../api/index";
import * as core from "../../core";
export declare const TriggerInstanceParamsDto: core.serialization.ObjectSchema<serializers.TriggerInstanceParamsDto.Raw, ComposioApi.TriggerInstanceParamsDto>;
export declare namespace TriggerInstanceParamsDto {
    interface Raw {
        triggerInstanceId: string;
    }
}
