/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as ComposioApi from "../../api/index";
import * as core from "../../core";
export declare const TriggersEnabledToggleReqDto: core.serialization.ObjectSchema<serializers.TriggersEnabledToggleReqDto.Raw, ComposioApi.TriggersEnabledToggleReqDto>;
export declare namespace TriggersEnabledToggleReqDto {
    interface Raw {
        enabled: boolean;
    }
}
