/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as ComposioApi from "../../api/index";
import * as core from "../../core";
import { TriggerMetadata } from "./TriggerMetadata";
export declare const TriggerLogData: core.serialization.ObjectSchema<serializers.TriggerLogData.Raw, ComposioApi.TriggerLogData>;
export declare namespace TriggerLogData {
    interface Raw {
        id: string;
        connectionId: string;
        clientId: string;
        status: string;
        appName: string;
        createdAt: string;
        type: string;
        meta: TriggerMetadata.Raw;
    }
}
