/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as ComposioApi from "../../api/index";
import * as core from "../../core";
export declare const TriggerMetadata: core.serialization.ObjectSchema<serializers.TriggerMetadata.Raw, ComposioApi.TriggerMetadata>;
export declare namespace TriggerMetadata {
    interface Raw {
        id: string;
        type: string;
        createdAt: string;
        updatedAt: string;
        provider: string;
        clientId: string;
        connectionId: string;
        triggerProviderPayload?: string | null;
        triggerClientPayload?: string | null;
        triggerClientError?: string | null;
        triggerName?: string | null;
        triggerClientResponse?: string | null;
    }
}
