/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as ComposioApi from "../../api/index";
import * as core from "../../core";
export declare const TriggersEnabledToggleResDto: core.serialization.ObjectSchema<serializers.TriggersEnabledToggleResDto.Raw, ComposioApi.TriggersEnabledToggleResDto>;
export declare namespace TriggersEnabledToggleResDto {
    interface Raw {
        message: string;
    }
}
