/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as ComposioApi from "../../api/index";
import * as core from "../../core";
export declare const UpdateRowApidtoStatus: core.serialization.Schema<serializers.UpdateRowApidtoStatus.Raw, ComposioApi.UpdateRowApidtoStatus>;
export declare namespace UpdateRowApidtoStatus {
    type Raw = "success" | "failed";
}
