/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as ComposioApi from "../../api/index";
import * as core from "../../core";
import { UpdateMemberReqDtoRole } from "./UpdateMemberReqDtoRole";
export declare const UpdateMemberReqDto: core.serialization.ObjectSchema<serializers.UpdateMemberReqDto.Raw, ComposioApi.UpdateMemberReqDto>;
export declare namespace UpdateMemberReqDto {
    interface Raw {
        memberId: string;
        role: UpdateMemberReqDtoRole.Raw;
    }
}
