/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as ComposioApi from "../../api/index";
import * as core from "../../core";
import { UpdateRowApidtoStatus } from "./UpdateRowApidtoStatus";
export declare const UpdateRowApidto: core.serialization.ObjectSchema<serializers.UpdateRowApidto.Raw, ComposioApi.UpdateRowApidto>;
export declare namespace UpdateRowApidto {
    interface Raw {
        status: UpdateRowApidtoStatus.Raw;
        count: number;
    }
}
