/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as ComposioApi from "../../api/index";
import * as core from "../../core";
export declare const UserGitUserInfo: core.serialization.ObjectSchema<serializers.UserGitUserInfo.Raw, ComposioApi.UserGitUserInfo>;
export declare namespace UserGitUserInfo {
    interface Raw {
        name?: string | null;
        email: string;
    }
}
