/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as ComposioApi from "../../api/index";
import * as core from "../../core";
export declare const VerifyMagicLinkReqDto: core.serialization.ObjectSchema<serializers.VerifyMagicLinkReqDto.Raw, ComposioApi.VerifyMagicLinkReqDto>;
export declare namespace VerifyMagicLinkReqDto {
    interface Raw {
        token: string;
    }
}
