/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {}
 */
export interface TriggersGetActiveTriggersRequest {
    connectedAccountIds?: string;
    integrationIds?: string;
    triggerIds?: string;
    triggerNames?: string;
    page?: number;
    limit?: number;
    showDisabled?: boolean;
}
