/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {
 *         id: "id",
 *         isNewWebhook: true
 *     }
 */
export interface WehbookNewFormatDto {
    /** Unique identifier of the project. */
    id: string;
    /** Indicates whether this is a newly created webhook. */
    isNewWebhook: boolean;
}
