name: Docs - Check Links

on:
  pull_request:
    paths:
      - 'docs/**'
      - '.github/actions/setup-node-pnpm-bun/action.yml'
      - '.github/workflows/docs-check-links.yml'
      - 'mise.toml'
      - 'mise.lock'

jobs:
  check-links:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docs

    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Setup Node.js, pnpm, Bun
        uses: ./.github/actions/setup-node-pnpm-bun

      - name: Install dependencies
        run: bun install

      - name: Validate links
        run: bun run lint:links
